### ISSUE TITLE
Calls open method on Windows during searching for a file and viewing a file property

### ISSUE THREAD

**Issue by arvgord** [billziss-gh/winfsp#247] opened 2019-08-28 12:06 UTC
## Bug Report

Hi, @billziss-gh !

I use [jnr-fuse](https://github.com/SerCeMan/jnr-fuse)(which uses WinFsp) in [FUSE plugin](https://github.com/GoogleCloudPlatform/healthcare-api-dicom-fuse) for the Google Cloud Healthcare DICOM API. It works perfect on Linux but on Windows, I got the issue.
In the open method, I implemented a retrieving DICOM file from the server and cache it in the user's local storage on disk. When I open a file, I cache it and get file size from the server. I found that on Windows calls open method during searching for a file and viewing a file property. This greatly reduces performance because I get unnecessary caching while searching for files. But in Linux(with libfuse) open method calls only when I open a file. Could you help me with this issue?

### How to Reproduce

In DICOMFuse, also in jnr-fuse examples, this problem occurs similarly (calls open method).

### Behaviors

Don't call the open method before opening a file.
Because on some network file systems, a file may be requested from a server in the open method.

### Environment

- OS version and build: Windows 10x64 1809 17763.379 (in others Windows it works similarly)
- WinFsp version and build: WinFsp 2019.2, WinFsp-FUSE version 2.8 (used in jnr-fuse)

**Comment by billziss-gh** [comment] 2019-08-28 12:30
Unfortunately this problem happens due to Windows file system design and is not a bug.

In Windows most file system operations require a file handle. This means that the file must be opened first, then some I/O is sent to the file handle and then the file handle is closed.

Because of this Windows sends a lot of `open`/`close` calls to the file system. Windows expects that the `open` call is relatively cheap and sends it with impunity. For example to get file metadata (i.e. "stat" information), Windows may open the file (`IRP_MJ_CREATE`), send multiple information queries (`IRP_MJ_QUERY_INFORMATION`) and then close it (`IRP_MJ_CLEANUP`, `IRP_MJ_CLOSE`). WinFsp optimizes many of these calls away by using a variety of caches (for information queries), or sending some of these calls asynchronously (close) or completely eliminating some calls in certain circumstances (cleanup). But most `open` calls must eventually make it to the file system (latest WinFsp betas have a method to eliminate some of the `open` calls as well).

Unfortunately your solution is to design your file system around this fact. For example, in [objfs](https://github.com/billziss-gh/objfs) I avoid doing any expensive cloud calls during `open`. Instead I delay expensive cloud operations like fetching a file, until I have an actual `read`/`write`/etc. operation to satisfy.

**Comment by arvgord** [comment] 2019-08-29 05:45
Thanks for the detailed answer!
I can include caching operation from a server in the read method, but I found when searching for a file in a folder, read method may be called. It also leads to unnecessary caching. Could you give me advice on how I can work around this (e.g. using some option to start WinFsp)?

**Comment by billziss-gh** [comment] 2019-08-31 03:08
When listing  a directory, you will receive `readdir` calls, but not `read`. However Explorer often opens up files to show thumbnails, etc.

One way around this is to mount the file system as a "network" file system (i.e. use the `--VolumePrefix=\SERVER\PATH` syntax. I believe Explorer will not try to show thumbnails for network file systems.

**Comment by arvgord** [comment] 2019-08-31 05:44
> However Explorer often opens up files to show thumbnails, etc.

I think that `read` caused by thumbnails.
Thanks! It works fine with `VolumePrefix=\SERVER\PATH`, but search through Explorer does not work. Is this expected behavior?

**Comment by billziss-gh** [comment] 2019-09-03 19:17
There are tradeoffs when exposing a file system as a "disk" vs a "network" file system. Different applications and services provide different amounts of functionality (as you are discovering).

In general "disk"  file systems are considered fast and more functionality will be made available for  them; this functionality may make your file system slow depending  on its  design and how much caching it does. OTOH "network" file systems are considered slow and less functionality is made available for them; this is under the assumption that such functionality is slow to offer over a network.

I believe Windows Search works through an index and to build the index, most/all files in the file system must be visited. This is obviously expensive in a  "network" file system, so it is likely off by default.

I am closing this issue as I believe the original question has been addressed. Feel free to reopen if you find otherwise.

**Closed by billziss-gh** 2019-09-03 19:17 UTC

**Comment by arvgord** [comment] 2019-09-04 10:56
Thank for the detailed information! It was very helpful!

**Comment by susarlanikhilesh** [comment] 2023-06-05 12:09
Is there a way to stop getting Read call while traversing files using winfsp ?
