### ISSUE TITLE
WinFSP causes Exact Audio Copy to crash on File Dialog

### ISSUE THREAD

**Issue by TeutonJon78** [billziss-gh/winfsp#162] opened 2018-04-26 23:58 UTC
With WinFSP installed, without anything even mounted, EAC crashes when opening the save dialog. The program worked fine before installation and after installation.

http://www.exactaudiocopy.de/
http://www.digital-inn.de/threads/eac-crashes-when-fuse-file-system-installed-winfsp.47548/

Apparently, it happens with Dokany as well, so it might be a more fundamental issue in Windows.

Steps:
1. put CD in
2. in EAC go to Action > and pick either compressed or uncompressed

With WinFSP installed -- EAC will crash
Without WinFSP installed -- EAC will open a file dialog asking where you want to save the files

Environment:
Win 10 Pro -- 16299.374
WinFSP -- 2017.2

----

Before submitting this issue please review this checklist. Ideally all checkmarks should be checked upon submitting. (Use an x inside square brackets like so: [x])

- [x] **Issue type**: Please consider posting only bug reports or enhancement requests. Questions are better in the [WinFsp Google Group](https://groups.google.com/forum/#!forum/winfsp). Please also consult the [WinFsp Frequently Asked Questions](https://github.com/billziss-gh/winfsp/wiki/Frequently-Asked-Questions).
- [x] **No Duplicate**: Ensure that your issue has not been filed before. (Check open and closed issues.)
- [x] **Description**: Provide a descriptive title and a detailed explanation of the problem you are experiencing (for a bug report) or you are trying to solve (for an enhancement request).
- [x] **Reproduce**: For bug reports provide detailed information on how to reproduce the problem. For enhancement requests you do not need to provide this information, unless you find it relevant.
- [x] **Behaviors**: Provide information on the expected and actual behaviors.
- [x] **Environment**: For bug reports provide information about your OS version and build (e.g. 10.0.14393) and WinFsp version and build (e.g. 2017.2 or 1.2.17341). For enhancement requests you do not need to provide this information, unless you find it relevant.

**Comment by billziss-gh** [comment] 2018-04-27 00:53
@TeutonJon78 when there is no file system mounted, there are 2 active WinFsp components:

1. The WinFsp "Launcher" which is a Windows service that allows launching file systems in the Windows Services context.

2. The WinFsp "Network Provider" which is used to facilitate the "map network drive" functionality.

From your description of the problem I can only see the "Network Provider" as the culprit. It is likely that somehow this functionality causes EAC to crash.

Is it possible to collect an application crash dump?

**Comment by billziss-gh** [comment] 2018-04-30 23:09
I can confirm that this is indeed a problem with the WinFsp Network Provider.

The problem is that EAC is a 32-bit application and the WinFsp Network Provider is 64-bits on a 64-bit system and 32-bits on a 32-bit system. Thus (on a 64-bit OS) we have the unfortunate situation of a 32-bit program trying to load a 64-bit DLL. The result: CRASH!

The main culprit are the registry entries in this location: `HKLM\SYSTEM\CurrentControlSet\Services\WinFsp.Np\NetworkProvider`. The `ProviderPath` points to the 64-bit DLL `C:\Program Files (x86)\WinFsp\bin\winfsp-x64.dll` regardless of whether the app is 64-bit or 32-bit.

Possible solutions:

- Use WOW64 registry redirection to redirect `HKLM\SYSTEM\CurrentControlSet\Services\WinFsp.Np\NetworkProvider` `ProviderPath` to the 32-bit DLL, when used by a 32-bit program. This may not possible, as registry redirection may be restricted to `HKLM\SYSTEM\Software`.

- Use WOW64 file system redirection to redirect the 64-bit DLL to the 32-bit one. This can work by storing the DLL's in the `System32` and `Syswow64` folders. It may also work by splitting WinFsp into 64-bit components in `\Program Files` and 32-bit components in `\Program Files (x86)`.
    - The WinFsp project has tried hard to avoid installing components in system directories (such as `System32` and `Syswow64`).

- Perhaps system environment variables (e.g. `%ProgramFiles(x86)%`, `%ProgramW6432%`, etc.) can be used instead.

**Comment by billziss-gh** [comment] 2018-04-30 23:40
Some further thoughts and a possible plan for action:

- Refactor the WinFsp.Np code out of the main `winfsp-*.dll` and into a new DLL (say `winfsp.np.dll`).
- Install that DLL under `bin\amd64` or `bin\x86` depending on intended processor architecture.
- Change the Network Provider `ProviderPath` under `HKLM\SYSTEM\CurrentControlSet\Services\WinFsp.Np\NetworkProvider` to be of type `REG_EXPAND_SZ` and have the value `C:\Program Files (x86)\WinFsp\bin\%PROCESSOR_ARCHITECTURE%\winfsp.np.dll`.

Some tests on a VM showed that this should work. It is unclear whether the `%PROCESSOR_ARCHITECTURE%` environment variable is guaranteed to exist though.

**Comment by billziss-gh** [comment] 2018-05-01 18:35
> Weird, I wrote a comment, but I must not have submitted it. Do you need logs still (doesn't seem like it)? I had also tested it a little more, and disabling the WinFSP service didn't change the effect at all, so I definitely concur it's in the Network Provider code.

I no longer need logs as I was able to reproduce and determine the cause of the problem.

> It seems like a bug more in Windows that would allow this to happen at all -- a program opening up the dialog should be able to happen on all 32 apps with 64-bit OS. I imagine other 32-bit programs might run into this same problem as well. Thanks for investigating.

I tend to agree, because the crash appeared to happen in [`WNetOpenEnumW`](https://msdn.microsoft.com/en-us/library/windows/desktop/aa385478(v=vs.85).aspx). But I would like to better understand this crash, because I tried some other 32-bit programs (notably the 32-bit version of `net.exe` found in `\Windows\syswow64\net.exe`) that use the Network Provider and they seemed to work without problems (they could not load the network provider DLL, but they would not crash either).

Are the EAC folks responsive at all? Could we contact them regarding this issue?

**Comment by TeutonJon78** [comment] 2018-05-01 18:56
I don't think they are all that responsive. The last version was in 2016, and most support requests on the forum go unanswered or only by other users, it seems.

Browsing the forums it seems they've had a history of 64-bit problems. Some people linked it to the cygwin1.dll used in the CDRAO portion of the program. I tried upgrading that, with both snapshot 32-bit and 64-bit versions, but it didn't affect the crash. (It might be a different 64-bit error those were trying to correct). The thread I originally linked was from 2017-12, with zero responses.

If WinFSP is coded correctly in this regard, I'd hate for you to do some odd workaround just for this one program, especially with other 32-bit programs working correctly.

**Comment by android-808** [comment] 2019-06-11 07:55
Dokany had a similar issue and appear to have a solution.
https://github.com/dokan-dev/dokany/issues/545

**Comment by billziss-gh** [comment] 2019-06-11 17:08
@android-808 have you encountered this problem on an app other than Exact Audio Copy?

**Comment by android-808** [comment] 2019-06-11 22:16
Not at the moment, only been using winfsp a couple of weeks. Most apps I use are native 64bit so I'd need to spend a bit longer with it to try and find some others.

Unfortunately EAC, although somewhat dormant at the moment, is still one of the best apps in terms of accurate/secure rips, particularly as it's free. It only plays a small role in my toolchain for creating cue sheets formatted a specific way.

**Comment by billziss-gh** [comment] 2019-06-11 22:23
@android-808 understood.

When I looked at this problem more closely (see above comments) it appeared to me that the problem was not with WinFsp, but with EAC (as evidenced by the fact that the problem appears with Dokany as well).

For this reason I am less inclined to modify WinFsp to work around a problem in a single app, especially because this would require WinFsp to place files in the \Windows\System32 directory.

**Comment by android-808** [comment] 2019-06-11 22:34
Fair enough. I've tried going through the EAC mailing list for the last 10 months but can't find any signs of progress. Their forum is also down. One user also mentioned tortoisesvn "causing" issues with EAC.

If I can find any other apps having issues with winfsp I'll report back.

**Comment by billziss-gh** [comment] 2019-06-11 22:41
@android-808 thanks for the understanding.

Although it would require me to change one of the fundamental principles of WinFsp packaging (**do not place files in system directories**), I would still do it if it turned out that there were more apps affected by this issue.

**Comment by asm0dey** [comment] 2019-06-17 07:20
https://www.freac.org/ possibly could be fine workaround for this issue (I mean use it instead of unsupported EAC)

**Comment by Svekla** [comment] 2019-06-27 13:37
Is there any simple workaround that I could do before running EAC (other than uninstalling, rebooting, running EAC and then reinstalling WinFSP)? Thanks for help.

**Comment by atrugiel69** [comment] 2020-01-26 17:21
Svekla, thank you so much for sharing your solution. Once you set up a default directory you can actually avoid removing the registry entry. I guess it could probably done by manually inputting the path to the default directory, without invoking the file requester.

**Comment by thegreatestminer** [comment] 2020-12-15 15:17
Just prodding this issue after almost an entire year, this problem still exists.

Removing the registry entry or temporarily uninstalling fixes the issue.

**Comment by billziss-gh** [comment] 2020-12-15 17:43
I am not planning to do anything in WinFsp about this issue. My reasons are:

- The problem is likely with EAC and not WinFsp.
- The EAC app is an old 32-bit app even on 64-bit Windows.
- I am not aware of any other app (including 32-bit apps on 64-bit Windows) that has the same problem.
- Working around the problem requires major restructuring of the WinFsp DLL.
- Working around the problem possibly requires installation of files in the Windows system directories (which WinFsp does not do).

I will close this issue with a *wontfix* label. However I will certainly revisit this if more 32-bit apps turn out to have the same problem.

**Closed by billziss-gh** 2020-12-15 17:43 UTC

**Comment by jdcox215** [comment] 2021-01-22 19:54
I made a batch file that's perfect to use if you have WinFsp isntalled. First, it stops the WinFsp.Launcher service that is clashing with EAC. Then it removed an entry for WinFsp.Np in the registry editor. It then launches EAC which is now functional, until you close it. then it restores the files in the registry and restarts the service. It's a perfect thing to use right before you need to use EAC! 
[EAC_Fix.zip](https://github.com/billziss-gh/winfsp/files/5858260/EAC_Fix.zip)

**Comment by nixix** [comment] 2021-03-27 12:46
This issue also affects an old proprietary program we use, which AFAIK doesn't do anything fancy with the file open dialogs. It was compiled with (old) Borland C++ tools and uses the [OWL](https://en.wikipedia.org/wiki/Object_Windows_Library). I have most of the source code but no project files and no build environment, so information is limited. But the issue is not just with EAC.

**Comment by nixix** [comment] 2021-03-28 18:03
FWIW, the above mentioned program doesn't care what the registry is when starting, but crashes when opening a file selector dialog if WinFsp.Np's ProviderPath doesn't point to a 32-bit dll at that exact time.

Changing HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WinFsp.Np\NetworkProvider\ProviderPath to REG_EXPAND_SZ and C:\Program Files (x86)\WinFsp\bin\winfsp-%PROCESSOR_ARCHITECTURE%.dll and renaming winfsp-x64.dll as winfsp-amd64.dll seems to let other programs work fully and this one not crash.

But I guess winfsp-x86.dll isn't really doing its job (or even supposed to, in a 64-bit system) because browsing WinFSP-accessed locations or mapped drives doesn't work with the 32-bit program even though it can use those files by name. Haven't tested on a 32-bit system.

**Comment by billziss-gh** [comment] 2021-03-29 16:50
> It was compiled with (old) Borland C++ tools and uses the OWL.

Wow, you really took me back with this OWL comment :)

I seem to recall that the OWL source was available (or perhaps that was only the Delphi VCL?). If you still have it perhaps we can see how it uses the Windows common dialogs.

> Changing HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WinFsp.Np\NetworkProvider\ProviderPath to REG_EXPAND_SZ and C:\Program Files (x86)\WinFsp\bin\winfsp-%PROCESSOR_ARCHITECTURE%.dll and copying winfsp-x64.dll to winfsp-amd64.dll seems to let other programs work fully and this one not crash.

Yes, using the `PROCESSOR_ARCHITECTURE` environment variable was one of the solutions I considered for this problem. 

> But I guess winfsp-x86.dll isn't really doing its job (or even supposed to, in a 64-bit system) because browsing WinFSP-accessed locations or mapped drives doesn't work with the 32-bit program even though it can use those files by name. Haven't tested on a 32-bit system.

Portions of the `winfsp-x86.dll` are usable on a 64-bit system: for example, 32-bit file systems that run on a 64-bit system. However the Network Provider portion of the 32-bit DLL is only active (and tested) on a 32-bit system.

**Comment by nixix** [comment] 2021-03-30 02:28
Well, I did steal the PROCESSOR_ARCHITECTURE trick from you upthread...

> I seem to recall that the OWL source was available (or perhaps that was only the Delphi VCL?). If you still have it perhaps we can see how it uses the Windows common dialogs.

I can't determine an exact version but the compiler+libraries seem to be from 1994. OWL's Docmanag.cpp (apparently slightly modified) happens to be compiled as part of the program. That means I do have most of the relevant code to look at. The most relevant snippet attached: [docmanag-snippet.cpp.txt](https://github.com/billziss-gh/winfsp/files/6225710/docmanag-snippet.cpp.txt)

The crash happens in its call to [GetOpenFileName](https://docs.microsoft.com/en-us/windows/win32/api/commdlg/ns-commdlg-openfilenamea) with `lStructSize = OPENFILENAME_SIZE_VERSION_400` (the code says `sizeof(OPENFILENAME)` but that's what that was), `Flags = OFN_ENABLEHOOK` (only) and lpfnHook pointing to a mostly dummy function that does some processing but always returns 0. According to [docs](https://docs.microsoft.com/en-us/windows/win32/api/commdlg/ns-commdlg-openfilenamea#ofn_explorer) this prompts GetOpenFileName to use the most basic dialog version instead of the otherwise default "explorer style". I tried patching the exe to use `Flags = OFN_ENABLEHOOK | OFN_EXPLORER` and this delays the crash until I open the "Look in" dropdown or enter a WinFSP-mapped drive letter (in "File name" and press enter/"open"). However, `Flags = OFN_EXPLORER` or `Flags = 0` do again crash immediately (but also work fine when winfsp-x64.dll isn't referenced) so even the hook function is inconsequential.

By the way, a correction to what I said earlier: the registry item doesn't have to point to winfsp-x86.dll, a non-existing filename is fine as well to protect from the crash.

The oldest OWL I can find the full sources to, is quite a lot newer [5.4-ish](http://cc.embarcadero.com/partners/bcb5/exclusive/object_windows_library/index.html) from 1998 (linked from OWL in Wikipedia). It looks like it does basically the same thing in OWLFiles/Owl/opensave.cpp and docmanag.cpp but overall the code is already quite a bit different.

I don't know why more people aren't running into this. Maybe Windows NT era programs somehow aren't in vogue anymore? But apparently GetOpenFileName as a whole was phased out only as late as with Vista. Perhaps the compatibility modes triggered by the old lStructSize matter?

**Comment by billziss-gh** [comment] 2021-03-30 05:24
> The crash happens in its call to GetOpenFileName...

Great information. Thank you.

> I don't know why more people aren't running into this. Maybe Windows NT era programs somehow aren't in vogue anymore? But apparently GetOpenFileName as a whole was phased out only as late as with Vista. Perhaps the compatibility modes triggered by the old lStructSize matter?

This might have something to do with some weird compatibility mode that Windows puts itself into to support really old apps. So it may or may not be possible to repro with a modern 32-bit app.

----

Thinking about next steps:

The `PROCESSOR_ARCHITECTURE` fix seems to be the most promising and requires the least amount of structural changes. But it is brittle because it requires the existence of an environment variable that may not exist or may not be assigned correctly. So I would not want to change the WinFsp installation to rely on `PROCESSOR_ARCHITECTURE`.

So perhaps a compromise is to create a batch file that fixes this problem only for people who experience it. The batch file would do the following:

- Create a junction called `amd64` inside the `WinFsp\bin` directory that points back to the directory.

    ```batch
    mklink /j amd64 .
    ```

    - My first thought was to create a symlink `winfsp-amd64.dll` that points to `winfsp-x64.dll`. Unfortunately creating Windows symlinks is not guaranteed to work on all Windows systems (even in elevated accounts).

- Update the `ProviderPath` in `HKLM\SYSTEM\CurrentControlSet\Services\WinFsp.Np\NetworkProvider` to point to `...\WinFsp\bin\%PROCESSOR_ARCHITECTURE%\winfsp-x64.dll`.

    - This means that 64-bit processes should be able to find the Network Provider in `...\WinFsp\bin\amd64\winfsp-x64.dll`, but 32-bit processes should be unable to find any Network Provider in `...\WinFsp\bin\x86\winfsp-x64.dll`.

**Comment by elmirador** [comment] 2021-04-06 06:12
Just want to thank @nixix for the hard work and @billziss-gh for the solution!
I use both sshfs and EAC a lot and this just saves the day :D

It seems like EAC REALLY needs to overhaul its code for the GUI portion, considering it's still active.

**Comment by billziss-gh** [comment] 2021-04-08 22:05
I added a batch file [tools\fix162.bat](https://github.com/billziss-gh/winfsp/blob/master/tools/fix162.bat) that can be used to easily work around this problem. See commit a7cfabeff8be83131cd435e0221012fba023bc71.

The batch file requires Administrator privileges in order to run. Run with `fix162.bat` to enable the fix. Run with `fix162.bat -u` to disable it.

**Comment by thatsmydoing** [comment] 2021-05-01 08:15
I wanted to report that I also see this issue with foobar2000 v1.6.5 which is also 32-bit only. The UI hangs when clicking the view menu or right clicking on a track.

**Comment by d4k0** [comment] 2022-12-25 23:12
@billziss-gh, thanks for this workaround! I had this problem yesterday and it almost drove me crazy.

In my case, the "culprit" seems to have been Cryptomator, which I've been using for the last few months. It installs and uses WinFSP. Someone on the Cryptomator forum had the problem as well:

https://community.cryptomator.org/t/exact-audio-copy-eac-crashes/9953

**Comment by elendil7** [comment] 2023-07-24 20:51
> I made a batch file that's perfect to use if you have WinFsp isntalled. First, it stops the WinFsp.Launcher service that is clashing with EAC. Then it removed an entry for WinFsp.Np in the registry editor. It then launches EAC which is now functional, until you close it. then it restores the files in the registry and restarts the service. It's a perfect thing to use right before you need to use EAC! [EAC_Fix.zip](https://github.com/billziss-gh/winfsp/files/5858260/EAC_Fix.zip)

Very useful script my dear fellow. Your work has not gone unnoticed 😃

**Comment by s-h-a-d-o-w** [comment] 2025-02-21 16:36
Note that EAC also has an option to always write to a specific directory, which means that it won't open a file chooser when ripping something.

EAC => EAC Options => Directories => Use this directory (Paste a path rather than browsing for one.)

Works best if you also use a naming scheme that creates subdirectories under "Filename".

**Comment by KaNo2025** [comment] 2025-05-06 18:06
Hello,

fresh EAC user here - and I've stumbled across the same pitfalls.

However, I've tried to address this issue with a more (or less) dynamic batch file approach, sharing it to hopefully be useful for one or the other. I also hope my coding and remarks within the batch file are more or less self-explanatory.

[eac_bypass_winfsp_x64_architecture.zip](https://github.com/user-attachments/files/20068345/eac_bypass_winfsp_x64_architecture.zip)
