### ISSUE TITLE
Korean backslash causes problems on Windows 10

### ISSUE THREAD

**Issue by shad00m** [billziss-gh/winfsp#302] opened 2019-11-24 19:35 UTC
Client: Windows 10 (Korean Locale)
Server: Debian (enUS)

I was not able to mount a folder until I changed to a locale on the Windows machine that has a usual Backslash \.
On Korean Windows-PCs the Backslash (\) is a ₩. I am assuming that this causes problems.

Example 1: I try to connect to \\sshfs\name@server.com on a Windows 10 with normal backslash
It'll auto fill the "name" in the Authentication Box that pop ups and after typing the password connecting works fine.

Example 2: I try to connect to ₩₩sshfs₩name@server.com
Username gets filled as "UNSPECIFIED" and after manually filling it in the connection fails

I know Japanese also has this behavior, and they're presented as ¥. I haven't tested if it fails there as well.

**Comment by billziss-gh** [comment] 2020-04-15 04:03
I have transferred this issue to WinFsp, because this is likely a WinFsp problem and because the chances of me acting on the problem are greatly increased by having it here.

**Comment by billziss-gh** [comment] 2020-04-15 04:10
@ds6 thanks for the good pointers. Reading on them now.

**Comment by roa-nyx** [comment] 2020-04-15 15:51
Thanks for directing me here from #178.

For me it's the Japanese locale, but it definitely seems like it would be the exact same issue.

@billziss-gh it's easy enough to test I would think, if you have a W10 machine, changing the locale takes a few minutes. I believe it requires a restart though, which is annoying. Please let me know if you can't reproduce the issue, and need some other diagnostic information from me.

**Comment by billziss-gh** [comment] 2020-05-04 22:40
I am unable to reproduce this problem.

See screenshot where I am able to mount my Mac's home folder and list the subdirectory `Movies` while running Windows 10 (1909) under the Japanese locale.

![Screen Shot 2020-05-04 at 3 36 34 PM](https://user-images.githubusercontent.com/15330948/81020344-72d55200-8e1d-11ea-8c0b-e3d9c0be9a27.png)

**Comment by roa-nyx** [comment] 2020-05-04 22:47
I think that's the reverse of the issue I've been having. I'm going to define the machine I'm trying to SSH into as the host, and the machine I'm trying to access it from as the guest.

In my case both the guest and host is in Japanese Locale, however I think it's important that the host is in Japanese Locale (and maybe that it's windows?). I also suspect the guest has to be Windows or more specifically Windows 10.

**Comment by writingdeveloper** [comment] 2021-02-28 06:02
Is there any solution to solve this problem?
I also experience same issue and it seems that it also problem in user name and server directory.

**Comment by billziss-gh** [comment] 2021-02-28 19:37
@writingdeveloper please see my comment above where I was not able to reproduce the problem as I understand it.

If someone posts a full list of easily reproducible tests, I will attempt to reproduce this, understand the problem (if any) and fix it.

**Closed** 2021-11-18 16:40 UTC
