### ISSUE TITLE
FILE_ATTRIBUTE_READONLY on directories results in STATUS_ACCESS_DENIED

### ISSUE THREAD

**Issue by alfaunits** [billziss-gh/winfsp#190] opened 2018-09-20 08:50 UTC
This was tested with different scenarios on W10 x64, but is reproducible in other environments. Vanilla MemFS/PTFS samples.

Scenario:
- Run (original, unmodified) MemFS/PTFS, mounted folder name, folder to expose (PTFS), file sizes, etc. are irrelevant.
- Copy any Admin user's folder (e.g., I suggest Downloads or Sample Pictures, since this is what I tested with) to the drive (TRY to copy, that is)
- Different errors might pop up, but generally, even if the copy progress bar shows it is copying files, nothing is being copied (only the top folder is created, and nothing else, not even Desktop.ini)
- Try copying any file in the newly created Downloads or Sample Pictures folder. It will fail.

The security descriptor is considerably different from the original folder's SD. Even though it should give access to Admins, the copy of files to those new folders fails.

In our sample (made from PTFS), I have removed GetSecurityByName, GetSecurity and SetSecurity, and this particular issue disappears.

**Comment by billziss-gh** [comment] 2018-09-20 16:56
Can you show how you start the file system? Also do you start it from a command prompt, an elevated command prompt or the SYSTEM account (i.e. under the launcher)?

**Comment by alfaunits** [comment] 2018-09-20 17:34
Elevated command prompt.
For MemFS I ran: memfs-x64.exe -m C:\VFS
For PTFS I ran: passthrough-x64.exe -p C:\Temp -m C:\VFS

**Comment by billziss-gh** [comment] 2018-09-20 18:45
Because you are mounting on a directory I suspect that you are experiencing an issue with directory permission inheritance.

Does the problem happen when you mount as a drive?

**Comment by alfaunits** [comment] 2018-09-20 19:02
Our test projects mounts as a drive and has the same issue.

**Comment by alfaunits** [comment] 2018-09-20 20:01
I just tried to run MemFS -m X:
I am not getting X: on W10 (in Explorer or cmd.exe)

On my own W7, C:\vFS mount has the permission issues, X: does not.

Our own project is based on Passthrough sample, so it does expose a folder with permissions, which seem to have the issue. Why the folder permissions are copied incorrectly, then? (in MemFS)

**Comment by billziss-gh** [comment] 2018-09-21 02:53
> I just tried to run MemFS -m X:
> I am not getting X: on W10 (in Explorer or cmd.exe)

If you start the file system from an elevated command prompt it will be created in a different name space and it will not be available via Explorer (which runs non-elevated).

> Our own project is based on Passthrough sample, so it does expose a folder with permissions, which seem to have the issue. Why the folder permissions are copied incorrectly, then? (in MemFS)

I believe (but have not confirmed) that the reason is likely that some directory permissions are passed through inheritance when you mount as a directory.

Can you please run the command `cacls MEMFS-DIR /s` on the MEMFS mount directory and report the output. Try also the same command in a file or directory contained within a MEMFS file system.

When MEMFS is mounted as a directory it creates a new directory with default security descriptor. This was perhaps an oversight as we likely do not want directory permission inheritance from NTFS to propagate through the MEMFS file system.

For your own file system there is an API `FspFileSystemSetMountPointEx`, which allows you to explicitly set the security descriptor on your directory. Please consider using this API instead.

**Comment by alfaunits** [comment] 2018-09-21 08:30
Yes, MemFS is inheriting the C: drive's permissions. But that does not explain why an Admin cannot copy Admin's data to that folder, when he has access. Copying to a folder on C drive with identical permissions is possible.

**Comment by alfaunits** [comment] 2018-09-21 09:53
On W10, I started MemFS from a normal Command Prompt. Explorer cannot copy Saved Pictures.

**Comment by billziss-gh** [comment] 2018-09-21 17:27
@alfaunits I think we are talking about multiple simultaneous scenarios and it makes the conversation somewhat confusing. Let me see if I understand:

- `memfs -m X:` works.
- `memfs -i -m C:\VFS` does not work. (BTW, do you supply the `-i` switch to make the file system case-insensitive when mounting on a directory? See FAQ entry #3.)
- `passthrough -p ... -m X:` works?
- `passthrough -p ... -m C:\VFS` does not work. (PTFS is always case-insensitive so FAQ entry #3 does not apply.)

For MEMFS the only access checks happen when a file/directory is created/opened. These checks happen in user mode in the file system (`FspAccessCheckEx` with the help of the file system's `GetSecurityByName`). This is a well-tested area of WinFsp and I am surprised to hear of problems at this stage of its life cycle.

For PTFS the situation is slightly more complicated. As before access checks happen when a file/directory is created/opened in user mode in the file system. However PTFS has to open real files on the underlying file system (usually NTFS) which **imposes its own access control against the user who runs the file system**. So you may still get "Access Denied" in some cases; it is for this reason that PTFS tries to acquire the BACKUP/RESTORE privileges if it is able to do so.

Some troubleshooting steps I would try:

- Try to completely disable permission inheritance on the mounted directory. As a quick way to test this you could try mounting the file system inside `C:\T\VFS` with `T` having inheritance disabled.
- Run the file systems (especially PTFS which needs BACKUP/RESTORE privileges to work properly) under the SYSTEM account. An easy way to do this from the command prompt is to use [PsExec](https://docs.microsoft.com/en-us/sysinternals/downloads/psexec).
- Make sure you pass the `-i` switch to MEMFS when you mount it on a directory.

**Comment by alfaunits** [comment] 2018-09-21 17:53
On Windows 10 nothing works. Even MemFS mounted as a drive, from a nonelevated Cmd.

**Comment by alfaunits** [comment] 2018-10-20 00:31
I cannot dedicate more time to this, but from what I have gathered to date, the issue seems to be FspAccessCheck, where it tests if a directory is read-only and prevents creating files in it. The test should not do that, as it is not how Windows file systems behave. Specifically, in the DLL/Security.c, line 342+:
  if (Request->Req.Create.UserMode)
    {
        if (0 != (FileAttributes & FILE_ATTRIBUTE_READONLY))
        {
            if (DesiredAccess &
                (FILE_WRITE_DATA | FILE_APPEND_DATA | FILE_ADD_SUBDIRECTORY | FILE_DELETE_CHILD))
            {
                Result = STATUS_ACCESS_DENIED;
                goto exit;
            }
The check should not occur for directories on Windows.

Cheers.

**Comment by billziss-gh** [comment] 2018-10-20 04:05
@alfaunits I believe that you have identified a real problem in `FspAccessCheckEx` with directories and `FILE_ATTRIBUTE_READONLY`.

NTFS session:
```
C:\Users\billziss>mkdir t

C:\Users\billziss>attrib +r t

C:\Users\billziss>cd t

C:\Users\billziss\t>echo hello >world

C:\Users\billziss\t>type world
hello

C:\Users\billziss\t>del world

C:\Users\billziss\t>cd ..

C:\Users\billziss>rmdir t
Access is denied.

C:\Users\billziss>attrib -r t

C:\Users\billziss>rmdir t

```

MEMFS session:
```
Y:\>mkdir t

Y:\>attrib +r t

Y:\>cd t

Y:\t>echo hello >world
Access is denied.

Y:\t>type world
The system cannot find the file specified.

Y:\t>cd ..

Y:\>rmdir t
Access is denied.

Y:\>attrib -r t

Y:\>rmdir t

```

So `FILE_ATTRIBUTE_READ_ONLY` disallows directory deletion, but allows the creation and deletion of files and directories.

Thank you again for correctly identifying the problem and a resolution.

**Comment by alfaunits** [comment] 2018-10-20 11:42
No problem.

**Comment by billziss-gh** [comment] 2018-10-20 17:53
I believe the commits referenced above fix the reported issue and pass all tests. I will also add a test case to make sure that we do not have a regression in the future.

**Comment by billziss-gh** [comment] 2018-11-06 18:02
I have now added a test for this problem to ensure that we do not have regressions in the future. [All tests pass.](https://ci.appveyor.com/project/billziss-gh/winfsp/builds/20070585)

I will merge these changes into the `release/1.4` and `master` branches and close this. Thank you again for finding the problem and pinpointing the resolution.

**Comment by alfaunits** [comment] 2018-11-06 18:04
Kein Problem :)

**Closed** 2018-11-06 18:13 UTC
Labels: bug
