### ISSUE TITLE
FUSE interface: At a certain point a lower case named folder is handled by FUSE in upper case

### ISSUE THREAD

**Issue by Bob590** [billziss-gh/winfsp#324] opened 2020-10-09 21:25 UTC
## Bug Report

I'm experimenting a little with the FUSE PassThrough example where I have added some log to see in details what happens inside it.
While doing a rename operation from an internal folder I experience a strange behaviour.
I have mounted the disk to see c:/Temp/ in a drive letter (O:).
When I do a rename O:\vSE0\a\test.txt TO O:\vSE0\b\new.txt WHERE the folder 'b' not yet exists.
I see in the log that at a certain point the folder 'b' become 'B' in upper case.
The operation succeed... so it isn't a problem for the functionality... but I'm asking myself from where it come the 'B'!!

Here is the log:
ret_code represent the value returned to the FUSE interface

[Fri 09/10/2020, 23:01:10.631] getattr c:/Temp/vSE0/b/new.txt
[Fri 09/10/2020, 23:01:10.639] getattr c:/Temp/vSE0/b/new.txt size=0, ret_code=-1
[Fri 09/10/2020, 23:01:10.648] getattr c:/Temp/VSE0/B/new.txt
[Fri 09/10/2020, 23:01:10.656] getattr c:/Temp/VSE0/B/new.txt size=0, ret_code=-1
[Fri 09/10/2020, 23:01:10.664] rename c:/Temp/vSE0/a/test.txt to c:/Temp/VSE0/B/new.txt
[Fri 09/10/2020, 23:01:10.677] releasedir /vSE0/b
[Fri 09/10/2020, 23:01:10.689] release /vSE0/a/test.txt
[Fri 09/10/2020, 23:01:10.695] getattr c:/Temp/vSE0/b/new.txt
[Fri 09/10/2020, 23:01:10.703] getattr c:/Temp/vSE0/b/new.txt size=31, ret_code=0
[Fri 09/10/2020, 23:01:10.710] getattr c:/Temp/vSE0/b/new.txt
[Fri 09/10/2020, 23:01:10.718] getattr c:/Temp/vSE0/b/new.txt size=31, ret_code=0

Maybe this is an internal bug... I'm asking a fix in this case or explain me what I'm doing wrong.

For Windows this isn't a problem because the file system doesn't make any difference between lower case and upper case during file operations.
But in case you want to preserve case the 'B' upper case can lead to problems.
Consider the case where you want for example create a new FUSE driver that handle a remote file system where case is a matter. In this case this behaviour IS A PROBLEM!

### How to Reproduce

Execute the passthrough example and place a brekpoint in the rename function.
Then on the mounted drive letter (run a command line - cmd) do a rename O:\vSE0\a\test.txt -> O:\vSE0\b\new.txt WHERE the folder 'b' not yet exists. You need to first create a folder in the root (vSE0 in my case) then create the folder 'a' and then copy inside the file test.txt (in my case just 31 bytes). The folder 'b' should not exists.

### Behaviors

I expect that all names are managed AS IS but instead at a certain point I see a getattr with 'B' and finally the rename is called with the 'B' in upper case instead of using 'b' like asked in the issued command .

### Environment

- OS version and build: _e.g. Windows 10, Build 1909 - 18363.1110
- WinFsp version and build: 2020.1

**Comment by Bob590** [comment] 2020-10-13 15:17
You can close this bug report.
I have discovered that the problem is excited by the Windows File System and thus winfsp is not responsible for this problem.
Most probably this is something that comes from MS-DOS compatibility...

**Comment by billziss-gh** [comment] 2020-10-13 21:41
@Bob590 sorry for the late response.

If you advertise your file system as case-sensitive Windows should not send you mixed case file names. Is your file system case-sensitive or case-insensitive? (FUSE does not normally support case-insensitive file systems, but WinFsp and OSXFUSE support them via the capability `FUSE_CAP_CASE_INSENSITIVE`.)

**Comment by Bob590** [comment] 2020-10-15 07:13
NP! We are all busy men.

Yes I wish to develop a case sensitive file system.
The problem is that I haven't specified FUSE_CAP_CASE_INSENSITIVE! :-(

**Comment by billziss-gh** [comment] 2020-10-15 19:43
> The problem is that I haven't specified FUSE_CAP_CASE_INSENSITIVE! :-(

Then Windows should not try to rename files using the wrong case.

However numerous Windows applications always assume that the file system is case-insensitive and may in fact use mixed case file names in the API's. Do you know which application triggered the rename?

**Comment by Bob590** [comment] 2020-10-15 20:02
I have used Total Commander shell and I also write a small Qt program that does the same test.
Both excite the problem.

**Comment by Bob590** [comment] 2020-10-16 12:52
BTW: my registry key obcaseinsensitive at
Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel
is set to ZERO

Thus the Kernel should handle all case sensitive.

**Comment by billziss-gh** [comment] 2020-10-16 18:48
> ... I also write a small Qt program that does the same test.

In your own QT application you have control of how the rename is done. Are you saying that you are issuing the QT-equivalent of `rename(old, "/b/new.txt")` and it comes into your file system as `\B\new.txt`?

You might also want to consider testing with the Windows API [MoveFileExW](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-movefileexw).

> Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\kernel
is set to ZERO

This is certainly interesting. If you find that `MoveFileExW` also causes the problem I will try to repro with this setting on when I get the time.

**Comment by Bob590** [comment] 2020-10-16 19:50
You can do the same test on the cmd command line.
The log will show you that at first all is lower case... but as the destination file doesn't yet exist... before the FUSE rename take place I receive one getattr with the lower case folder name and then another one with the upper case.
NOTE: only the folder name is upper case, the file name remain correct.
After these two getattr finally I receive the FUSE rename call but, and here is the problem, with the destination folder in upper case.
I find this really ODD.

Let me know if you will be able to RE-CREATE the problem... I'm curios to know if this is only my problem or not.
Thank you for yout time!

**Comment by billziss-gh** [comment] 2020-10-16 21:36
The behavior you are describing is weird and I would certainly like to get to the bottom of it. I do not have time to try and repro this currently, but I intend to try in the future.

I will not be surprised if this ends up somehow related to that `obcaseinsensitive` registry setting...

**Comment by Bob590** [comment] 2020-10-16 21:42
I agree. This is making me crazy... as I don't know from where it comes...
I'll try to play with the registry obcaseinsensitive set to 1 to see if this will make any difference.
I'll let you know...

**Comment by Bob590** [comment] 2020-10-19 10:02
To simplify your life here is the Qt code I'm using to test.

m_Path is set to the drive letter of the passthrough driver. For example "O:\"

    QDir dir(m_Path);
    QString path;
    QDir newdir;
    QFile file;
    int i;

    path = dir.path();
    newdir.setPath(path);
    // mkdir dir2
    if( !newdir.mkdir("dir2") )
        AppendError("creating dir2");
    // mkdir dir3
    if( !newdir.mkdir("dir3") )
        AppendError("creating dir3");
    // open dir2/file0 for W
    path = newdir.path() + "/dir2/file0";
    file.setFileName(path);
    if( !file.open(QFile::WriteOnly) )
        AppendError("Opening dir2/file0");
    // write to file0 100MB
    for( i = 1; i <= 100000; ++i ) {
        qint64 n = file.write( WBuffer1, 1024 );
        if(n != 1024) {
            AppendError("writing dir2/file0");
            break;
        }
    }
    // close file0
    file.close();

    if(!newdir.exists("dir2/file0"))
        AppendError("dir2/file0 was not created");

    // rename dir2/file0 to dir3/file1
    if( !newdir.rename("dir2/file0", "dir3/file1") )
        AppendError("Renaming dir2/file0 to dir3/file1");

    if(!newdir.exists("dir3/file1"))
        AppendError("dir3/file1 NOT present after rename");

the code proceed with deleting the folders created... I omit it.

BEFORE the rename takes place you will see in the log:

	getattr /DIR3/file1

and then the rename will be logged as:

	rename /dir2/file0 TO /DIR3/file1


Teh mentioned registry is DON'T CARE.
Today I have tested it set to ZERO or set to ONE.
No differences.

The good point is that the final result is OK. I mean that I don't find any errors in the Qt code... most probably due to the fact that the NTFS file system don't care about case and thus DIR3 is the same that dir3.

BUT if you develop a file system that is case sensitive this will no more be TRUE! :-(

**Comment by Bob590** [comment] 2020-10-19 13:18
Another example withouit to write ANY code you can simply run the PassThrough disk that map C:\Temp to a drive letter. Then open File Explorer and create a folder DirX. enter this folder and create a new folder. Ar this point assign the name xxx to this folder.
Here is the log you get:

getattr c:/Temp/DirX/dir1
getattr c:/Temp/DirX/dir1 size=0, errno=0
getattr c:/Temp/DirX/dir1
getattr c:/Temp/DirX/dir1 size=0, errno=0
opendir c:/Temp/DirX/dir1
getattr c:/Temp/DirX
getattr c:/Temp/DirX size=0, errno=0
getattr c:/Temp/DirX
getattr c:/Temp/DirX size=0, errno=0
opendir c:/Temp/DirX
getattr c:/Temp/DirX/xxx
getattr c:/Temp/DirX/xxx size=0, errno=2
getattr c:/Temp/DirX
getattr c:/Temp/DirX size=0, errno=2
opendir c:/Temp/DirX
releasedir /DirX
getattr c:/Temp/DIRX/xxx
getattr c:/Temp/DIRX/xxx size=0, errno=2
c:/Temp/DirX/dir1 to c:/Temp/DIRX/xxx

As you see the DirX become DIRX all upper case!
:-(

**Comment by billziss-gh** [comment] 2020-12-23 00:09
@Bob590 I am looking at this now with the intent to have any necessary fixes available for the next beta (WinFsp 2021 Beta2).

However the behavior I am seeing looks like expected behavior. I tried with the file systems mentioned below (logs were obtained with the `-d` switch):

- `passthrough-fuse`: This is a case-insensitive file system and Windows indeed sends mixed case file names in `Rename`. However this is ok since the file system advertises itself as case-insensitive (using `FSP_FUSE_CAP_CASE_INSENSITIVE` in its `init`).

    ```
    passthrough-fuse-x6[TID=3ffc]: FFFF8A89B1545850: >>SetInformation [Rename] "\DIRX\DIR1", 0000000000000000:000002A1C6C6D1E0, NewFileName="\DIRX\mydir", AccessToken=0000000000000000[PID=0]
    passthrough-fuse-x6[TID=3ffc]: FFFF8A89B1545850: <<SetInformation IoStatus=0[0] FileInfo={FileAttributes=0, ReparseTag=0, AllocationSize=0:0, FileSize=0:0, CreationTime=0, LastAccessTime=0, LastWriteTime=0, ChangeTime=0, IndexNumber=0:0}
    ```

- `memfs-fuse`: This is a case-sensitive file system and I did not observe Windows sending mixed case file names.

    ```
    memfs-fuse3-x64[TID=47bc]: FFFF8A8991E17010: >>SetInformation [Rename] "\DirX\dir1", 0000000000000000:0000012FE0F46DE0, NewFileName="\DirX\mydir", AccessToken=0000000000000000[PID=0]
    memfs-fuse3-x64[TID=47bc]: FFFF8A8991E17010: <<SetInformation IoStatus=0[0] FileInfo={FileAttributes=0, ReparseTag=0, AllocationSize=0:0, FileSize=0:0, CreationTime=0, LastAccessTime=0, LastWriteTime=0, ChangeTime=0, IndexNumber=0:0}
    ```

The scenario I tried is the one you mentioned earlier:

- Using Windows Explorer:
    - Create folder `DirX`.
    - Create folder `dir1`.
    - Rename folder `dir1` to `mydir`.

**Comment by billziss-gh** [comment] 2021-01-07 17:39
I am closing this as I believe that this behavior obeys correct file system semantics. Please reopen if you disagree or have additional feedback.

**Closed by billziss-gh** 2021-01-07 17:39 UTC
