### ISSUE TITLE
not install on windows 1909

### ISSUE THREAD

**Issue by zappbrannigan34** [billziss-gh/winfsp#303] opened 2020-05-03 17:13 UTC
## Bug Report

![Снимок](https://user-images.githubusercontent.com/25005152/80920752-85e31600-8d7a-11ea-990a-8594b7e1bb53.PNG)
![Снимок2](https://user-images.githubusercontent.com/25005152/80920761-8bd8f700-8d7a-11ea-95cd-8d0e0243e215.PNG)

### How to Reproduce

clear installed windows and try install winfsp

### Behaviors

install succesful
### Environment

windows 1909 64
- WinFsp version winfsp-1.6.20027 and above

**Comment by zappbrannigan34** [comment] 2020-05-03 17:16
other pc same windows version

PS C:\Users\kuzne> choco install winfsp --pre
Chocolatey v0.10.15
Installing the following packages:
winfsp
By installing you accept licenses for the packages.
Progress: Downloading winfsp 1.7.20123-pre... 100%

winfsp v1.7.20123-pre [Approved]
winfsp package files install completed. Performing other installation steps.
The package winfsp wants to run 'chocolateyInstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider:
choco feature enable -n allowGlobalConfirmation
Do you want to run the script?([Y]es/[A]ll - yes to all/[N]o/[P]rint): a

WARNING: No registry key found based on  'WinFsp*'
Installing winfsp...
WARNING: Generic MSI Error. This is a local environment error, not an issue with a package or the MSI itself - it could mean a pending reboot is necessary prior to install or something else (like the same version is already installed). Please see MSI log if available. If not, try again adding '--install-arguments="'/l*v c:\winfsp_msi_install.log'"'. Then search the MSI Log for "Return Value 3" and look above that for the error.
ERROR: Running ["C:\Windows\System32\msiexec.exe" /i "C:\ProgramData\chocolatey\lib\winfsp\tools\winfsp-1.7.20123.msi" /qn /norestart INSTALLLEVEL=1000 ] was not successful. Exit code was '1603'. Exit code indicates the following: Generic MSI Error. This is a local environment error, not an issue with a package or the MSI itself - it could mean a pending reboot is necessary prior to install or something else (like the same version is already installed). Please see MSI log if available. If not, try again adding '--install-arguments="'/l*v c:\winfsp_msi_install.log'"'. Then search the MSI Log for "Return Value 3" and look above that for the error..
The install of winfsp was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\winfsp\tools\chocolateyInstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - winfsp (exited 1603) - Error while running 'C:\ProgramData\chocolatey\lib\winfsp\tools\chocolateyInstall.ps1'.
 See log for details.

**Comment by billziss-gh** [comment] 2020-05-04 20:36
@zappbrannigan34 does this happen with versions other than the latest beta 2020.1 B2?

**Comment by billziss-gh** [comment] 2020-05-04 21:37
I cannot reproduce this.

Here is a screenshot of a new VM running Win10 1909 with WinFsp 2020.1 B2 installed.

![Screen Shot 2020-05-04 at 2 35 46 PM](https://user-images.githubusercontent.com/15330948/81016147-c3947d00-8e14-11ea-82f2-d6d5cbd7d102.png)

**Comment by billziss-gh** [comment] 2020-05-05 21:58
Closing this. Please reopen if you find that the problem persists.

**Closed by billziss-gh** 2020-05-05 21:58 UTC
