### ISSUE TITLE
error: invalid preprocessing directive #memset for cygfuse (fuse3) using cygport

### ISSUE THREAD

**Issue by sdaau** [billziss-gh/winfsp#294] opened 2020-03-21 20:30 UTC
## Bug Report

I tried to build cygfuse for fuse3 from source ; however, it fails to build with `error: invalid preprocessing directive #memset`

### How to Reproduce

Detailed information on how to reproduce the problem:

```
$ git clone https://github.com/billziss-gh/winfsp.git winfsp_git
$ cd winfsp_git/opt/cygfuse/fuse3/
$ cygport fuse3.cygport all # without previous download:
>>> Preparing fuse3-3.2-2.x86_64
*** ERROR: Cannot find source package master.tar.gz
$ cygport fuse3.cygport download # got master.tar.gz.tmp
$ cygport fuse3.cygport all
>>> Preparing fuse3-3.2-2.x86_64
>>> Unpacking source master.tar.gz
>>> Preparing working source directory
>>> Compiling fuse3-3.2-2.x86_64
gcc  \
        -shared -o build/x86_64/cygfuse-3.2.dll \
        -Wl,--out-implib=build/x86_64/libfuse-3.2.dll.a \
        -I../../../inc/fuse3 \
        cygfuse.c
In file included from ../../../inc/fuse3/winfsp_fuse.h:26,
                 from ../../../inc/fuse3/fuse_common.h:30,
                 from cygfuse.c:84:
../../../inc/fuse3/../fuse/winfsp_fuse.h: In function fsp_fuse_set_signal_handlers:
../../../inc/fuse3/../fuse/winfsp_fuse.h:365:7: error: invalid preprocessing directive #memset
  365 |     # memset instead of ={0} to avoid a GCC -Wmissing-field-initializers warning
      |       ^~~~~~
make: *** [Makefile:12: build/x86_64/cygfuse-3.2.dll] Error 1
```

### Behaviors

Information on the expected and actual behaviors: I'd expect `cygport fuse3.cygport all` to build.

### Environment

- OS version and build: Windows 10, Cygwin `setup-x86_64.exe` v2.903
- WinFsp version and build: 
```
$ git log -1
commit ad68b36de77abceeb5a31fb857ce51e52de6fd9e (HEAD -> master, origin/master, origin/HEAD)
Author: Bill Zissimopoulos <billziss@navimatics.com>
Date:   Tue Mar 10 20:19:05 2020 +0200

    README: internal link to cap.gif
```

**Comment by billziss-gh** [comment] 2020-03-21 22:49
Wow! I must have been asleep at the wheel when this got through.

Thanks for the report. Commit 4b5b56230715920d2f128e96a37e77cbc135e16d should fix this. Confirmed the fix with `make dist` in the `opt/cygfuse` directory. Please reconfirm.

I am leaving this issue open to investigate if I can do regular Appveyor builds for cygfuse to avoid such problems in the future.

**Comment by billziss-gh** [comment] 2020-03-21 23:25
Commit b7553925fb76c2d6e1b39c6d1dba0b5f92db954e also adds cygfuse builds on Appveyor that should hopefully catch such problems in the future.

I am closing this @sdaau, but please reconfirm that your problem is fixed if you can.

**Closed by billziss-gh** 2020-03-21 23:25 UTC

**Comment by sdaau** [comment] 2020-03-22 06:25
Many thanks for the prompt response and the solution, @billziss-gh :

> please reconfirm that your problem is fixed if you can

I indeed confirm my problem is fixed! Please find the build log (of `make dist`) attached ...
[cygfuse_build.log](https://github.com/billziss-gh/winfsp/files/4364750/cygfuse_build.log) ; just to confirm, I built commit b755392.

The only thing a bit suspicious to a newbie I can see there is:

    sort: cannot read: /cygdrive/c/src/winfsp_git/opt/cygfuse/build/fuse-2.8-10.x86_64/temp/.dbgsrc.out: No such file or directory

... but I guess it's nothing to worry about, as the relevant files are being built and can be installed in Cygwin setup.exe

Btw, I was wondering where would the `.hint` and `-src.tar.xz` end up (because without them, Cygwin's `mksetupini` will not create correct `setup.ini` entries), and they are here:

```
$ cd winfsp_git/opt/cygfuse

$ find . -name '*.hint'
./build/fuse-2.8-10.x86_64/dist/fuse/fuse-2.8-10.hint
./build/fuse3-3.2-2.x86_64/dist/fuse3/fuse3-3.2-2.hint

$ tree ./build/fuse-2.8-10.x86_64/dist
./build/fuse-2.8-10.x86_64/dist
+-- fuse
    +-- fuse-2.8-10.hint
    +-- fuse-2.8-10.tar.xz
    +-- fuse-2.8-10-src.tar.xz
```
So, after putting these in my custom Cygwin local package directory, and running `mksetupini` (with the relevant options), Cygwin's setup.exe (rather, `setup-x86_64.exe`, v 2.903) can pick them up, and `fuse` and `fuse3` packages can be installed fine!

Just a note: I guess, for this to fully work, one also has to have the winfsp.msi installed (latest via Releases on github is winfsp-1.7.20038.msi, but seems I've had winfsp-1.4.19016.msi installed from before, and the machine I'm testing on is not in a state where I can easily remove the old one, which requires a reboot).

Btw, is there a quick test of these for Cygwin, that can be compiled with a Makefile and gcc? I've seen the tst directory in the source, but it seems all of those require Chocolatey or Visual Studio ...

Thanks again for the quick solution!

**Comment by billziss-gh** [comment] 2020-03-22 19:23
> Many thanks for the prompt response and the solution...

Thank you for the report.

> The only thing a bit suspicious to a newbie I can see there is:
>
> ```
> sort: cannot read: /cygdrive/c/src/winfsp_git/opt/cygfuse/build/fuse-2.8-10.x86_64/temp/.dbgsrc.out: No such file or directory
> ```

This problem happens for me too. I recall investigating it some time ago, but unfortunately cannot recall what the result of the investigation was. I believe it benign though.

> So, after putting these in my custom Cygwin local package directory, and running mksetupini (with the relevant options), Cygwin's setup.exe (rather, setup-x86_64.exe, v 2.903) can pick them up, and fuse and fuse3 packages can be installed fine!

Yes. When I first created the package a few years ago I fully intended to submit to Cygwin as a package to be installed via setup.exe. Unfortunately this never happened due to interference from other projects.

> Btw, is there a quick test of these for Cygwin, that can be compiled with a Makefile and gcc? I've seen the tst directory in the source, but it seems all of those require Chocolatey or Visual Studio ...

Some of the included file systems can be built under Cygwin using `make`. Look at the [memfs-fuse3](https://github.com/billziss-gh/winfsp/tree/master/tst/memfs-fuse3), [passthrough-fuse](https://github.com/billziss-gh/winfsp/tree/master/tst/passthrough-fuse) and [passthrough-fuse3](https://github.com/billziss-gh/winfsp/tree/master/tst/passthrough-fuse3) file systems included with WinFsp.
