### ISSUE TITLE
Possible Bug: use of  FileContext after Close operation

### ISSUE THREAD

**Issue by kochelmonster** [billziss-gh/winfsp#231] opened 2019-05-02 16:51 UTC
## Bug Report

The following debug log shows what happens:
```
python[TID=006c]: FFFF8C8E561502B0: >>Close 0000021FC8C81778
python[TID=1350]: FFFF8C8E5816E400: >>Cleanup 0000021FC8C81778
python[TID=006c]: FFFF8C8E561502B0: <<Close IoStatus=0[0]
```
During the Close operation a second thread calls Cleanup. In my case this leads to
a access violation because Close already freed the file context.

### How to Reproduce

Unfortunately I cannot provide sample code all attempts to reproduce this behavior with
a simple filesystem failed.  Running my test leads to 99% to a crash.

This is the code leading to the crash:

```python
with open(path, "ab") as f:
    f.write(b"appended")
    f.flush()
    logger.info("test_append:written %r", path)
     with open(path, "rb") as fin:
        data = fin.read()
```

### Environment

- OS version and build: Windows 10 1803 (Build: 17134.706)
- WinFsp version and build: 1.4.19049

Here is the full log:

```
python[TID=1350]: FFFF8C8E55EE3310: >>QueryVolumeInformation
python[TID=1350]: FFFF8C8E55EE3310: <<QueryVolumeInformation IoStatus=0[0] VolumeInfo={TotalSize=100000:0, FreeSize=400:0, VolumeLabel="Larch"}
python[TID=1350]: FFFF8C8E56117110: >>Create [UT---C] "\autorun.inf", FILE_OPEN, CreateOptions=200000, FileAttributes=0, Security=NULL, AllocationSize=0:0, AccessToken=00000000000002F4[PID=1290], DesiredAccess=80, GrantedAccess=0, ShareAccess=7
python[TID=1350]: FFFF8C8E56117110: <<Create IoStatus=c0000034[0]
python[TID=1350]: FFFF8C8E56117110: >>Create [UT---C] "\autorun.inf", FILE_OPEN, CreateOptions=60, FileAttributes=0, Security=NULL, AllocationSize=0:0, AccessToken=00000000000002F4[PID=1290], DesiredAccess=120089, GrantedAccess=0, ShareAccess=7
python[TID=1350]: FFFF8C8E56117110: <<Create IoStatus=c0000034[0]
python[TID=1350]: FFFF8C8E561A07C0: >>Create [UT---C] "\autorun.inf", FILE_OPEN, CreateOptions=60, FileAttributes=0, Security=NULL, AllocationSize=0:0, AccessToken=00000000000002F4[PID=1290], DesiredAccess=120089, GrantedAccess=0, ShareAccess=7
python[TID=1350]: FFFF8C8E561A07C0: <<Create IoStatus=c0000034[0]
python[TID=1350]: FFFF8C8E55B8D7D0: >>Create [UT---C] "\", FILE_OPEN, CreateOptions=200000, FileAttributes=0, Security=NULL, AllocationSize=0:0, AccessToken=00000000000002F4[PID=1290], DesiredAccess=80, GrantedAccess=0, ShareAccess=7
python[TID=1350]: FFFF8C8E55B8D7D0: <<Create IoStatus=0[1] UserContext=0000021FC8C812C8, GrantedAccess=80, FileInfo={FileAttributes=10, ReparseTag=0, AllocationSize=0:0, FileSize=0:0, CreationTime=0, LastAccessTime=0, LastWriteTime=0, ChangeTime=0, IndexNumber=0:0}
python[TID=1350]: FFFF8C8E56821EA0: >>QueryInformation 0000021FC8C812C8
python[TID=006c]: FFFF8C8E5ADD8430: >>QueryVolumeInformation
python[TID=1350]: FFFF8C8E56821EA0: <<QueryInformation IoStatus=0[0] FileInfo={FileAttributes=10, ReparseTag=0, AllocationSize=0:0, FileSize=0:0, CreationTime=0, LastAccessTime=0, LastWriteTime=0, ChangeTime=0, IndexNumber=0:0}
python[TID=1350]: FFFF8C8E56151420: >>QueryInformation 0000021FC8C812C8
python[TID=006c]: FFFF8C8E5ADD8430: <<QueryVolumeInformation IoStatus=0[0] VolumeInfo={TotalSize=100000:0, FreeSize=400:0, VolumeLabel="Larch"}
python[TID=1350]: FFFF8C8E56151420: <<QueryInformation IoStatus=0[0] FileInfo={FileAttributes=10, ReparseTag=0, AllocationSize=0:0, FileSize=0:0, CreationTime=0, LastAccessTime=0, LastWriteTime=0, ChangeTime=0, IndexNumber=0:0}
python[TID=1350]: FFFF8C8E55E49010: >>Cleanup 0000021FC8C812C8
python[TID=1350]: FFFF8C8E55E49010: <<Cleanup IoStatus=0[0]
python[TID=1350]: FFFF8C8E56864EA0: >>Close 0000021FC8C812C8
python[TID=006c]: FFFF8C8E5671D010: >>Create [UT---C] "\AutoRun.inf", FILE_OPEN, CreateOptions=200000, FileAttributes=0, Security=NULL, AllocationSize=0:0, AccessToken=00000000000002F4[PID=1290], DesiredAccess=80, GrantedAccess=0, ShareAccess=7
python[TID=1350]: FFFF8C8E56864EA0: <<Close IoStatus=0[0]
python[TID=006c]: FFFF8C8E5671D010: <<Create IoStatus=c0000034[0]
python[TID=006c]: FFFF8C8E5773D3A0: >>Create [UT---C] "\dmk\corn\rape-oil.txt", FILE_OPEN_IF, CreateOptions=60, FileAttributes=0, Security=NULL, AllocationSize=0:0, AccessToken=00000000000003A4[PID=134], DesiredAccess=120196, GrantedAccess=0, ShareAccess=3
python[TID=006c]: FFFF8C8E5773D3A0: <<Create IoStatus=0[1] UserContext=0000021FC8C81778, GrantedAccess=120196, FileInfo={FileAttributes=80, ReparseTag=0, AllocationSize=0:0, FileSize=0:2ed, CreationTime=0, LastAccessTime=0, LastWriteTime=0, ChangeTime=2019-05-02T14:40:03.000Z, IndexNumber=0:0}
python[TID=006c]: FFFF8C8E55F81010: >>QueryInformation 0000021FC8C81778
python[TID=006c]: FFFF8C8E55F81010: <<QueryInformation IoStatus=0[0] FileInfo={FileAttributes=80, ReparseTag=0, AllocationSize=0:0, FileSize=0:2ed, CreationTime=0, LastAccessTime=0, LastWriteTime=0, ChangeTime=2019-05-02T14:40:03.000Z, IndexNumber=0:0}
python[TID=006c]: FFFF8C8E55F81010: >>QueryInformation 0000021FC8C81778
python[TID=006c]: FFFF8C8E55F81010: <<QueryInformation IoStatus=0[0] FileInfo={FileAttributes=80, ReparseTag=0, AllocationSize=0:0, FileSize=0:2ed, CreationTime=0, LastAccessTime=0, LastWriteTime=0, ChangeTime=2019-05-02T14:40:03.000Z, IndexNumber=0:0}
python[TID=006c]: FFFF8C8E55F81010: >>QueryInformation 0000021FC8C81778
python[TID=006c]: FFFF8C8E55F81010: <<QueryInformation IoStatus=0[0] FileInfo={FileAttributes=80, ReparseTag=0, AllocationSize=0:0, FileSize=0:2ed, CreationTime=0, LastAccessTime=0, LastWriteTime=0, ChangeTime=2019-05-02T14:40:03.000Z, IndexNumber=0:0}
python[TID=006c]: FFFF8C8E55F81010: >>QueryVolumeInformation
python[TID=006c]: FFFF8C8E55F81010: <<QueryVolumeInformation IoStatus=0[0] VolumeInfo={TotalSize=100000:0, FreeSize=400:0, VolumeLabel="Larch"}
python[TID=006c]: FFFF8C8E55F81010: >>QueryInformation 0000021FC8C81778
python[TID=006c]: FFFF8C8E55F81010: <<QueryInformation IoStatus=0[0] FileInfo={FileAttributes=80, ReparseTag=0, AllocationSize=0:0, FileSize=0:2ed, CreationTime=0, LastAccessTime=0, LastWriteTime=0, ChangeTime=2019-05-02T14:40:03.000Z, IndexNumber=0:0}
python[TID=006c]: FFFF8C8E55F81010: >>QueryInformation 0000021FC8C81778
python[TID=006c]: FFFF8C8E55F81010: <<QueryInformation IoStatus=0[0] FileInfo={FileAttributes=80, ReparseTag=0, AllocationSize=0:0, FileSize=0:2ed, CreationTime=0, LastAccessTime=0, LastWriteTime=0, ChangeTime=2019-05-02T14:40:03.000Z, IndexNumber=0:0}
python[TID=006c]: FFFF8C8E55F81010: >>QueryInformation 0000021FC8C81778
python[TID=006c]: FFFF8C8E55F81010: <<QueryInformation IoStatus=0[0] FileInfo={FileAttributes=80, ReparseTag=0, AllocationSize=0:0, FileSize=0:2ed, CreationTime=0, LastAccessTime=0, LastWriteTime=0, ChangeTime=2019-05-02T14:40:03.000Z, IndexNumber=0:0}
python[TID=006c]: FFFF8C8E55F81010: >>Write 0000021FC8C81778, Address=0000021FC8CA0000, Offset=0:2ed, Length=8, Key=0
python[TID=006c]: FFFF8C8E55F81010: <<Write IoStatus=0[8] FileInfo={FileAttributes=80, ReparseTag=0, AllocationSize=0:0, FileSize=0:2f5, CreationTime=0, LastAccessTime=0, LastWriteTime=0, ChangeTime=2019-05-02T14:40:03.000Z, IndexNumber=0:0}
python[TID=006c]: FFFF8C8E55F81010: >>Create [UT---C] "\dmk\corn\rape-oil.txt", FILE_OPEN, CreateOptions=60, FileAttributes=0, Security=NULL, AllocationSize=0:0, AccessToken=00000000000003A4[PID=134], DesiredAccess=120089, GrantedAccess=0, ShareAccess=3
python[TID=006c]: FFFF8C8E55F81010: <<Create IoStatus=0[1] UserContext=0000021FC8C81BD8, GrantedAccess=120089, FileInfo={FileAttributes=80, ReparseTag=0, AllocationSize=0:0, FileSize=0:2ed, CreationTime=0, LastAccessTime=0, LastWriteTime=0, ChangeTime=2019-05-02T14:40:03.000Z, IndexNumber=0:0}
python[TID=006c]: FFFF8C8E561502B0: >>QueryInformation 0000021FC8C81778
python[TID=006c]: FFFF8C8E561502B0: <<QueryInformation IoStatus=0[0] FileInfo={FileAttributes=80, ReparseTag=0, AllocationSize=0:0, FileSize=0:2f5, CreationTime=0, LastAccessTime=0, LastWriteTime=0, ChangeTime=2019-05-02T14:40:03.000Z, IndexNumber=0:0}
python[TID=006c]: FFFF8C8E56877670: >>QueryInformation 0000021FC8C81778
python[TID=006c]: FFFF8C8E56877670: <<QueryInformation IoStatus=0[0] FileInfo={FileAttributes=80, ReparseTag=0, AllocationSize=0:0, FileSize=0:2f5, CreationTime=0, LastAccessTime=0, LastWriteTime=0, ChangeTime=2019-05-02T14:40:03.000Z, IndexNumber=0:0}
python[TID=006c]: FFFF8C8E55BB3950: >>QueryInformation 0000021FC8C81778
python[TID=006c]: FFFF8C8E55BB3950: <<QueryInformation IoStatus=0[0] FileInfo={FileAttributes=80, ReparseTag=0, AllocationSize=0:0, FileSize=0:2f5, CreationTime=0, LastAccessTime=0, LastWriteTime=0, ChangeTime=2019-05-02T14:40:03.000Z, IndexNumber=0:0}
python[TID=006c]: FFFF8C8E5604BD10: >>Read 0000021FC8C81778, Address=0000021FC8CA0000, Offset=0:0, Length=4096, Key=0
python[TID=006c]: FFFF8C8E5604BD10: <<Read IoStatus=0[757]
python[TID=006c]: FFFF8C8E561502B0: >>QueryInformation 0000021FC8C81778
python[TID=006c]: FFFF8C8E561502B0: <<QueryInformation IoStatus=0[0] FileInfo={FileAttributes=80, ReparseTag=0, AllocationSize=0:0, FileSize=0:2f5, CreationTime=0, LastAccessTime=0, LastWriteTime=0, ChangeTime=2019-05-02T14:40:03.000Z, IndexNumber=0:0}
python[TID=006c]: FFFF8C8E55F81010: >>QueryVolumeInformation
python[TID=006c]: FFFF8C8E55F81010: <<QueryVolumeInformation IoStatus=0[0] VolumeInfo={TotalSize=100000:0, FreeSize=400:0, VolumeLabel="Larch"}
python[TID=006c]: FFFF8C8E55F81010: >>QueryInformation 0000021FC8C81778
python[TID=006c]: FFFF8C8E55F81010: <<QueryInformation IoStatus=0[0] FileInfo={FileAttributes=80, ReparseTag=0, AllocationSize=0:0, FileSize=0:2f5, CreationTime=0, LastAccessTime=0, LastWriteTime=0, ChangeTime=2019-05-02T14:40:03.000Z, IndexNumber=0:0}
python[TID=006c]: FFFF8C8E55F81010: >>QueryVolumeInformation
python[TID=006c]: FFFF8C8E55F81010: <<QueryVolumeInformation IoStatus=0[0] VolumeInfo={TotalSize=100000:0, FreeSize=400:0, VolumeLabel="Larch"}
python[TID=006c]: FFFF8C8E56877670: >>QueryInformation 0000021FC8C81778
python[TID=006c]: FFFF8C8E56877670: <<QueryInformation IoStatus=0[0] FileInfo={FileAttributes=80, ReparseTag=0, AllocationSize=0:0, FileSize=0:2f5, CreationTime=0, LastAccessTime=0, LastWriteTime=0, ChangeTime=2019-05-02T14:40:03.000Z, IndexNumber=0:0}
python[TID=006c]: FFFF8C8E55B8D7D0: >>Read 0000021FC8C81778, Address=0000021FC8CA0000, Offset=0:0, Length=758, Key=0
python[TID=006c]: FFFF8C8E55B8D7D0: <<Read IoStatus=0[757]
python[TID=006c]: FFFF8C8E55B8D7D0: >>Read 0000021FC8C81778, Address=0000021FC8CA0000, Offset=0:2f5, Length=1, Key=0
python[TID=006c]: FFFF8C8E55B8D7D0: <<Read IoStatus=0[0]
python[TID=006c]: FFFF8C8E55B8D7D0: >>Cleanup 0000021FC8C81778
python[TID=006c]: FFFF8C8E55B8D7D0: <<Cleanup IoStatus=0[0]
python[TID=006c]: FFFF8C8E561502B0: >>Close 0000021FC8C81778
python[TID=1350]: FFFF8C8E5816E400: >>Cleanup 0000021FC8C81778
python[TID=006c]: FFFF8C8E561502B0: <<Close IoStatus=0[0]
```

**Comment by billziss-gh** [comment] 2019-05-02 18:20
Thanks for the report. Is the file system a FUSE file system or does it use FileContext directly?

**Comment by billziss-gh** [comment] 2019-05-02 21:23
Windows file systems maintain both a handle count and a reference count for their open files. When a file is closed (`CloseHandle`) the `Cleanup` handler is called, however there are still outstanding references to the file. Only when the reference count of a file goes to 0 does the OS call the `Close` handler. BTW, this behavior is by Windows and not from WinFsp.

For this reason I find it unlikely that a `Close` arrives before a `Cleanup` **for the same `HANDLE` / `FILE_OBJECT` / "file descriptor"**. I think what you are observing is the same file being opened more than once (i.e. 2 "file descriptors") and one of the file descriptors being closed (`Close`) while the other one is being cleaned up (`Cleanup`).

**Comment by kochelmonster** [comment] 2019-05-03 16:23
I use a bugpatched  [winfspy](https://github.com/Scille/winfspy).

The problem is: the last Cleanup is called with the same FileContext as the Close before.
In the log there are 3 FileContext used:
* 0000021FC8C812C8: "\" is opened, cleaned up and closed correctly
* 0000021FC8C81778: "\dmk\corn\rape-oil.txt" (writeable) is opened, cleaned up and closed
                                    and afterwards is cleaned up again.
* 0000021FC8C81BD8 "\dmk\corn\rape-oil.txt" (readable) is only opened and not used anymore.

Can it be that somehow the FileContexts get mixed up?

**Comment by fsgeek** [comment] 2019-05-03 17:20
There is a situation in which the cleanup completion can arrive after the close completion. It relates to a memory mapped file for a delete pending file. In that case, cleanup purges the memory map, which will cause the reference count to drop to zero, which triggers the close inside the file system’s cleanup handler. 

It is a peculiar case, but one I have seen before. In filters, we suppress it by reference counting the file object in the cleanup path (and dropping the reference in the cleanup completion handler,) but a file system has no way to suppress this behavior.

**Comment by billziss-gh** [comment] 2019-05-03 17:39
I think the problem is that your file system (or winfspy) uses `FileContext` incorrectly.

When opening a file in WinFsp there are two constructs to consider:

- File "node". This is a construct that represents the file and is the same across multiple opens. **Thus if the same file is opened more than once the same "node" should be used.** WinFsp tracks user mode "nodes" in a field called `UserContext`.
- File "descriptor". This is a construct that represents a file that has been opened. **Thus every file open has a unique file "descriptor".** WinFsp tracks user mode "descriptors" in a field called `UserContext2`.

File systems are allowed to use `UserContext` or `UserContext2` or both. The default in WinFsp when you use `FileContext` is to use `UserContext`. This is what your file system appears to be doing.

From your log I see that you have two opens of the same file, but your return different `UserContext` for them. This is illegal:

```
python[TID=006c]: FFFF8C8E5773D3A0: >>Create [UT---C] "\dmk\corn\rape-oil.txt", FILE_OPEN_IF, CreateOptions=60, FileAttributes=0, Security=NULL, AllocationSize=0:0, AccessToken=00000000000003A4[PID=134], DesiredAccess=120196, GrantedAccess=0, ShareAccess=3
python[TID=006c]: FFFF8C8E5773D3A0: <<Create IoStatus=0[1] UserContext=0000021FC8C81778, GrantedAccess=120196, FileInfo={FileAttributes=80, ReparseTag=0, AllocationSize=0:0, FileSize=0:2ed, CreationTime=0, LastAccessTime=0, LastWriteTime=0, ChangeTime=2019-05-02T14:40:03.000Z, IndexNumber=0:0}

...

python[TID=006c]: FFFF8C8E55F81010: >>Create [UT---C] "\dmk\corn\rape-oil.txt", FILE_OPEN, CreateOptions=60, FileAttributes=0, Security=NULL, AllocationSize=0:0, AccessToken=00000000000003A4[PID=134], DesiredAccess=120089, GrantedAccess=0, ShareAccess=3
python[TID=006c]: FFFF8C8E55F81010: <<Create IoStatus=0[1] UserContext=0000021FC8C81BD8, GrantedAccess=120089, FileInfo={FileAttributes=80, ReparseTag=0, AllocationSize=0:0, FileSize=0:2ed, CreationTime=0, LastAccessTime=0, LastWriteTime=0, ChangeTime=2019-05-02T14:40:03.000Z, IndexNumber=0:0}
```

WinFsp will ignore the `UserContext` from the second open and will reuse the `UserContext` from the first open, because it detects that the same file is being opened. The reason is that the file "node" is the same for both opens (the "node" for `\dmk\corn\rape-oil.txt`).

At a later time both file descriptors are being closed and you get `Cleanup` / `Close` for both of them. Unfortunately you cannot differentiate between them because your file system uses `UserContext` instead of `UserContext2`.

```
python[TID=006c]: FFFF8C8E55B8D7D0: >>Cleanup 0000021FC8C81778
python[TID=006c]: FFFF8C8E55B8D7D0: <<Cleanup IoStatus=0[0]
python[TID=006c]: FFFF8C8E561502B0: >>Close 0000021FC8C81778
python[TID=1350]: FFFF8C8E5816E400: >>Cleanup 0000021FC8C81778
python[TID=006c]: FFFF8C8E561502B0: <<Close IoStatus=0[0]
```

If you want to differentiate between opens you must use `UserContext2` and not `UserContext`. I do not know how this is done in winfspy, but in core WinFsp this is done by setting `FSP_FSCTL_VOLUME_PARAMS::UmFileContextIsUserContext2` (or `UmFileContextIsFullContext` to use both UserContext and UserContext2).

**Comment by billziss-gh** [comment] 2019-05-03 17:50
@fsgeek 

> There is a situation in which the cleanup completion can arrive after the close completion. It relates to a memory mapped file for a delete pending file. In that case, cleanup purges the memory map, which will cause the reference count to drop to zero, which triggers the close inside the file system’s cleanup handler.

Interesting situation. Do you know if this still happens on modern Windows? I would have thought that the OS takes an additional reference on the `FILE_OBJECT` when sending `IRP_MJ_CLEANUP` (or other IRP).

**Comment by kochelmonster** [comment] 2019-05-03 21:25
The UmFileContextIsUserContext2 flag is the solution. 
Thank You.

I also found the flag's documentation but only after I searched for it.
Would be nice if you could mention this behavior in the tutorial, to avoid others stumbling over it.

**Comment by billziss-gh** [comment] 2019-05-03 21:45
There is a brief mention here although it is easy to miss admittedly.

https://github.com/billziss-gh/winfsp/wiki/WinFsp-Tutorial#entry-point

> 4. Initialize the file system VolumeParams. We want the file system to post Cleanup requests only when a file is modified (this avoids unnecessary Cleanup requests thus improving performance). We also want to treat the FileContext parameter as a "file descriptor".

I am closing this as the problem seems to have been resolved.

**Closed by billziss-gh** 2019-05-03 21:45 UTC
