### ISSUE TITLE
Passthrough: video files don't play

### ISSUE THREAD

**Issue by stanimirivanovde** [billziss-gh/winfsp#197] opened 2018-10-28 05:47 UTC
Hi @billziss-gh. Thanks for creating WinFSP! It works really well for our purposes. I am observing the same issue as previously reported in  #98 with unplayable video files on my Windows 10 testing VM. I am using jnr-fuse with WinFSP. Based on the answer I think the issue is security related, but I don't see a way to configure the OpGuardStrategy to   FSP_FILE_SYSTEM_OPERATION_GUARD_STRATEGY_COARSE in jnr-fuse. If I copy the video out of the fuse drive and onto my desktop the video plays fine. But while the video is in the fuse drive it loads its thumbnail but refuses to play. Media Player shows this error: 0xc00d36c4.

It would be nice to be able to pass such options as part of the fuse mount options. Similarly to how osxfuse has Mac OS X specific mount options.

**Comment by billziss-gh** [comment] 2018-10-28 09:19
WinFsp-FUSE supports the `-s` option for single threaded operation but I am not certain how to pass it in jnr-fuse.

**Comment by stanimirivanovde** [comment] 2018-10-28 16:40
I see now. I incorrectly assumed that the OpGuardStrategy is a security policy and attributed the issue to it. It appears to be a locking strategy for the file system and thus your recommendation to use -s. 

The -s options is not the cause of the problem as far as I can tell. With and without it the issue still persists. If I copy the video out of the FUSE drive then the video plays fine so it can't be a corrupted read/write implementation. Furthermore hashing the video file inside the FUSE drive and outside of it gives the same hash so the read operations should be identical.

The error code I see from Windows Media Player 0xc00d36c4 is linked to USB and removable drives issues. So its probably something that I am not doing right.

Using VLC instead to play the video works. But VLC is notorious for playing corrupted videos so this might not be a good argument.

**Comment by billziss-gh** [comment] 2018-10-28 17:10
Can you reproduce the problem against Memfs?

**Comment by yogendersolanki91** [comment] 2018-12-21 17:41
@billziss-gh 
It is not reproducing with memFs.

**Comment by FrKaram** [comment] 2019-03-03 12:59
A user reported the same issue with KS2 Drive. Even when synchonised is set to ON, Windows Media Player does not want to read the video file. VLC works well on the same video.
I've monitored each Read() event. The file is correctly loaded in a Byte[], every Read() seems to be successfull but still, WMP is unhappy ...
I've tried locking the Read sequence so that only one Read happen at the same time, it's not better...

Any clue on what I should check ?
BTW, in the .NET wrapper, I do not know if the Read is exclusive or not, right ?

**Comment by billziss-gh** [comment] 2019-11-01 00:58
The passthrough file system was really created for tutorial purposes and is by no means a complete file system. For example:

- It does not support named streams.
- It does not support reparse points.
- It uses file handles for file operations to the underlying file system. This means that all the restrictions that Windows imposes on file handles are present (e.g. access permissions, sharing access checks, etc). For this reason some operations fail that should conceptually succeed.

Unfortunately some of these issues often create "mysterious" failures such as the one above. I do not recommend passthrough for uses other than as a tutorial. While these issues could be fixed, the fixes would make passthrough complicated and no longer suitable for tutorial purposes.

**Comment by FrKaram** [comment] 2019-11-01 09:23
Could it fail for the same reasons with memfs ?

**Comment by billziss-gh** [comment] 2019-11-01 16:42
@FrKaram not sure I understand.

If it also fails with memfs then I would consider it a WinFsp bug and would try to fix it, because memfs is the reference file system for WinFsp. But it was my understanding that this problem does not happen with memfs?

**Comment by FrKaram** [comment] 2019-11-01 17:17
I guess I misread the previous post.
As it is failing to read with KS2 Drive which is based on memfs, I thought the post was also saying it wasn't working with memfs. Then it's only my fault if it's not working then :-(
My bad...

**Comment by johntyner** [comment] 2019-11-01 17:25
So @billziss-gh, can you suggest a way forward here? I'm not sure I follow what exactly the issue is.

I would have thought that the interface to the app and the behavior at that level would be the same regardless of the underlying implementation of the file system. If that's not the case, then what does the file system implementation need to do to enable this to work?

**Comment by billziss-gh** [comment] 2019-11-01 18:46
@johntyner 

> I would have thought that the interface to the app and the behavior at that level would be the same regardless of the underlying implementation of the file system.

Maybe I misunderstand what you are saying, but how can this be true in general? For example, if your file system did not implement `Write` then it would not be able to write files.

As a more obscure example, I believe that if you do not implement `GetVolumeInfo` `notepad.exe` will not work, although simple testing in `cmd.exe` and `explorer.exe` will likely work.

> If that's not the case, then what does the file system implementation need to do to enable this to work?

I am not sure what would have to be modified in the passthrough sample to make this work. To find out we would have to use FileSpy and/or Process Monitor (as you have done) to understand where the problem is. In some rare cases reverse engineering of the app in question is required (e.g. using Ghidra). But I am less inclined to hunt and fix all problems with passthrough because of the reasons stated earlier.

This may sound like a cop-out, but I only consider memfs the reference file system for WinFsp and will strive to fix all problems with it. Passthrough plays a different role, that of a tutorial sample, and as such I am less inclined to fix problems with it.

The only way to make sure that your file system works in as many scenarios as possible is to constantly test it with `winfsp-tests` and Microsoft's `ifstest` and try to pass as many tests as possible. If a test does not pass try to understand why it does not. The WinFsp `run-tests.bat` file is the main WinFsp test driver and can be used to gain some understanding how to use `winfsp-tests` and `ifstest`.

----

Having said all this and after looking at your logs more closely.

Passthrough (and only passthrough) seems to be getting a `FileSystemControl` request with `FSCTL_QUERY_VOLUME_CONTAINER_STATE`.

From `winioctl.h`:

```C
#define FSCTL_QUERY_VOLUME_CONTAINER_STATE       CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 228, METHOD_BUFFERED, FILE_ANY_ACCESS)
```

This particular `FSCTL` is not documented anywhere. Somehow I do not believe that this is the problem.

----

Since so many people have a problem with this I will take a look into it.

**Comment by billziss-gh** [comment] 2019-11-01 18:56
What kind of video files do not play? Can you point me to a specific one so that I can try?

**Comment by johntyner** [comment] 2019-11-01 19:18
> Maybe I misunderstand what you are saying, but how can this be true in general? For example, if your file system did not implement Write then it would not be able to write files.

Of course. I meant more that if the file system implements the correct functions, then the underlying implementation of those functions shouldn't be visible to the application. More concretely, both of the opens in the trace I posted (one with the Sequential Access, No Buffering and the second with the Synchronous I/O, Non-Alert) succeed. Why doesn't the Read come through after the first open? Maybe the answer depends on too many things to be answerable, but without seeing a call fail somewhere, I'm not sure where to look.

> This particular FSCTL is not documented anywhere. Somehow I do not believe that this is the problem.

I agree with you, but what is curious is that it is called at all in one situation and not in the others. I kind of suspect the `<unknown>` operation may be the more likely culprit, but who knows.

> Since so many people have a problem with this I will take a look into it.

That's huge! Thanks Bill. I'm happy to help however I can; I was mostly hoping to get your time to point me in the right direction since you're obviously more familiar with the library than I am.

> What kind of video files do not play? Can you point me to a specific one so that I can try on passthrough?

This is the one I used for my tests in the traces above. I was using Windows Media Player in Windows 10.

https://www.videezy.com/technology/12979-traveling-shot-top-view-of-needle-and-vinyl-disc-spinning-from-right-to-left-in-4k

**Comment by billziss-gh** [comment] 2019-11-01 19:38
@johntyner unfortunately I cannot reproduce.

![Capture](https://user-images.githubusercontent.com/15330948/68051362-7a684280-fca4-11e9-8726-32b1ba590789.PNG)

I suspect a filter issue. What does `fltmc` and `fltmc instances` report?

**Comment by johntyner** [comment] 2019-11-01 19:52
```
C:\Windows\system32>fltmc

Filter Name                     Num Instances    Altitude    Frame
------------------------------  -------------  ------------  -----
PROCMON24                               1       385200         0
WdFilter                                4       328010         0
storqosflt                              0       244000         0
wcifs                                   1       189900         0
CldFlt                                  0       180451         0
FileCrypt                               0       141100         0
luafv                                   1       135000         0
npsvctrig                               1        46000         0
Wof                                     2        40700         0
FileInfo                                4        40500         0

C:\Windows\system32>fltmc instances
Filter                Volume Name                              Altitude        Instance Name       Frame   SprtFtrs  VlStatus
--------------------  -------------------------------------  ------------  ----------------------  -----   --------  --------
FileInfo                                                         40500     FileInfo                  0     00000007
FileInfo              C:                                         40500     FileInfo                  0     00000007
FileInfo              \Device\Mup                                40500     FileInfo                  0     00000007
FileInfo              \Device\Volume{ef4b919f-f764-11e9-9114-88ef811a8f59}      40500     FileInfo                  0     00000007
PROCMON24             \Device\Volume{ef4b919f-f764-11e9-9114-88ef811a8f59}     385200     Process Monitor 24 Instance    0     00000007
WdFilter                                                        328010     WdFilter Instance         0     00000007
WdFilter              C:                                        328010     WdFilter Instance         0     00000007
WdFilter              \Device\Mup                               328010     WdFilter Instance         0     00000007
WdFilter              \Device\Volume{ef4b919f-f764-11e9-9114-88ef811a8f59}     328010     WdFilter Instance         0     00000007
Wof                                                              40700     Wof Instance              0     00000007
Wof                   C:                                         40700     Wof Instance              0     00000007
luafv                 C:                                        135000     luafv                     0     00000007
npsvctrig             \Device\NamedPipe                          46000     npsvctrig                 0     00000000
wcifs                 C:                                        189900     wcifs Instance            0     00000007

C:\Windows\system32>
```

**Comment by FrKaram** [comment] 2019-11-01 20:43
Using ProcessMonitor is a great idea, I just wished I thought about it before.
When reading a video file with Windows Media Player here is what I got
![image](https://user-images.githubusercontent.com/8916606/68055082-2be09580-fcf0-11e9-9f92-08a31da3d80e.png)
Looks like what @johntyner get in his airfs log except that for me i produces a 0xc00d36c4 error

**Comment by billziss-gh** [comment] 2019-11-01 20:45
Your filters are the standard ones. From my dev system:

```
# fltmc

Filter Name                     Num Instances    Altitude    Frame
------------------------------  -------------  ------------  -----
WdFilter                                4       328010         0
storqosflt                              0       244000         0
wcifs                                   1       189900         0
CldFlt                                  0       180451         0
FileCrypt                               0       141100         0
luafv                                   1       135000         0
npsvctrig                               1        46000         0
Wof                                     2        40700         0
FileInfo                                4        40500         0
```

So the difference must lie elsewhere.

- Can you please post the output of `diag.bat` located in `\Program Files (x86)\WinFsp\bin`?
- How exactly do you start passthrough? Can you post full command line so that I can attempt to repro?

**Comment by billziss-gh** [comment] 2019-11-01 20:47
@FrKaram where do you see the `0xc00d36c4` error? I do not see it in the procmon output.

This does not appear to be an NTSTATUS code. Perhaps it is an HRESULT?

**Comment by billziss-gh** [comment] 2019-11-01 20:50
Searching online reveals the error code to be: `MF_MEDIA_ENGINE_ERR_SRC_NOT_SUPPORTED`

**Comment by billziss-gh** [comment] 2019-11-01 20:53
Searching online reveals the error code to be: [`MF_E_UNSUPPORTED_BYTESTREAM_TYPE`](https://www.hresult.info/FACILITY_MEDIASERVER/0xC00D36C4).

**Comment by FrKaram** [comment] 2019-11-01 20:56
The error is displayed by the video player
![image](https://user-images.githubusercontent.com/8916606/68056019-66e3c880-fcf2-11e9-9b26-821fd7a7718f.png)

**Comment by FrKaram** [comment] 2019-11-01 20:57
I cannot figure out what is wrong if I serve the media player with what seems to be the correct excepted byte[]

**Comment by johntyner** [comment] 2019-11-01 20:58
> Can you please post the output of diag.bat located in \Program Files (x86)\WinFsp\bin?
```
C:\Program Files (x86)\WinFsp\bin>diag.bat
WINFSP INSTALLATION DIRECTORY AND LAUNCHER REGISTRATIONS

HKEY_LOCAL_MACHINE\SOFTWARE\WinFsp
    InstallDir    REG_SZ    C:\Program Files (x86)\WinFsp\

HKEY_LOCAL_MACHINE\SOFTWARE\WinFsp\Services

HKEY_LOCAL_MACHINE\SOFTWARE\WinFsp\Services\memfs-dotnet
    Executable    REG_SZ    C:\Program Files (x86)\WinFsp\bin\memfs-dotnet-msil.exe
    CommandLine    REG_SZ    -i -F NTFS -n 65536 -s 67108864 -u %1 -m %2
    Security    REG_SZ    D:P(A;;RPWPLC;;;WD)
    JobControl    REG_DWORD    0x1

HKEY_LOCAL_MACHINE\SOFTWARE\WinFsp\Services\memfs32
    Executable    REG_SZ    C:\Program Files (x86)\WinFsp\bin\memfs-x86.exe
    CommandLine    REG_SZ    -i -F NTFS -n 65536 -s 67108864 -u %1 -m %2
    Security    REG_SZ    D:P(A;;RPWPLC;;;WD)
    JobControl    REG_DWORD    0x1

HKEY_LOCAL_MACHINE\SOFTWARE\WinFsp\Services\memfs64
    Executable    REG_SZ    C:\Program Files (x86)\WinFsp\bin\memfs-x64.exe
    CommandLine    REG_SZ    -i -F NTFS -n 65536 -s 67108864 -u %1 -m %2
    Security    REG_SZ    D:P(A;;RPWPLC;;;WD)
    JobControl    REG_DWORD    0x1


WINFSP DLL REGISTRATIONS

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\NetworkProvider\Order
    ProviderOrder    REG_SZ    WinFsp.Np,RDPNP,LanmanWorkstation,webclient


HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WinFsp.Np\NetworkProvider
    Name    REG_SZ    Windows File System Proxy
    ProviderPath    REG_SZ    C:\Program Files (x86)\WinFsp\bin\winfsp-x64.dll
    DeviceName    REG_SZ    \Device\WinFsp.Mup


HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\EventLog\Application\WinFsp
    EventMessageFile    REG_SZ    C:\Program Files (x86)\WinFsp\bin\winfsp-x64.dll
    TypesSupported    REG_DWORD    0x7


WINFSP FSD CONFIGURATION AND STATUS

SERVICE_NAME: WinFsp
        TYPE               : 2  FILE_SYSTEM_DRIVER
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
[SC] QueryServiceConfig SUCCESS

SERVICE_NAME: WinFsp
        TYPE               : 2  FILE_SYSTEM_DRIVER
        START_TYPE         : 3   DEMAND_START
        ERROR_CONTROL      : 1   NORMAL
        BINARY_PATH_NAME   : \??\C:\Program Files (x86)\WinFsp\bin\winfsp-x64.sys
        LOAD_ORDER_GROUP   :
        TAG                : 0
        DISPLAY_NAME       : WinFsp
        DEPENDENCIES       :
        SERVICE_START_NAME :

D:(A;;LCRP;;;WD)(A;;CCLCSWRPWPDTLOCRRC;;;SY)(A;;CCDCLCSWRPWPDTLOCRSDRCWDWO;;;BA)(A;;CCLCSWLOCRRC;;;IU)(A;;CCLCSWLOCRRC;;;SU)

WINFSP LAUNCHER SERVICE CONFIGURATION AND STATUS

SERVICE_NAME: WinFsp.Launcher
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, ACCEPTS_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
[SC] QueryServiceConfig SUCCESS

SERVICE_NAME: WinFsp.Launcher
        TYPE               : 10  WIN32_OWN_PROCESS
        START_TYPE         : 2   AUTO_START
        ERROR_CONTROL      : 0   IGNORE
        BINARY_PATH_NAME   : "C:\Program Files (x86)\WinFsp\bin\launcher-x64.exe"
        LOAD_ORDER_GROUP   :
        TAG                : 0
        DISPLAY_NAME       : WinFsp.Launcher
        DEPENDENCIES       :
        SERVICE_START_NAME : LocalSystem

D:(A;;CCLCSWRPWPDTLOCRRC;;;SY)(A;;CCDCLCSWRPWPDTLOCRSDRCWDWO;;;BA)(A;;CCLCSWLOCRRC;;;IU)(A;;CCLCSWLOCRRC;;;SU)

OS INFORMATION

Host Name:                 DESKTOP-JFRQ2IA
OS Name:                   Microsoft Windows 10 Pro N
OS Version:                10.0.17763 N/A Build 17763
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          User
Registered Organization:
Product ID:
Original Install Date:     2/8/2019, 10:11:11 AM
System Boot Time:          10/25/2019, 1:20:55 PM
System Manufacturer:       QEMU
System Model:              Standard PC (Q35 + ICH9, 2009)
System Type:               x64-based PC
Processor(s):              2 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 94 Stepping 3 GenuineIntel ~2592 Mhz
                           [02]: Intel64 Family 6 Model 94 Stepping 3 GenuineIntel ~2592 Mhz
BIOS Version:              SeaBIOS 1.12.0-1, 4/1/2014
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-08:00) Pacific Time (US & Canada)
Total Physical Memory:     16,383 MB
Available Physical Memory: 11,694 MB
Virtual Memory: Max Size:  18,815 MB
Virtual Memory: Available: 14,240 MB
Virtual Memory: In Use:    4,575 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\DESKTOP-JFRQ2IA
Hotfix(s):                 14 Hotfix(s) Installed.
                           [01]: KB4519569
                           [02]: KB4465065
                           [03]: KB4470788
                           [04]: KB4480056
                           [05]: KB4486153
                           [06]: KB4493510
                           [07]: KB4499728
                           [08]: KB4504369
                           [09]: KB4509095
                           [10]: KB4512577
                           [11]: KB4512937
                           [12]: KB4516115
                           [13]: KB4521862
                           [14]: KB4519338
Network Card(s):           2 NIC(s) Installed.
                           [01]: Red Hat VirtIO Ethernet Adapter
                                 Connection Name: Ethernet
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.122.1
                                 IP address(es)
                                 [01]: 192.168.122.150
                                 [02]: fe80::250d:2e18:8fd1:e4ae
                           [02]: TAP-Windows Adapter V9
                                 Connection Name: Ethernet 2
                                 DHCP Enabled:    Yes
                                 DHCP Server:     10.8.0.9
                                 IP address(es)
                                 [01]: 10.8.0.10
                                 [02]: fe80::9f1:89c7:1ae5:bd74
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.
```

> How exactly do you start passthrough? Can you post full command line so that I can attempt to repro?

```
C:\Users\User\Source\repos\passthrough\build\Debug>passthrough-x64.exe -p c:\ -m p:
passthrough -p c:\ -m p:
The service passthrough has been started.
```

**Comment by billziss-gh** [comment] 2019-11-01 21:08
@FrKaram @johntyner does this problem with latest WinFsp release (2019.3 B3). This is the version I was running when I could not reproduce.

**Comment by FrKaram** [comment] 2019-11-01 21:16
Testing it right now.
Even though I'm not sure WinFSP is the issue there. Can be on my side.

**Comment by FrKaram** [comment] 2019-11-01 21:21
OMG it does work with 2019.3 B3

**Comment by FrKaram** [comment] 2019-11-01 21:21
Procmon trace is a little bit different
![image](https://user-images.githubusercontent.com/8916606/68057377-fa6ac880-fcf5-11e9-8581-b324ad663687.png)

**Comment by billziss-gh** [comment] 2019-11-01 21:29
Wow, indeed!

I suspect that this may be related to 9436fd8402c5c8941d272abf3ce8f91ef46615e5.

But I do not understand why this worked with memfs/airfs, but not with passthrough prior to this release. It looks like memfs/airfs support some operation that satisfied the media player, so it would not issue the IOCTL's implemented in the commit above.

BTW, the IOCTL's above were implemented for better SQL Server compatibility. See issue #240.

**Comment by billziss-gh** [comment] 2019-11-01 21:38
Hmmm... the default sector size reported by passthrough is 4096 (which I recommend for performance) whereas the default sector size reported by memfs is 512 (which I use for better testing mapping buffers across processes during I/O).

It may be that when some apps see the 4096 sector size, they want to confirm that this is a valid sector size and issue one of the aforementioned IOCTL's to verify. This is perhaps where the difference comes from.

**Comment by FrKaram** [comment] 2019-11-01 21:40
I'm gonna try previous WinFSP with 512 sector size

**Comment by billziss-gh** [comment] 2019-11-01 21:41
@FrKaram great idea. Thank you!

**Comment by FrKaram** [comment] 2019-11-01 21:51
Few reboots later ...
2019.3 B2 works with 512 sector size

**Comment by billziss-gh** [comment] 2019-11-01 22:00
Thanks @FrKaram. So this confirms what the issue is.

**Comment by FrKaram** [comment] 2019-11-01 22:01
Yes indeed.
One problem solved

**Comment by billziss-gh** [comment] 2019-11-01 22:03
@stanimirivanovde @yogendersolanki91 @johntyner 

Can you please verify that this problem is fixed for you with latest WinFsp (2019.3 B3)? If yes, then we can close this issue.

@FrKaram thanks for yours!

**Comment by johntyner** [comment] 2019-11-01 22:34
Can confirm: works with 2019.3 B3.

I tested with the passthrough as well as my own FUSE-based FS. Nice work, guys.

**Comment by billziss-gh** [comment] 2019-11-02 18:57
Great! I will wait a couple of days to see if the OP (@stanimirivanovde) has the chance to verify and will close then.

**Comment by billziss-gh** [comment] 2019-11-05 17:15
Closing this as it appears to be resolved.

**Closed by billziss-gh** 2019-11-05 17:15 UTC

**Comment by nduong-ol** [comment] 2024-01-18 10:00
Hello @billziss-gh , I'm using cgofuse with winfsp to develop a file system on windows and I also encountered a similar issue with importing video file to Davinci Resolve. Here a error log from Davinci Resolve:

*** BMD::QT::Movie::Init[259]: read of 512 bytes failed with 22
*** BMD::QT::Movie::Create[70]: Init() failed with 22
*** BMDMacQuickTimeReader::BMDMacQuickTimeReader[218]: Movie::Create() failed
[0x00006fe0] | IO                   | ERROR | 2024-01-18 09:16:14,515 | Failed to create decoder for O:\System Bin\Dream_lake.mp4
[0x00006fe0] | IO                   | ERROR | 2024-01-18 09:16:14,515 | Failed to open video file <O:\System Bin\Dream_lake.mp4> for decoding, error: <Codec is not opened yet.>
[0x00006fe0] | IO                   | ERROR | 2024-01-18 09:16:14,515 | Failed to read video track information from file <Dream_lake.mp4> in O:\System Bin, track 0: codec DUMMY is not supported

Can you tell me how to set the sector size with cgofuse?

**Comment by billziss-gh** [comment] 2024-01-18 19:12
Not sure about error 22 (likely `EINVAL`) but since this looks like a private log from your file system, you should be able to debug it and find out where the error originates?

> Can you tell me how to set the sector size with cgofuse?

The default sector size for WinFsp-FUSE is 4096. You can control this using the `-o SectorSize=VALUE` option.
