### ISSUE TITLE
memfs isn't unmounting drive on Windows 10 when sent ctrl+c -- impossible to unmount drive other than uninstalling winfsp

### ISSUE THREAD

**Issue by nightlark** [billziss-gh/winfsp#345] opened 2021-01-15 08:46 UTC
## Bug Report

When testing winfsp with the memfs example, I am unable to get it to unmount the drive when memfs exits (is sent ctrl+c). The other issues and bug reports imply that this should make it unmount the drive.

After exiting memfs, selecting the drive it had created pops up a `Location is not available` message box. As it is not a network drive, it does not show up on the list of network drives that can be unmounted. I thought it was related to Dokan being installed so I uninstalled that, which made it unmount -- however when I reran memfs and tried to quit it again, the same problem reoccurred. Unfortunately this time I no longer have a copy of Dokan installed to use as a sacrifice to get the memfs drive unmounted.

### How to Reproduce

I installed winfsp (not using a network drive).

Then I ran: `./memfs-x64.exe -m Q:`

I then used ctrl+c to exit memfs. The `MEMFS (Q:)` drive remains in the list of drives on my system, but is inaccessible.

### Behaviors

Described above -- default memfs example isn't unmounting the drive it creates when it exits.

### Environment

- OS version and build: 10.0.19041 Build 19041
- WinFsp version and build: WinFsp 2020.2

**Comment by nightlark** [comment] 2021-01-15 09:01
Unrelated, is using winfsp in a mingw program supported? I noticed odd behavior with a program I was trying to get working that doesn't match up with the memfs example (it created a folder in the working directory instead of mapping a drive -- this was before I installed Dokan to see if their implementation would be easier to get working).

**Comment by billziss-gh** [comment] 2021-01-15 18:24
I am unable to reproduce this:

![image](https://user-images.githubusercontent.com/15330948/104764090-bf4a8e80-571b-11eb-91f3-ad1a730002e6.png)

(I pressed Ctrl-C where the red arrow is.)

Since I notice a slash (instead of your backslash) in your command `./memfs-x64.exe -m Q:` and you also mention mingw: perhaps you are running memfs in an non-Windows terminal? Some of these terminals can have weird handling of Ctrl-C for Windows console applications.

**Comment by nightlark** [comment] 2021-01-15 18:33
Yes, I noticed it required sending ctrl+c twice in a mingw/bash terminal, though I also tried running it in command prompt and noticed it didn't go away either -- though maybe it saw the memfs mount was already created and decided not to remove it after?

**Comment by billziss-gh** [comment] 2021-02-04 18:18
I am closing this as I do not believe that there is an actual problem. Please reopen if you find otherwise.

**Closed by billziss-gh** 2021-02-04 18:18 UTC
