### ISSUE TITLE
Microsoft Edge Compatibility

### ISSUE THREAD

**Issue by KeitcH** [billziss-gh/winfsp#151] opened 2018-03-20 08:13 UTC
Environment
----
Windows 10 Version 1709 (OS Build 16299.309)
WinFSP v1.3B1(2018.1.8)

Description
----
Microsoft Edge does not read the file(`pdf`, `jpg`, `html`, etc.) in the file system.
By the log, it doesn't call `read `operation between `open` and `release`.
No problem with other programs (even `Microsoft Explorer 11`).

Reproduce Steps
----
Execute `memfs-x64.exe -m r:` or `passthrough-fuse-x64.exe d: r:`
Open the file with `Microsoft Edge`

Expected behaviors
----
Show the contents of the file.

> NTFS

![edge-ntfs](https://user-images.githubusercontent.com/37568225/37641838-8a57622e-2c5e-11e8-8cae-7c74ce55aa3c.gif)

Actual behaviors
----
Show nothing.

> memfs

![edge-memfs](https://user-images.githubusercontent.com/37568225/37641934-cf8cede6-2c5e-11e8-9ce0-abbf6251afaf.gif)

> passthrough-fuse

![edge-fuse](https://user-images.githubusercontent.com/37568225/37642010-037683ce-2c5f-11e8-8b0d-838216f3ab8d.gif)

--------------------------------------------------------------------------------------

Before submitting this issue please review this checklist. Ideally all checkmarks should be checked upon submitting. (Use an x inside square brackets like so: [x])

- [x] **Issue type**: Please consider posting only bug reports or enhancement requests. Questions are better in the [WinFsp Google Group](https://groups.google.com/forum/#!forum/winfsp). Please also consult the [WinFsp Frequently Asked Questions](https://github.com/billziss-gh/winfsp/wiki/Frequently-Asked-Questions).
- [x] **No Duplicate**: Ensure that your issue has not been filed before. (Check open and closed issues.)
- [x] **Description**: Provide a descriptive title and a detailed explanation of the problem you are experiencing (for a bug report) or you are trying to solve (for an enhancement request).
- [x] **Reproduce**: For bug reports provide detailed information on how to reproduce the problem. For enhancement requests you do not need to provide this information, unless you find it relevant.
- [x] **Behaviors**: Provide information on the expected and actual behaviors.
- [x] **Environment**: For bug reports provide information about your OS version and build (e.g. 10.0.14393) and WinFsp version and build (e.g. 2017.2 or 1.2.17341). For enhancement requests you do not need to provide this information, unless you find it relevant.

**Comment by billziss-gh** [comment] 2018-03-20 16:17
Thank you for the bug report. This looks like a serious issue. I will investigate it immediately.

**Comment by billziss-gh** [comment] 2018-03-20 17:20
## TEST

Open a PDF file with Microsoft Edge.

## RESULTS

1. MEMFS 64 as **disk** drive. WinFsp v1.3B2, OS 10 Pro (Version 1607)
    - **FAIL**. Microsoft Edge never opens the file. It appears that it keeps trying to load the file.

2. MEMFS 64 as **network** drive. WinFsp v1.3B2, OS 10 Pro (Version 1607)
    - **PASS**. Microsoft Edge successfully displays the PDF file.

**Comment by billziss-gh** [comment] 2018-03-20 20:52
Analysis of this is proving difficult as Microsoft Edge manages to crash [FileSpy](http://www.zezula.net/en/fstools/filespy.html) even when WinFsp is not involved at all (i.e. the WinFsp driver is not loaded). I do not remember ever seeing FileSpy crash before!

Nevertheless I have managed to find that when opening a PDF file with Edge, multiple processes are involved:

- browser_broker
- MicrosoftEdge
- MicrosoftEdgeCP

According to the FileSpy logs that I have managed to get, the file is first opened by browser_broker and then handed to either MicrosoftEdge or MicrosoftEdgeCP. This happens when opening the file from the C: drive (NTFS) or MEMFS running as a network file system (MUP).

The handoff does not happen when running MEMFS as a disk file system. Browser_broker opens the file correctly, but for some reason fails to hand it off to MicrosoftEdge[CP]. The Edge UI is in the "page loading" state, which it never exits. It does not report any error messages (it is unclear if it will timeout if I leave it long enough).

I will try with WinDbg next as FileSpy appears unreliable in this scenario.

**Comment by billziss-gh** [comment] 2018-03-21 04:15
I spent quite some time today chasing this with various different tools (FileSpy, Procmon, WinDbg, WinFsp's own debug logging).

Unfortunately nothing obvious jumps out at me. Although the Edge UI appears to be waiting for the file to load, no IRP's appear to have been lost and the file systems remain responsive and functional.

Using procmon I was able to establish that the main difference that I can establish between the working case of a *network* drive and the non-working case of a *disk* drive is the following:

- `browser_broker.exe` issues an `IRP_MN_QUERY_DIRECTORY` with `FileIdBothDirectoryInformation` and `Pattern=="FILENAME-BEING_OPENED"`. This call is successful.

- In the case of a *network* drive: `MicrosoftEdgeCP.exe` eventually takes over and opens the file.

- In the case of a *disk* drive: `MicrosoftEdgeCP.exe` never attempts any file operations. It is not clear why this is the case.

**Comment by billziss-gh** [comment] 2018-04-08 07:30
**NOTE**: I am suspecting that this has to do with the AppContainers technology which Microsoft Edge uses by default.

**Comment by webfolderio** [comment] 2018-11-07 13:00
I couldn't reproduce the problem, Edge render the pdf without an error.

Environment:
```
Windows 10 Pro (EN), Microsoft Version 10.0.17134.376
winfsp version: 1.3.18160
memfs -t -1 -n 1024 -s 16777216 -m r:
```

**Comment by billziss-gh** [comment] 2018-11-14 20:19
@webfolderio thank you. I will look into this again soon. Perhaps it was a Windows problem that got fixed?

**Comment by alfaunits** [comment] 2018-12-20 17:06
Can you try running a modified MemFS/PTFS sample, that does not have GetSecurity/SetSecurity/GetSecurityByName? (all three should be NULL)

I remember when I did encryption filters, Edge was an extreme corner case in that the process that opens the file does so with incredibly low permissions, and it is unable to access anything outside of "low-permission" folders.
It is possible the PDF renderer is the cause, if you do not see this with other files.

**Comment by billziss-gh** [comment] 2019-04-01 23:13
As of Win10 version 1803 or later this no longer happens. I am therefore closing this as it looks like it was an Edge problem that has been resolved in later version of the OS.

**Comment by vxgmichel** [comment] 2019-11-28 14:49
I ran into a similar issue with the following configuration:

- Winfsp-1.5.19320
- Windows 10 version 1903

Screenshot:

![edge](https://user-images.githubusercontent.com/7490006/69815301-dee6c680-11aa-11ea-8018-a8441ef51592.png)

**Comment by billziss-gh** [comment] 2019-11-28 19:26
@vxgmichel 

Interesting. This suggests that this may be a user configuration issue, since it seems to happen for some users, but not others. Is there something special about your setup?

**Comment by vxgmichel** [comment] 2019-12-03 15:01
> Is there something special about your setup?

I thought there was nothing special about it, as I used a standard [windows 10 development environment](https://developer.microsoft.com/en-us/windows/downloads/virtual-machines). Nonetheless, I decided to fire up a fresh VM to make sure I could reproduce the bug from a clean state. And surprise, edge opened the pdf just fine with the following settings:

- Winfsp-1.5.19320
- Windows 10 version 1909
- `memfs-x64.exe -m r:`

I can't tell whether the problem comes from the windows 10 version (`1903` vs `1909`) or something else from my old environment. Reproducing bugs on windows is quite frustrating... I've seen this problem on other machines too, do you have any advice on how I should approach this issue the next time I see it? Thanks :)

**Comment by alfaunits** [comment] 2019-12-03 17:45
Open a Command Prompt and type "icacls PDF_FILE_NAME" on both systems.
Paste the two outputs here.

On 12/3/19, Vincent Michel <notifications@github.com> wrote:
>> Is there something special about your setup?
>
> I thought there was nothing special about it, as I used a standard [windows
> 10 development
> environment](https://developer.microsoft.com/en-us/windows/downloads/virtual-machines).
> Nonetheless, I decided to fire up a fresh VM to make sure I could reproduce
> the bug from a clean state. And surprise, edge opened the pdf just fine with
> the following settings:
>
> - Winfsp-1.5.19320
> - Windows 10 version 1909
> - `memfs-x64.exe -m r:`
>
> I can't tell whether the problem comes from the windows 10 version (`1903`
> vs `1909`) or something else from my old environment. Reproducing bugs on
> windows is quite frustrating... I've seen this problem on other machines
> too, do you have any advice on how I should approach this issue the next
> time I see it? Thanks :)
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/billziss-gh/winfsp/issues/151#issuecomment-561206427


-- 
Kind regards, Dejan Maksimovic.
FS Lead: http://www.alfasp.com

**Comment by vxgmichel** [comment] 2019-12-04 15:43
> Open a Command Prompt and type "icacls PDF_FILE_NAME" on both systems.

[System 1](https://developer.microsoft.com/en-us/windows/downloads/virtual-machines) - **do not** reproduce the issue:
- Winfsp-1.5.19320
- Windows 10 version 1909
- `memfs-x64.exe -m r:`
- ```
  R:\pdf.pdf 
  WINDEV1911EVAL\User:(F)
  BUILTIN\Administrators:(F)
  NT AUTHORITY\SYSTEM:(F)
  ```
[System 2](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) - **does** reproduce the issue:
- Winfsp-1.5.19320
- Windows 10 version 1809
- `memfs-x64.exe -m r:`
- ```
  R:\sample.pdf 
  MSEDGEWIN10\IEUser:(F)
  NT AUTHORITY\SYSTEM:(F)
  NT AUTHORITY\LogonSessionId_0_133190:(RX)
  ```

**Comment by alfaunits** [comment] 2019-12-04 15:52
Hmm, neither of those should work.. there is no Mandatiry Label, so
Integrity Level is Medium.

Can you monitor the opening via Process Monitor? Attach the log from both
systems please.

**Comment by vxgmichel** [comment] 2019-12-04 18:46
> Can you monitor the opening via Process Monitor? Attach the log from both
systems please.

Sure! I'm not sure what you're interested in though, which filter do you want me to apply during the capture?

**Comment by alfaunits** [comment] 2019-12-04 18:49
Just file system activity.
Dont filter any of it out. I am guessing Edge cannkt copy the pdf to a temp
location due to Integrity level issues.

Kind regards, Dejan.

**Comment by vxgmichel** [comment] 2019-12-04 19:40
No problem, here's the log file for the first system (the one that **does not** reproduce the issue): [System1.zip](https://github.com/billziss-gh/winfsp/files/3923606/System1.zip)

I used two filters in order to reduce the size of the file:
- `EventClass` -  `is` - `File System` - `Include`
- `Path` - `ends with` - `.dll` - `Exclude`

Also, Edge was already running when I opened the file in order to reduce the amount of logs. I counted 4 different accesses to the PDF file, coming from an application called `MicrosoftPdfReader.exe`:
- 2 occurrences of `QueryStandardInformationfile`
- 2 occurrences of `CreateFileMapping`

I'll get back with the logs for the second system once I have access to them. Hope that helps :)

**Comment by billziss-gh** [comment] 2019-12-04 21:17
@vxgmichel FWIW there does seem to be a difference in the permissions (which may or may not be significant):

- In the **does not reproduce** case you have `BUILTIN\Administrators` with `F`ull Access.
- In the **does reproduce** case `BUILTIN\Administrators` is missing (and you have `LogonSessionId` instead).

BTW, the system that reproduces appears to be a prepackaged Microsoft Edge VM. If this is correct can you point me to the specific download so I can try it myself?

Also thanks you @alfaunits for helping with troubleshooting this.

**Comment by c4ffein** [comment] 2019-12-05 10:38
Hi, I'm @vxgmichel colleague

Here is the logfile : 
file:///home/sharl/Downloads/LogfileFailEdgeOpening.zip
I can also share you the link to the VM, which is https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/
Just select "MSEdge on Windows 10 (x64) Stable 1809" and "Virtualbox" if you want the same setup.

Thank you for your time and your help!

**Comment by alfaunits** [comment] 2019-12-06 20:55
I'll take a deeper look over the weekend.
But at first glance, I do not see any typical Integrity level related issues...

On 12/5/19, c4ffein <notifications@github.com> wrote:
> Hi, I'm @vxgmichel colleague
>
> Here is the logfile :
> file:///home/sharl/Downloads/LogfileFailEdgeOpening.zip
> I can also share you the link to the VM, which is
> https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/
> Just select "MSEdge on Windows 10 (x64) Stable 1809" and "Virtualbox" if you
> want the same setup.
>
> Thank you for your time and your help!
>
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/billziss-gh/winfsp/issues/151#issuecomment-562072634


-- 
Kind regards, Dejan Maksimovic.
FS Lead: http://www.alfasp.com

**Comment by alfaunits** [comment] 2019-12-06 20:58
Can you do icacls on
C:\Users\IEUser\AppData\Local\Packages\Microsoft.MicrosoftEdge_8wekyb3d8bbwe\AC\MicrosoftEdge\Cache

and

C:\Users\User\AppData\Local\Packages\Microsoft.MicrosoftEdge_8wekyb3d8bbwe\AC\MicrosoftEdge\Cache

(depending on the machine)

**Comment by vxgmichel** [comment] 2019-12-06 21:06
@alfaunits Thanks for investigating this! 

The output of `icacls` on the system that **does not** reproduce the issue is:
```
C:\Users\User\AppData\Local\Packages\Microsoft.MicrosoftEdge_8wekyb3d8bbwe\AC\MicrosoftEdge\Cache 
S-1-15-2-3624051433-2125758914-1423191267-1740899205-1073925389-3782572162-737981194:(I)(OI)(CI)(CR)(F)
NT AUTHORITY\SYSTEM:(I)(OI)(CI)(F)
BUILTIN\Administrators:(I)(OI)(CI)(F)
WINDEV1911EVAL\User:(I)(OI)(CI)(F)
Mandatory Label\Low Mandatory Level:(I)(OI)(CI)(NW)
```

**Comment by vxgmichel** [comment] 2019-12-06 21:14
@alfaunits I also noticed those `INVALID DEVICE REQUEST` logs:

![invalid_device_request](https://user-images.githubusercontent.com/7490006/70356761-fd436680-1829-11ea-81ed-e32ac88aa39f.png)

They do not appear on the system that does not reproduce the issue. Do you think it is related?

**Comment by alfaunits** [comment] 2019-12-06 21:31
No, those are unimportant AFAIK

Kind regards, Dejan.

**Comment by c4ffein** [comment] 2019-12-13 14:15
Here are the output from the machine that reproduces this issue :
```C:\Users\IEUser\AppData\Local\Packages\Microsoft.MicrosoftEdge_8wekyb3d8bbwe\AC\MicrosoftEdge\Cache S-1-15-2-3624051433-2125758914-1423191267-1740899205-1073925389-3782572162-737981194:(I)(OI)(CI)(CR)(F)
                                                                                                    NT AUTHORITY\SYSTEM:(I)(OI)(CI)(F)
                                                                                                    BUILTIN\Administrators:(I)(OI)(CI)(F)
                                                                                                    MSEDGEWIN10\IEUser:(I)(OI)(CI)(F)
                                                                                                    Mandatory Label\Low Mandatory Level:(I)(OI)(CI)(NW)

Successfully processed 1 files; Failed processing 0 files```

Again, thank you for your time!

**Comment by alfaunits** [comment] 2019-12-13 18:43
Hmm, nothing strange in the ICACLS output..
I checked out the two Process monitor outputs, and I still see nothing
that makes sense, as to why it fails on one of the machines.


The only strange thing is... are you sure the PML files are named correctly?
The System1.pml (supposedly working?) has NO access to Sample.pdf
LogfileFailEdgeOpening.PML - has access to Sample.pdf

-- 
Kind regards, Dejan Maksimovic.
FS Lead: http://www.alfasp.com

**Comment by vxgmichel** [comment] 2019-12-13 18:55
> The only strange thing is... are you sure the PML files are named correctly?
> The System1.pml (supposedly working?) has NO access to Sample.pdf

Oh sorry, the pdf file is called `pdf.pdf` on system 1 and I can confirm there are 259 file system logs involving `\Device\Volume{aeecf71e-170d-11ea-8a9c-0800276c890e}\pdf.pdf`.

**Comment by billziss-gh** [comment] 2019-12-18 01:07
Sorry for the long delay.

I have been busy getting [winfuse](https://github.com/billziss-gh/winfuse) ready for its first release.

I will download the "MSEdge on Windows 10 (x64) Stable 1809" VM and try to reproduce.

**Comment by billziss-gh** [comment] 2020-12-19 18:31
I am revisiting old problems to make sure they are still valid.

This problem no longer happens for me with new Microsoft Edge (based on Chromium).

![Annotation 2020-12-19 101807](https://user-images.githubusercontent.com/15330948/102696741-44a65600-41e5-11eb-9939-15d3e5c1d81c.jpg)

I am closing this, but please reopen if the problem reappears.

**Closed by billziss-gh** 2020-12-19 18:31 UTC
Labels: bug
