### ISSUE TITLE
Issue with MEMFS when the Cache Manager is used

### ISSUE THREAD

**Issue by FrKaram** [billziss-gh/winfsp#96] opened 2017-07-03 12:42 UTC
Hi Bill,

I was having file corruption issues with PowerPoint files with my implementation and so I decided to check with memfs-dotnet to see how it behave. 

Memfs-dotnet have the same problem.

I managed to find a reproductible procedure to hightlight this behavour (corruption does not open everytime ) :

1\ Download this document with which I do my tests : www.unm.edu/~unmvclib/powerpoint/pptexamples.ppt
2\ Copy this document to memfs-dotnet
3\ Open the document with PowerPoint
4\ Delete the picture on first slide
5\ Delete slide 3 (the pink one)
6\ Save and quit powerpoint
7\ Reopen the file

If it behaves like on my PC, you should have 

![image](https://user-images.githubusercontent.com/8916606/27793256-9d94caa8-5ffd-11e7-909f-946aa6354f7d.png)

I haven'd found yet what could be the cause of this corruption.

Any idea ?

Thanks

**Comment by billziss-gh** [comment] 2017-07-03 18:02
Unfortunately I do not own Powerpoint on Windows (only on macOS) so I cannot see this myself.

I have a few suggestions to try and further troubleshoot this:

- By default memfs-dotnet and memfs limit file sizes to 16MB. Can you confirm that the powerpoint does not get bigger than this? [The downloaded file is only 1.8MB so I do not expect this to be the issue.]

- Can you confirm that this does not happen with the powerpoint when run over NTFS?

- Can you confirm whether it happens with plain memfs (i.e. the one written in C/C++)? This would help us determine whether this is a .NET layer issue or a general WinFsp issue.

- Can you try running MEMFS with the `-d -1 -D -` switches to see debug log output while performing the above mentioned operations?

- There is a batch file called diag.bat under `\Program Files (x86)\WinFsp\bin`. Can you run it and send me the log output?

- Does this happen on multiple computers/VM's? Or just this one?

**Comment by fsgeek** [comment] 2017-07-03 18:35
https://products.office.com/en-us/try

You can try the office suite free for a month.  If you do this inside a VM,
you can repeat this process in the future as well.

**Comment by billziss-gh** [comment] 2017-07-03 18:36
@fsgeek thank you.

**Comment by FrKaram** [comment] 2017-07-03 18:37
I try all that and keep you posted

**Comment by FrKaram** [comment] 2017-07-04 08:04
-     By default memfs-dotnet and memfs limit file sizes to 16MB. Can you confirm that the powerpoint does not get bigger than this? [The downloaded file is only 1.8MB so I do not expect this to be the issue.]
-> The file is indeed 1.8Mb and after the modification is shrinks to 1.3Mb so it's not the 16Mb limitation
-> BTW, where is this 16Mb limit configured ?

-     Can you confirm that this does not happen with the powerpoint when run over NTFS?
-> Does not happen on NTFS
 
-     Can you confirm whether it happens with plain memfs (i.e. the one written in C/C++)? This would help us determine whether this is a .NET layer issue or a general WinFsp issue.
-> I reproduce with memfs-x64.exe
 
-     Can you try running memfs with the -d -1 -D - switches to show debug log output while performing the above mentioned operations?
-> See attached log.txt. While logging, I did the procedure twice. First time it worked correctly. I deleted the file. Copied a clean version. Did the procedure a second time and the file was corrupted.

-     There is a batch file called diag.bat under \Program Files (x86)\WinFsp\bin. Can you run it and send me the log output?
-> See attached diagresult.txt
 
-     Does this happen on multiple computers/VM's? Or just this one?
-> Happens on other computers

The problem does not occur with the -t 0 parameter. Could it be a cache issue ?
[diagresult.txt](https://github.com/billziss-gh/winfsp/files/1121213/diagresult.txt)
[log.txt](https://github.com/billziss-gh/winfsp/files/1121214/log.txt)

**Comment by billziss-gh** [comment] 2017-07-04 17:42
@FrKaram thank you for your investigation on this.

> BTW, where is this 16MB limit configured ?

You can configure it using the `-s` switch in memfs.

> I reproduce with memfs-x64.exe

Ok. This means that this is a more general problem.

> The problem does not occur with the -t 0 parameter. Could it be a cache issue ?

It sounds like it.

The `-t` option controls the value of [`FileInfoTimeout`](https://github.com/billziss-gh/winfsp/blob/v1.1/inc/winfsp/fsctl.h#L136). The `FileInfoTimeout` is used as follows:

- If `FileInfoTimeout==0` the FSD does not do any caching at all. Almost all file system operations are passed to the user mode file system (which may do its own caching).

- If `FileInfoTimeout>0 && FileInfoTimeout!=(UINT32)-1` the FSD will cache file metadata information (for the specified time), but will not cache actual file data. The FSD does this by using its own caching mechanism and does not use the NTOS cache manager for this purpose. Many file system operations (e.g. `GetFileInfo`) are satisfied by the FSD and do not need to be sent to the user mode file system.

- If `FileInfoTimeout==-1` the FSD will cache file metadata and data information indefinitely (i.e. without timeout). It will use its own caching mechanism for file metadata and the NTOS cache manager for file data. Most file system operations can be satisfied from cache, for example `GetFileInfo`, `Read` and `Write` will be satisfied from cache.

Based on your investigation so far I understand the following:

- The problem **does not happen** with `-t 0` (`FileInfoTimeout==0`).

- The problem **does happen** with `-t -1` (`FileInfoTimeout==-1`).

- Could you also try with `-t 1000` (`FileInfoTimeout==1000`). This instructs the FSD to cache metadata for 1000 ms and would let us know which cache (metadata or data) exhibits the problem.

> diagresult.txt
log.txt

Thank you for these. I will study the logs and see if there is something obvious (although if the problem is a caching issue, this will not necessarily show up on the logs).

**Comment by billziss-gh** [comment] 2017-07-04 18:38
@FrKaram can you please also let me know what version of Powerpoint you are using? I am looking into getting Powerpoint for Windows, but I would like to get the right version.

**Comment by FrKaram** [comment] 2017-07-04 18:50
I've just tested with -t 1000 and did not encounter any issue.

![image](https://user-images.githubusercontent.com/8916606/27840581-78fb4dc2-60fa-11e7-8ccd-23449fa54121.png)

**Comment by billziss-gh** [comment] 2017-07-04 19:35
> I've just tested with -t 1000 and did not encounter any issue.

This means that the issue is with WinFsp's use of the NTOS cache manager.

I will see if I can get Powerpoint 2016 and attempt to reproduce myself with `-t -1`.

----

Thank you for being so helpful. Some additional thoughts if you are feeling adventurous:

- If you have DebugView from Sysinternals, you can run the file system with the `-d -1` switch (without the `-D -` part. Debug log output will then go to DebugView. DebugView has the ability to add comments in your log (under Edit > Append Comment). This way you can provide some commentary along the lines of "deleting powerpoint slide x", "reopening powerpoint", etc.

- Ladislav Zezula has created a fantastic program called [FileSpy](http://www.zezula.net/en/fstools/filespy.html). FileSpy actually shows all file activity in the system at the IRP (I/O Request Packet) level. Unfortunately FileSpy does not have the ability to inject commentary like DebugView (AFAIK) so it would be harder to match file system operations to actual user level operations. [I usually incrementally save the log with descriptive names to get around that problem.] BTW, to capture a WinFsp volume you would need to select the device with name `\Device\Volume{GUID}` under the Volumes menu item.

Both apps need to be run with Administrator privileges.

These tools together let us analyze both what the FSD sees, but also what the DLL sees.

**Comment by FrKaram** [comment] 2017-07-04 20:40
I know both tools (remind me of the time when I was working on a filesystem monitoring driver).
I don't know if I will have time to check that but if so, I'll post here.

**Comment by billziss-gh** [comment] 2017-07-05 04:51
I am able to reproduce this issue after installing Powerpoint 2016 32-bit on Win10 Pro 64-bit.

**Comment by FrKaram** [comment] 2017-07-05 05:17
I hope this is not a twited behaviour of Windows or Powerpoint

**Comment by billziss-gh** [comment] 2017-07-05 16:39
I spent some time looking at this last night and trying to decipher what Powerpoint is doing through the logs.

It seems to be doing cached writes on a temporary file, which it flushes using `FlushFileBuffers`. It then renames the temporary file back to the original file name `pptexamples.ppt`. I do not have a good understanding yet on where this fails.

I will also spend some time today trying to understand the problem.

**Comment by FrKaram** [comment] 2017-07-05 17:33
Fyi I got the issue with other ppt files. The one I gave you the link to is the only one to be "clean". All others are corrupted and as they were foe testing, I do not have the originals anymore

**Comment by billziss-gh** [comment] 2017-07-05 18:05
@fsgeek I am wondering if you have any feedback on this question:

When `CcSetFileSizes` is used to extend the cache manager's view of the file size, does the cache manager guarantee that the cache mapping has the extended portion zeroed out or does the FSD always have to call `CcZeroData`?

I am thinking specifically about a scenario such as the following.

- A cache mapping starts out as 2MB in size.
- It gets written across the whole 2MB range.
- It then gets pulled back to 1MB.
- Finally it is re-extended to 2MB.

My expectation has been that `CcSetFileSizes` is sufficient to zero out the (re-)extended portion of the mapping and that the mapping now has zeroes from 1MB to 2MB. This is without calling `CcZeroData`, which I have understood to be used to force `WRITE` of zero pages to disk.

WinFsp does not call `CcZeroData` and does not use ValidDataLength. The assumption has been that these were optimizations that a user mode file system could perform on its own and that `CcSetFileSizes` was intelligent enough to zero out cache mapping extensions. If that is not the case, I am unclear on how WinFsp passes [FSX](https://github.com/billziss-gh/secfs.test/tree/master/fstools/src/fsx) testing.

**Comment by fsgeek** [comment] 2017-07-05 18:19
VDL can easily drive you crazy.  Cc definitely tracks it internally to know
what should be zeroed and I have seen it as a source of data corruption in
the past (where Cc thinks something is beyond VDL but the FSD does not and
Cc triggers a zero out of the region).

For example, there's a discussion here -
https://www.osronline.com/showthread.cfm?link=157290 (it is just one of
many on the topic).

I suspect you've seen Malcolm's piece on this as well
https://www.osr.com/nt-insider/2015-issue2/maintaining-valid-data-length
 and the key point from that work is:

The Cache Manager optimization is used by NTFS but is optional for other
> file systems.  A file system may indicate that the Cache Manager should not
> attempt to track valid data by using the special value of MAXLONGLONG as
> the valid data length in a CcSetFileSizes call.  Having done so, the file
> system must take care to update valid data on disk in response to all
> paging writes.  This is the approach that ReFS takes as of Windows 8.1 and
> Server 2012 R2, leaving all data potentially valid in the cache and zeroing
> to the disk as needed when paging writes occur.


I'm assuming that you are using MAXLONGLONG as the VDL, in which case Cc
just leaves the problem to you.

It is strange how many things will work right but there are a few special
applications (and powerpoint is one of them) that seem to use the system in
an unexpected fashion.  So while one would hope that a test suite would
catch such an issue, its possible for it not to do so.  The IFS Kit
syscache test is quite good at finding these issues in my experience.

**Comment by billziss-gh** [comment] 2017-07-05 19:10
> I'm assuming that you are using MAXLONGLONG as the VDL, in which case Cc
just leaves the problem to you.

This is correct. WinFsp uses MAXLONGLONG as the VDL.

I am handling cached writes roughly as follows:

- If (and only if) the `WRITE` extends the file I first send (recursively) a `SET_INFORMATION [EndOfFile]` IRP to the FSD. The `EndOfFile` handler forwards the IRP to the user mode file system, which updates its own view of the `EndOfFile`.

- The user mode file system is now responsible to return zeroes from the old `EndOfFile` to the newly updated one on `READ`'s; it may do so by implementing the `ValidDataLength` optimization.

- On completion of the `SET_INFORMATION [EndOfFile]` IRP I also extend the cache mapping using `CcSetFileSizes` with the new `EndOfFile` / `FileSize`.

- Back in the cached `WRITE` I do the necessary `CcCopyWrite`, etc.

Nowhere in this process I call `CcZeroData`. The assumption has always been that **`CcSetFileSizes` will always zero out any extended portions** of a cache mapping. If that is not the case I may have to call `CcZeroData` and somehow avoid sending the recursive zeroed page`WRITE`'s to the user mode file system.

> I suspect you've seen Malcolm's piece on this as well
https://www.osr.com/nt-insider/2015-issue2/maintaining-valid-data-length

I have seen it, but must admit that it is mostly above my pay grade :)

> The Cache Manager optimization is used by NTFS but is optional for other
 file systems.  A file system may indicate that the Cache Manager should not
 attempt to track valid data by using the special value of MAXLONGLONG as
 the valid data length in a CcSetFileSizes call.  Having done so, the file
 system must take care to update valid data on disk in response to all
 paging writes.

My understanding is that the protocol outlined above should work correctly. I may be wrong of course.

> The IFS Kit syscache test is quite good at finding these issues in my experience.

Thanks. I am already using ifstest for testing. I will look into using syscache as well.

**Comment by fsgeek** [comment] 2017-07-05 20:01
I may be wrong, but my recollection is that once you turn off VDL tracking
the Cache Manager has no way to know what the filling policy should be
(thus, it should be faulting in any partial pages that get overwritten).
Having said that, though, if you do a *CcCopyWrite* across an entire page,
it should not fault in the data for that page.

So there are plenty of annoying cases here, including the write beyond EOF
- where you would need to zero out the unwritten range.  A move of EOF
without writing can be problematic as well.  For example, FAT does track
VDL in memory, but not on disk, so when the file gets closed
(IRP_MJ_CLEANUP) it zeros out the region from VDL to EOF.  There can also
be interesting problems if you have mixed memory mapping and file I/O
operations.  While we've been talking about Cc, it is important to keep in
mind that Mm also gets involved in this mix and it has *less* insight into
VDL.

The problem with having the issue in Powerpoint is that it makes it
difficult to do any sort of simple analysis.  What you want to look for is
some sort of unusual pattern of access, whether it is open, move EOF,
close, reopen, etc.  You *did* note that it happens after a rename.  Is it
possible there is an operation on the pre-rename version (such as an EOF
move and then close) that creates some added complexity with an
intermediate rename.  I am reaching at this point, but in my experience
these types of problems are very usage pattern specific.

**Comment by billziss-gh** [comment] 2017-07-05 21:17
> The problem with having the issue in Powerpoint is that it makes it
difficult to do any sort of simple analysis.

I agree. My approach so far has been to try simple scenarios within Powerpoint and observing the results in FileSpy. Of course just saving a file produces reams of data and it is very hard to know what fails. What's worse if I choose to "repair" the corrupted Powerpoint file it is always repaired successfully, even if I move the file to a different system. Which begs the question: what exactly does Powerpoint not like about the modified file?

The `CcSetFileSizes` thing was just a wild hunch based on a pattern that I saw during saving. It likely has nothing to do with the actual problem.

Thank you for your insights.

**Comment by FrKaram** [comment] 2017-07-06 05:15
Fyi, sometimes the repair fail and the file totally unreadable. Sometimes it succeed and the 3 first slides are empty ...
At least that's what's I'va noticed on my pc.
It seems to me that it the fact of changing the beginning of the file (slide 1) + the middle of it (slide 4) that cause the issue

**Comment by billziss-gh** [comment] 2017-07-06 20:30
@FrKaram I have not seen the repair fail, but your observation does point to a deeper problem. I will continue investigating this although it is not straightforward to solve, because we do not have an easy to understand repro.

There are a couple of things that I want to try in the hopes that they will resolve the issue. But I cannot promise a quick resolution unless we somehow gain a better understanding.

In the meantime please run your file system with a `FileInfoTimeout` value such as 1000 to disable the cache manager.

**Comment by FrKaram** [comment] 2017-07-06 20:36
Yeah, I guess nothing is simple at this level of complexity.
I'll test with t 1000. I think it will have consequences in the way the methods are called but I will adapt accordingly
Thanks for your efforts

**Comment by billziss-gh** [comment] 2017-07-06 20:38
The only thing that should change with `FileInfoTimeout=1000` is that you will be getting more `Read` and `Write` calls.

BTW, I consider this bug critical and will continue working on it until we have it resolved.

**Comment by FrKaram** [comment] 2017-07-06 20:44
If I can be of any help, do not hesitate to ask

**Comment by billziss-gh** [comment] 2017-07-07 00:58
## Experiments

I spent a few hours today experimenting with largely discouraging results. I tried the following experiments:

- A [`CcZeroData`](https://msdn.microsoft.com/en-us/library/windows/hardware/ff539243(v=vs.85).aspx) experiment with `Wait==TRUE`. Deadlock on a recursive `IRP_MJ_READ`.

- A [`CcUnmapFileOffsetFromSystemCache`](https://msdn.microsoft.com/en-us/library/windows/hardware/hh406345(v=vs.85).aspx) experiment was also unsuccessful. Bugcheck galore and it only works on Win8+ anyway.

At this point I was fairly discouraged, but I decided to try the `CcZeroData` experiment with `Wait==FALSE` this time. This resolved the `IRP_MJ_READ` deadlock and passed the WinFsp tests.

More importantly experimentation with Powerpoint has shown marked improvements:

- Modifying the `pptexamples.ppt` file, saving it, and then quitting Powerpoint now **works**. I can reliably reopen the file without the need to repair. [Previously this scenario would never work for me.]

- Modifying the `pptexamples.ppt` file, quitting Powerpoint and then saving the file when the save dialog box pops up, results in a corrupted file (same as before).

While this is not the solution to this problem, I consider it a significant step forward. It appears that the problem may be related to `CcZeroData` after all.

## WORKING THEORY

My working theory is that under circumstances yet to be identified the cache mapping contains stale data after a file/cache extension. For example, if the file was 2MB, then pulled back to 1MB and then re-extended to 2MB, it may contain stale data.

I will attempt to improve my `CcZeroData` experiment so that I can reliably call it with `Wait==TRUE` and have it fully zero out the portion of the cache that is being extended. I have already built a mechanism so that `CcZeroData` writes are ignored by the `IRP_MJ_WRITE` handler (because they are useless and in fact counter-productive in the WinFsp API design).

**Comment by fsgeek** [comment] 2017-07-07 01:04
Do you call CcSetFileSizes in the truncate path? If not, Cc likely wouldn't know the file has shrunk. This is consistent with your hypothesis.

**Comment by billziss-gh** [comment] 2017-07-07 03:50
> Do you call CcSetFileSizes in the truncate path? If not, Cc likely wouldn't know the file has shrunk. This is consistent with your hypothesis.

Yes, I call `CcSetFileSizes` whenever the file size changes (at least I think I do). This includes truncations and extensions.

My theory is that the Cache Manager may sometimes have stale data when a file gets truncated to a partial page size and then re-extended. For example, from 2MiB down to 1MiB + 900 bytes and back to 2MiB. I have no solid data to back this theory up.

My intent is to try the following experiment: After extending the cache with CcSetFileSizes I will execute up to 3 `CcZeroData` calls:

- One `CcZeroData` call with `Wait==FALSE` iff the old `FileSize` was not on a page boundary. This will be from the old `FileSize` to the next page boundary.

- One `CcZeroData` call with `Wait==TRUE` from the page boundary immediately after the old `FileSize` to the page boundary immediately before the new `FileSize`. I have modified my `IRP_MJ_WRITE` handler to detect such writes and no-op them.

- Once `CcZeroData` call with `Wait==FALSE` from the last

**Comment by billziss-gh** [comment] 2017-07-07 22:47
@FrKaram have you ever been able to reproduce this on Win8? I am only able to reproduce it on Win10, but not Win8.

**Comment by FrKaram** [comment] 2017-07-08 05:38
@billziss-gh I haven't try win8. I need to build a VM to test it

**Comment by billziss-gh** [comment] 2017-07-08 15:51
@FrKaram no need to build a new VM if you have not already done so. I just wanted to confirm my finding that this cannot be reproduced on Win8. Every little clue is significant in figuring this one out.

Unfortunately my earlier experiments did not yield any real results. Until we find an easier to understand repro we may be unable to resolve this.

**Comment by FrKaram** [comment] 2017-07-08 18:09
I may have a win8 or winserver 2012 at work. I'll have a look if so.

With the procedure described in my first post, the issue occur almost everytime. I could do a Powerpoint interop based program that reproduce the problem, if needed

**Comment by billziss-gh** [comment] 2017-07-08 18:43
> I could do a Powerpoint interop based program that reproduce the problem, if needed

Actually something like that would be very useful. It would be great if we had a "real world" test suite, that does things like drive Office apps in scenarios like this one.

Your interop program could serve as the basis for that.

**Comment by FrKaram** [comment] 2017-07-10 08:36
I've been working on a quick program but, as you said, this thing is quite difficult to track.
I've not been able yet to reproduce a procedure that fails at each run.

**Comment by billziss-gh** [comment] 2017-07-12 00:12
I believe I may have resolved this with commits b35bf204db3a0ec926b846e4ef70833b29cbfa4b and 637f461a65d72c539625246f69d8ee69fb4ac541.

## FSX Experiments

After some random experimentation last week I set out this week to break WinFsp/MEMFS using [FSX](https://github.com/billziss-gh/secfs.test/tree/master/fstools/src/fsx). While I was unable to do so at first I eventually found that if the file written by FSX was also opened by a second process (e.g. Explorer) sometimes FSX would complain about the file having the wrong size.

I was eventually able to create a test scenario that would always fail within a few seconds of starting FSX. Using the FSX logs, together with FileSpy and WinFsp logs I was able to identify a subtle race condition which I describe below.

## Race Condition

In the WinFsp API after many file system operations complete the user mode file system communicates to the FSD the most recent metadata of the file that was operated upon. This information is communicated via the `FileInfo` data structure that many of the `FSP_FILE_SYSTEM_INTERFACE` operations return. It is important for the FSD and the user mode file system to maintain a consistent view of file metadata, especially when caching is enabled.

Consider the following scenario: a file is open and being appended to. The appends appear as WRITE IRP's and they are all synchronized by acquiring the `FileNode` resources exclusively. Part of the WRITE protocol involves returning an updated `FileInfo` for the written `FileNode`, which the FSD uses to update its view of the file metadata.

Now consider that another OPEN comes in for the same file. Because the FSD does not know yet which `FileNode` will be opened it does not acquire any `FileNode`. [Note that while it is possible to uniquely identify a `FileNode` by `FileName` currently, this would no longer be the case when we implement hard links.] The FSD posts the OPEN request to the user mode file system. The user mode file system processes the OPEN request successfully and responds with the opened file and its `FileInfo`.

Prior to the FSD processing the OPEN response additional WRITE IRP's come through the original file handle. These WRITE's update the `FileSize` as understood by the user mode file system and the corresponding (more recent) `FileInfo`'s get reported back to the FSD. Eventually the delayed OPEN response gets processed, which now clobbers the `FileInfo` as understood by the FSD with stale metadata.

The problem here is that OPEN requests have no way of locking the `FileNode` while the OPEN request is in transit to the user mode file system. In all other cases the user mode file system and the FSD update their view of the file's metadata (together) in an atomic fashion. Not so in the case of OPEN.

This is a subtle race condition, because the FileNode contains valid information, but that information is out of date with respect to what the user mode file system thinks even if only momentarily. In the case of FSX this creates a problem because FSX double-checks file metadata after its operations are complete and complains if they are not as expected.

## The Fix

My current fix is simple: do not update file metadata during an OPEN if the file was already open.

This seems to resolve the FSX issue. It also seems to resolve the Powerpoint issue, as I have not been able to reproduce the "repair" problem since introducing this change. It should be noted here that I am not 100% certain that the above race condition is the original cause of our Powerpoint problems.

----

@FrKaram would you be able to test a build that has this fix and verify whether this fixes the problem for you or not?

**Comment by billziss-gh** [comment] 2017-07-12 04:40
@FrKaram 
> I've been working on a quick program but, as you said, this thing is quite difficult to track.
I've not been able yet to reproduce a procedure that fails at each run.

If you still have that interop program, you may be able to get somewhere by constantly doing [`GetFileAttributes`](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364944(v=vs.85).aspx) on the `pptexamples.ppt` file in a separate thread. My earlier message (where I believe I have a fix for this issue) explains why.

**Comment by FrKaram** [comment] 2017-07-12 06:54
@billziss-gh Seems fine to me ! I wasn't able to reporduce the problem with the new version.

**Comment by billziss-gh** [comment] 2017-07-12 07:04
Fantastic. It looks like we can close this.

I will try to get a new build with this fix out before the end of July. Unfortunately producing the full build requires me to run the HLK tests in Server 2016 and that is an involved (and boring) process. I also have some other matters to attend to that I neglected while I was bug hunting on this issue.

**Comment by FrKaram** [comment] 2017-07-12 07:06
Yeah, I guess that was not an easy issue to solve
As for myself, I'm not in a hurry, holidays are coming :-)

I will certainly have more questions coming regarding the use of WinFSP. Should I open an issue for them or should I use another way ?

**Comment by billziss-gh** [comment] 2017-07-12 07:15
Feel free to open additional issues. Or you could use the google group [here](https://groups.google.com/forum/#!forum/winfsp). I monitor both, so whatever is more convenient for you.

**Comment by FrKaram** [comment] 2017-07-12 07:18
I must be the only one not having a Google account, so I may post here.
Anyway, congrats for solving this !

**Comment by billziss-gh** [comment] 2017-07-12 07:21
No problem. GitHub issues works as well.

Closing this. Please reopen if the problem resurfaces

**Closed by billziss-gh** 2017-07-12 07:21 UTC
Labels: bug, critical
