### ISSUE TITLE
Feature/Stability/Robustness comparison with dokany

### ISSUE THREAD

**Issue by brunoklein99** [billziss-gh/winfsp#83] opened 2017-04-19 22:53 UTC
I'm wondering, what are the pitfalls of WinFsp and Dokany, why would I create my project using one rather than the other?

**Comment by billziss-gh** [comment] 2017-04-19 23:23
Duplicate of #19. Please see the discussion there, which may answer some of these questions.

I have my own views of course, but I am obviously biased.

**Comment by billziss-gh** [comment] 2017-12-06 18:30
Closing this as I do not have anything else to add at this time.

**Closed by billziss-gh** 2017-12-06 18:30 UTC
