### ISSUE TITLE
Long delay when opening properties of a network volume

### ISSUE THREAD

**Issue by bugger123** [billziss-gh/winfsp#87] opened 2017-05-23 12:35 UTC
hallo, opening the properties page of a volume (right click in explorer) take pretty long > 20s.
opening the context menu for "nw disconnect" takes also ~ 10s. thats wired. steve

**Comment by billziss-gh** [comment] 2017-05-23 17:18
Yes, these long delays are definitely not right. If the file system is otherwise fast to use, the most likely culprit is that you have a "Network Provider" that attempts to resolve WinFsp shares (e.g. `\\memfs64\share`) as actual computer names on the network. This can take a long time.

Network providers are used in Windows to connect and disconnect to network drives. In the Windows architecture they are all tried in sequence one after the other. For compatibility reasons, WinFsp places itself last in the list of Network Providers that are tried, so every other provider gets a chance first. The fix here is to place the WinFsp Network Provider first in the list (and perhaps I should make this default.)

To eliminate other issues let me ask a couple of questions:

1. Which OS version are you running? Are you running a debug version of Windows or the driver verifier?

2. Which version of WinFsp are you running?

3. Can you please send me the output of running the batch file `C:\Program Files (x86)\WinFsp\bin\diag.bat`. [You may want to check the produced report to ensure that it does not contain any private information.]

**Comment by billziss-gh** [comment] 2017-05-23 18:35
@bugger123 I am just realizing that you may not know how to change the Network Provider DLL order. There is actually a way to do it from within the Windows interface although it is well hidden. Here are instructions:

https://www.interfacett.com/blogs/changing-the-network-provider-order-in-windows-10

**Comment by bugger123** [comment] 2017-05-24 09:09
bill, thansk for the fast response. its plain/fresh win10 in vmplayer. winfsp 1.0.17.072 is a fresh download.

seems to be release mode ? was there a debug selection ?  just wanted to give it a fest tryout with memfs.

also put winfsp.np in front using the reg. key. helped not much.

 

steve

 

 

Gesendet: Dienstag, 23. Mai 2017 um 19:18 Uhr
Von: "Bill Zissimopoulos" <notifications@github.com>
An: billziss-gh/winfsp <winfsp@noreply.github.com>
Cc: bugger123 <sngan@web.de>, Author <author@noreply.github.com>
Betreff: Re: [billziss-gh/winfsp] long delay (#87)


Yes, these long delays are definitely not right. If the file system is otherwise fast to use, the most likely culprit is that you have a "Network Provider" that attempts to resolve WinFsp shares (e.g. \\memfs64\share) as actual computer names on the network. This can take a long time.

Network providers are used in Windows to connect and disconnect to network drives. In the Windows architecture they are all tried in sequence one after the other. For compatibility reasons, WinFsp places itself last in the list of Network Providers that are tried, so every other provider gets a chance first. The fix here is to place the WinFsp Network Provider first in the list (and perhaps I should make this default.)

To eliminate other issues let me ask a couple of questions:


	
	Which OS version are you running? Are you running a debug version of Windows or the driver verifier?
	
	
	Which version of WinFsp are you running?
	
	
	Can you please send me the output of running the batch file C:\Program Files (x86)\WinFsp\bin\diag.bat. [You may want to check the produced report to ensure that it does not contain any private information.]

**Comment by billziss-gh** [comment] 2017-05-24 22:12
[Argh! I just wrote a fairly long response and lost it by accidentally closing the wrong window. I have below an abridged version. Thanks github issues.]

For the first mount of MEMFS things can take longer. This is because most of the WinFsp.Launcher infrastructure has not been loaded yet, but also because a Windows driver called the MUP has to communicate with multiple kernel drivers to find which one serves the `\mem64\share` prefix.

As a result a mount of MEMFS immediately after booting Windows can take as much as 10 seconds or more when mounting it as a network drive (mounting as a disk drive is almost always instantaneous). Disconnecting should always be fast, I am a bit perplexed if you are finding that it is not.

Subsequent mounts should in general be much faster. Accessing the MEMFS file system should also be very fast as it comparable to or faster than NTFS in most scenarios ([WinFsp Performance Testing](https://github.com/billziss-gh/winfsp/wiki/WinFsp-Performance-Testing)).

It would also be helpful if you sent me that `diag.bat` output so that I have more information on the installed OS, how WinFsp is being used, etc.

**Comment by billziss-gh** [comment] 2017-05-24 22:35
> winfsp 1.0.17.072

This is version `v1.0`. Thank you!

> opening the properties page of a volume (right click in explorer) take pretty long > 20s.

Looking again at your original message I am realizing that the file system is slow not to be mounted, but to access its "properties" from Explorer.

Is this VM properly provisioned? Is the guest OS fast otherwise? Is the host system overloaded for any reason?

It would also be very helpful if you send me the output of the `diag.bat` file.

**Comment by bugger123** [comment] 2017-05-29 12:03
WINFSP INSTALLATION DIRECTORY AND LAUNCHER REGISTRATIONS

HKEY_LOCAL_MACHINE\SOFTWARE\WinFsp
    InstallDir    REG_SZ    C:\Program Files (x86)\WinFsp\


WINFSP DLL REGISTRATIONS

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\NetworkProvider\Order
    ProviderOrder    REG_SZ    VBoxSF,RDPNP,LanmanWorkstation,WebClient,Nfsnp,WinFsp.Np


HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WinFsp.Np\NetworkProvider
    Name    REG_SZ    Windows File System Proxy
    ProviderPath    REG_SZ    C:\Program Files (x86)\WinFsp\bin\winfsp-x64.dll


HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\EventLog\Application\WinFsp
    EventMessageFile    REG_SZ    C:\Program Files (x86)\WinFsp\bin\winfsp-x64.dll
    TypesSupported    REG_DWORD    0x7


WINFSP FSD CONFIGURATION AND STATUS

SERVICE_NAME: WinFsp 
        TYPE               : 2  FILE_SYSTEM_DRIVER  
        STATE              : 4  RUNNING 
                                (STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
[SC] QueryServiceConfig SUCCESS

SERVICE_NAME: WinFsp
        TYPE               : 2  FILE_SYSTEM_DRIVER 
        START_TYPE         : 3   DEMAND_START
        ERROR_CONTROL      : 1   NORMAL
        BINARY_PATH_NAME   : \??\C:\Program Files (x86)\WinFsp\bin\winfsp-x64.sys
        LOAD_ORDER_GROUP   : 
        TAG                : 0
        DISPLAY_NAME       : WinFsp
        DEPENDENCIES       : 
        SERVICE_START_NAME : 

D:(A;;LCRP;;;WD)(A;;CCLCSWRPWPDTLOCRRC;;;SY)(A;;CCDCLCSWRPWPDTLOCRSDRCWDWO;;;BA)(A;;CCLCSWLOCRRC;;;IU)(A;;CCLCSWLOCRRC;;;SU)S:(AU;FA;CCDCLCSWRPWPDTLOCRSDRCWDWO;;;WD)

WINFSP LAUNCHER SERVICE CONFIGURATION AND STATUS

SERVICE_NAME: WinFsp.Launcher 
        TYPE               : 10  WIN32_OWN_PROCESS  
        STATE              : 4  RUNNING 
                                (STOPPABLE, NOT_PAUSABLE, ACCEPTS_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
[SC] QueryServiceConfig SUCCESS

SERVICE_NAME: WinFsp.Launcher
        TYPE               : 10  WIN32_OWN_PROCESS 
        START_TYPE         : 2   AUTO_START
        ERROR_CONTROL      : 0   IGNORE
        BINARY_PATH_NAME   : "C:\Program Files (x86)\WinFsp\bin\launcher-x64.exe"
        LOAD_ORDER_GROUP   : 
        TAG                : 0
        DISPLAY_NAME       : WinFsp.Launcher
        DEPENDENCIES       : 
        SERVICE_START_NAME : LocalSystem

D:(A;;CCLCSWRPWPDTLOCRRC;;;SY)(A;;CCDCLCSWRPWPDTLOCRSDRCWDWO;;;BA)(A;;CCLCSWLOCRRC;;;IU)(A;;CCLCSWLOCRRC;;;SU)S:(AU;FA;CCDCLCSWRPWPDTLOCRSDRCWDWO;;;WD)

OS INFORMATION

Host Name:                 
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.14393 N/A Build 14393
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          admin
Registered Organization:   
Product ID:                
Original Install Date:     
System Boot Time:          
System Manufacturer:       
System Model:              
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 94 Stepping 3 GenuineIntel ~3408 Mhz
BIOS Version:              
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              de;German (Germany)
Time Zone:                 (UTC-08:00) Pacific Time (US & Canada)
Total Physical Memory:     2,048 MB
Available Physical Memory: 1,202 MB
Virtual Memory: Max Size:  2,688 MB
Virtual Memory: Available: 1,734 MB
Virtual Memory: In Use:    954 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    
Logon Server:              
Hotfix(s):                 9 Hotfix(s) Installed.
                           [01]: KB3176937
                           [02]: KB3194623
                           [03]: KB3199986
                           [04]: KB3202790
                           [05]: KB3211320
                           [06]: KB3214628
                           [07]: KB4013418
                           [08]: KB4020821
                           [09]: KB4019472
Network Card(s):           4 NIC(s) Installed.
                           [01]: Intel(R) PRO/1000 MT Desktop Adapter
                                 Connection Name: Ethernet
                                 DHCP Enabled:    No
                                 IP address(es)
                                 
                           [02]: Microsoft Kernel Debug Network Adapter
                                 Connection Name: Local Area Connection* 1
                                 Status:          Hardware not present
                           [03]: Intel(R) PRO/1000 MT Desktop Adapter
                                 Connection Name: Ethernet 2
                                 DHCP Enabled:    No
                                 IP address(es)
                                 
                           [04]: Intel(R) PRO/1000 MT Desktop Adapter
                                 Connection Name: Ethernet 3
                                 DHCP Enabled:    Yes
                                 
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.

**Comment by billziss-gh** [comment] 2017-05-29 22:46
@bugger123 thanks. I notice from the output below that you still have the WinFsp Network Provider as the last one in the list.

```
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\NetworkProvider\Order
    ProviderOrder    REG_SZ    VBoxSF,RDPNP,LanmanWorkstation,WebClient,Nfsnp,WinFsp.Np
```

Did you try moving the WinFsp Network Provider first in the list using the instructions posted earlier?

**Comment by bugger123** [comment] 2017-05-30 09:40
yes, i moved it forth and back. as i wrote, it has only marginal impact on the timings, steve.

 

 

Gesendet: Dienstag, 30. Mai 2017 um 00:46 Uhr
Von: "Bill Zissimopoulos" <notifications@github.com>
An: billziss-gh/winfsp <winfsp@noreply.github.com>
Cc: bugger123 <sngan@web.de>, Mention <mention@noreply.github.com>
Betreff: Re: [billziss-gh/winfsp] long delay (#87)


@bugger123 thanks. I notice from the output below that you still have the WinFsp Network Provider as the last one in the list.

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\NetworkProvider\Order
    ProviderOrder    REG_SZ    VBoxSF,RDPNP,LanmanWorkstation,WebClient,Nfsnp,WinFsp.Np


Did you try moving the WinFsp Network Provider first in the list using the instructions posted earlier?

**Comment by billziss-gh** [comment] 2017-09-06 02:31
I am doing issue cleanup and revisiting this issue.

I noticed that you are running NFS (you have the `nfsnp` network provider). I have often found that NFS often causes slowdowns. Do you still have this problem and does it persist if you remove NFS?

**Comment by bugger123** [comment] 2017-09-06 11:03
yes, it is still there even without nfs. nfs is just in place to compare perf. of diff. network-shares.

the ordering (provider) has some but only a pretty small impact.

 

thx

 

Gesendet: Mittwoch, 06. September 2017 um 04:31 Uhr
Von: "Bill Zissimopoulos" <notifications@github.com>
An: billziss-gh/winfsp <winfsp@noreply.github.com>
Cc: bugger123 <sngan@web.de>, Mention <mention@noreply.github.com>
Betreff: Re: [billziss-gh/winfsp] long delay (#87)


I am doing issue cleanup and revisiting this issue.

I noticed that you are running NFS (you have the nfsnp network provider). I have often found that NFS often causes slowdowns. Do you still have this problem and does it persist if you remove NFS?

**Comment by billziss-gh** [comment] 2017-12-06 18:45
I am adding this to be investigated for the next release.

I have seen myself delays, although nothing like what was described in the OP. Nevertheless I would like to understand why these delays happen, determine if WinFsp is the culprit and find ways to fix them.

**Comment by bugger123** [comment] 2017-12-08 12:41
bill, we see the sam behaviour with nfs. its unclear if it was the case before we installed winfsp.

i also have the feeling that it wasnt there from the beginning !? please update us if you found a solution.

 

thx steve

 

 

Gesendet: Mittwoch, 06. Dezember 2017 um 19:45 Uhr
Von: "Bill Zissimopoulos" <notifications@github.com>
An: billziss-gh/winfsp <winfsp@noreply.github.com>
Cc: bugger123 <sngan@web.de>, Mention <mention@noreply.github.com>
Betreff: Re: [billziss-gh/winfsp] long delay (#87)


I am adding this to be investigated for the next release.

I have seen myself delays, although nothing like what was described in the OP. Nevertheless I would like to understand why these delays happen, determine if WinFsp is the culprit and find ways to fix them.

**Comment by felfert** [comment] 2017-12-20 11:14
Hi Bill,

I think, there are multiple issues here.

Reason:
I had exactly the same issue, especially when initially mounting.

After changing HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\NetworkProvider\Order
like you mentioned before (putting WinFsp.Np in front [and rebooting just to be shure]) the initial mount is blazingly fast now.

However the delays for displaying properties has increased now and it is existent for all directory levels, 
not only the toplevel.

Another subtle difference:
If WinFsp.Np is last in the list, after a mount operation, a computer icon appears in the network neighborhood. Any action on that (expand, properties, etc.) fails after a long delay. If WinFsp.Np is first on the list, that computer icon does not get created. I have a feeling that the delays have something to do with this fake "computer" (even if it is not shown).

**Comment by billziss-gh** [comment] 2018-01-04 19:50
This appears to have been closed automatically by accepting @felfert's PR. Since there is more work to do on this, I am reopening it.

**Comment by felfert** [comment] 2018-01-06 20:54
While testing my fuse implemenation, I observed the following:

Whenever a delay happens, the test-machine sends out a broadcast netbios name lookup for the host-part of the UNC-prefix. This leads me to believe that the implementation of NPOpenEnum() in np.c might be incomplete. I will augment the code there to get a better clue about what is going on in there ...

**Comment by billziss-gh** [comment] 2018-01-08 09:42
@felfert I also suspect that this is not file system related and that the network provider may be the culprit. I intend to run some tests this week to test this theory.

**Comment by felfert** [comment] 2018-01-08 11:35
I did some more tests:

Each delay is caused by either a DNS-Lookup, a NetBios Name-Lookup or (if one of these succeds and the corresponding machine is down: multiple ARP requests).

I also found a simple workaround: Creating an entry in \Windows\system32\drivers\etc\hosts with the "server" name makes all those delays go away.

To figure out, if anything can be done in the network provider, I also did the following test:

1. No entries in the hosts file.
2. Removed all network providers except WinFSp.Np

After that, the various lookups (and the resulting delays) still happen.
This leads me to the conclusion, that Explorer apparently bypasses "normal" Network providers and does some lookup of its own. It also indicates, unfortunately nothing can be done about that from within the network provider.

**Comment by billziss-gh** [comment] 2018-01-08 18:11
@felfert thank you for your valuable research and pushing this forward.

When using UNC syntax (`\\Server\Share\Path`) there are system components involved both in user mode and in kernel mode:

- **User mode**: The user mode component is called MPR [(Multiple Provider Router)](https://msdn.microsoft.com/en-us/library/windows/desktop/aa378771(v=vs.85).aspx). The MPR handles all communication with the Network Providers (which are user mode DLL's) and asks each one in order (`SYSTEM\CurrentControlSet\Control\NetworkProvider\Order`) to handle the request. Typical MPR responsibilities are to map/disconnect network drives, list network resources, etc.

- **Kernel mode**: The kernel mode component is called MUP [(Multiple UNC Provider)](https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/support-for-unc-naming-and-mup). (The following discussion is Vista and higher specific.) A request to open a file with a name like `\\Server\Share\Path` actually gets routed to the MUP. The MUP interrogates all registered file systems (which are kernel mode drivers) with [`IOCTL_REDIR_QUERY_PATH_EX`](https://msdn.microsoft.com/en-us/library/windows/hardware/ff548320(v=vs.85).aspx) to determine which file system will handle a particular open (and caches the response for a little while, so that it does not have to continuously issue `IOCTL_REDIR_QUERY_PATH_EX`). I am quite certain that such MUP query requests happen in parallel to all registered file systems, although I cannot recall how I know this (and I may be wrong).

So I see two potential culprits that may issue the network name lookups you are seeing:

- Network providers other than WinFsp.Np. Even when we place WinFsp.Np as the first provider, it may be that we are not handling an important provider call, which then goes to the next provider and so on, resulting in delays. If that is the case it should be relatively easy to fix.

- MUP registered file systems other than WinFsp (e.g. network redirectors). Although the MUP issues query requests in parallel, it may actually wait for all queries to complete before deciding what file system is going to handle a particular file open. In this case there may be nothing that we can do (except something along the lines of your `/etc/hosts` file hacks). I am hopeful that the MUP is not the culprit, because I have never seen any delays when using the command line or any application other than Windows Explorer (except perhaps for an initial delay on the very first open).

My plan this week is to retrofit WinFsp.Np for testing, by adding all possible NP API calls to it and logging their usage. This may help us to pinpoint the call that Explorer likes to issue that slows things down.

Of course there is also the possibility that Explorer itself is trying to perform a network query directly, but I am finding this a bit unlikely.

Let me know if you have additional findings.

**Comment by billziss-gh** [comment] 2018-01-08 23:27
I seem to have hit a wall on this. Nevertheless I am documenting my findings so far.

Tested scenario: right-click on a WinFsp (SSHFS) network drive and select "Properties".

- There appear to be two delays: one upon the initial right-click and a second one upon selecting "Properties".

- The first delay appears to happen while executing in the context of the `explorer.exe` process. The second delay appears to happen while executing in the context of a `dllhost.exe` process that appears to implement the "Properties" dialog.

- I have implemented many more NP callbacks in the WinFsp NP DLL, but do not see any calls to these callbacks in my logs. This may be a mistake or misconfiguration on my part (e.g. not properly "enabling" these calls as they need to be "advertised" in at least 2 places: `NPGetCaps` and the DLL export table).

- I am able to simulate the Explorer behavior by using the [`SHObjectProperties`](https://msdn.microsoft.com/en-us/library/windows/desktop/bb762231(v=vs.85).aspx) function from my own test program. Another important function in this puzzle: [`SHOpenPropSheet`](https://msdn.microsoft.com/en-us/library/windows/desktop/bb762233(v=vs.85).aspx).

**Comment by billziss-gh** [comment] 2018-01-09 00:08
I may have an indication of what the problem is although I have not confirmed it.

In the documentation for [`FsRtlRegisterUncProviderEx`](https://msdn.microsoft.com/en-us/library/windows/hardware/ff547184(v=vs.85).aspx) it is stated:

> The ProviderOrder registry value determines the order in which MUP issues prefix resolution requests to individual network redirectors. This order can be changed dynamically without a reboot. This registry value is located under the following registry key:
>
> ```
> HKLM\CurrentControlSet\Control\NetworkProvider\Order
> ```

This is curious because this registry key is used to define Network Provider (NP) order and NP's are user-mode components. So how can this also be used to define kernel-mode component order?

Turns out that one can specify a [`DeviceName`](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/including-a-networkprovider-section) in the registry that names a kernel-mode device that corresponds to a NP!

Assuming this is indeed the problem, fixing it is not straightforward. The problem is that WinFsp creates kernel-mode devices with random names likes `\Device\Volume{GUID}` for every file system. So we do not have a nice static name that we can use for our `DeviceName`. I have to think how to retrofit this into the existing WinFsp MUP design.

**Comment by bugger123** [comment] 2018-01-09 10:05
bill, i hope you will find a easy workaround. thanks a lot for your inverstigations into this.

 

steve

 

Gesendet: Montag, 08. Januar 2018 um 19:11 Uhr
Von: "Bill Zissimopoulos" <notifications@github.com>
An: billziss-gh/winfsp <winfsp@noreply.github.com>
Cc: bugger123 <sngan@web.de>, Mention <mention@noreply.github.com>
Betreff: Re: [billziss-gh/winfsp] long delay (#87)


@felfert thank you for your valuable research and pushing this forward.

When using UNC syntax (\\Server\Share\Path) there are system components involved both in user mode and in kernel mode:


	
	User mode: The user mode component is called MPR (Multiple Provider Router). The MPR handles all communication with the Network Providers (which are user mode DLL's) and asks each one in order (SYSTEM\CurrentControlSet\Control\NetworkProvider\Order) to handle the request. Typical MPR responsibilities are to map/disconnect network drives, list network resources, etc.
	
	
	Kernel mode: The kernel mode component is called MUP (Multiple UNC Provider). (The following discussion is Vista and higher specific.) A request to open a file with a name like \\Server\Share\Path actually gets routed to the MUP. The MUP interrogates all registered file systems (which are kernel mode drivers) with IOCTL_REDIR_QUERY_PATH_EX to determine which file system will handle a particular open (and caches the response for a little while, so that it does not have to continuously issue IOCTL_REDIR_QUERY_PATH_EX). I am quite certain that such MUP query requests happen in parallel to all registered file systems, although I cannot recall how I know this (and I may be wrong).
	


So I see two potential culprits that may issue the network name lookups you are seeing:


	
	Network providers other than WinFsp.Np. Even when we place WinFsp.Np as the first provider, it may be that we are not handling an important provider call, which then goes to the next provider and so on, resulting in delays. If that is the case it should be relatively easy to fix.
	
	
	MUP registered file systems other than WinFsp (e.g. network redirectors). Although the MUP issues query requests in parallel, it may actually wait for all queries to complete before deciding what file system is going to handle a particular file open. In this case there may be nothing that we can do (except something along the lines of your /etc/hosts file hacks). I am hopeful that the MUP is not the culprit, because I have never seen any delays when using the command line or any application other than Windows Explorer (except perhaps for an initial delay on the very first open).
	


My plan this week is to retrofit WinFsp.Np for testing, by adding all possible NP API calls to it and logging their usage. This may help us to pinpoint the call that Explorer likes to issue that slows things down.

Of course there is also the possibility that Explorer itself is trying to perform a network query directly, but I am finding this a bit unlikely.

Let me know if you have additional findings.

**Comment by billziss-gh** [comment] 2018-01-13 01:11
A quick update on this. I am working on a WinFsp redesign that will hopefully resolve this issue. Unfortunately it is rather deep surgery so that it might take a while to implement properly, test and stabilize.

Here is a brief description of the current design and the new design as it relates to this problem.

**Current design**

Every network file system is represented internally by a volume device object (`fsvol` in WinFsp parlance). This `fsvol` device is registered with the Windows MUP under a name with the pattern `Volume{GUID}`. The MUP sets up a symbolic link from `\Device\Volume{GUID}` to `\Device\Mup\;Volume{GUID}` and handles I/O requests for `\Device\Mup\;Volume{GUID}\PATH` by routing them to our `fsvol` device as `\PATH`.

My speculation is that when registering our `fsvol` device with the MUP, the `fsvol` device is placed last in the MUP's list for handling UNC paths (`\Server\Share`). Therefore network redirectors, etc. get a first chance at handling a prefix such as `\sshfs\...` and WinFsp does not get a chance until after these redirectors are done, resulting in delays. (Turns out that the new post-Vista MUP no longer issues requests in parallel.)

**New design**

The new (attempted) design is as follows. Like in the old design every network file system is represented internally by a volume device object (`fsvol`). However WinFsp now registers a single device object (`fsmup`) with the MUP under the static name `WinFsp.Mup`. The MUP sets up a symbolic link from `\Device\WinFsp.Mup` to `\Device\Mup\;WinFsp.Mup` and handles I/O requests for `\Device\Mup\;WinFsp.Mup\PATH` by routing them to our `fsmup` device as `\PATH`.

The `fsmup` device maintains a prefix table that maps prefixes to `fsvol` devices. For example, `\sshfs` will be routed to one `fsvol` device, `\memfs64` will be routed to another `fsvol` device and so on. Clearly this is an extra indirection step, but it has a huge benefit: we now have a static name (`WinFsp.Mup`) that we can use to tell the MUP to register with a specific priority using the `NetworkProvider` registry key and hopefully eliminate those delays.

**Comment by felfert** [comment] 2018-01-13 08:57
Thanks for the update, @billziss-gh 

In the meantime, for my project, I'm using the workaround with the hosts file that i described earlier. Maybe that one should go into the FAQ. Speaking of FAQ/Wiki, I noticed that one cannot add entries. (No public write permission). If you would consider changing that, I'd feel tempted to add this myself and I also would add a HOWTO on cross-building/cross-packaging against WinFSP on Linux using mingw cross compilers that are available on major Linux distributions as well as my dockerized WiX.

Cheers
 -Fritz

**Comment by billziss-gh** [comment] 2018-01-13 17:37
@felfert 

> In the meantime, for my project, I'm using the workaround with the hosts file that i described earlier. Maybe that one should go into the FAQ.

If I am unsuccessful in my current efforts, I agree that we should add it.

> Speaking of FAQ/Wiki, I noticed that one cannot add entries. (No public write permission).

The reason that I have kept the wiki private, is that the wiki content can be found in the `doc` directory of the WinFsp repo. For example the FAQ is [`doc/Frequently-Asked-Questions.asciidoc`](https://github.com/billziss-gh/winfsp/blob/master/doc/Frequently-Asked-Questions.asciidoc).

When I edit the Wiki, I do it indirectly: I first edit the desired document in `doc` and then copy the `doc` contents into the Wiki. So you can send me a PR request against `doc` and your changes will end up in the Wiki.

> I also would add a HOWTO on cross-building/cross-packaging against WinFSP on Linux using mingw cross compilers that are available on major Linux distributions as well as my dockerized WiX.

Something like this would be very valuable and I would love to see it. Please consider sending a PR against `doc` to add your HOWTO.

**Comment by billziss-gh** [comment] 2018-01-19 14:18
I am closing this as I believe this issue has been addressed by the aforementioned commits.

**Closed by billziss-gh** 2018-01-19 14:18 UTC
Labels: in progress

**Comment by felfert** [comment] 2018-01-19 17:23
@billziss-gh:
I'd love to see a release of this.

**Comment by billziss-gh** [comment] 2018-01-19 21:35
I am currently traveling but I am hoping to make a release some time next week.

**Comment by billziss-gh** [comment] 2018-01-23 13:41
@felfert I have release version [2018.1 B2](https://github.com/billziss-gh/winfsp/releases/tag/v1.3B2)
