### ISSUE TITLE
File permission not matching st_mode

### ISSUE THREAD

**Issue by Marabon** [billziss-gh/winfsp#245] opened 2019-08-16 22:57 UTC
## Bug Report

I was having some issues with file permissions while using rar2fs and came across something weird. I was told by @hasse69 that this information could be useful in a ticket here.
Link to original issue at rar2fs: https://github.com/hasse69/rar2fs/issues/111

File permissions doesn't match the st_mode of the file.

```
struct stat {
    st_dev = 0
   st_mode = 100600 (octal)
    st_nlink = 1
    st_ino = 0
    st_uid = 197609
    st_gid = 197609
   st_rdev = 0
   st_size = 864775589
 st_blocks = 1689016
st_blksize = 0
}
```
st_size matches the file outputted in ls -l below, and st_mode 100600 above results in no permissions as seen below.
```
$ ls -l
total 844516
---------- 1 x x 864775589 Jun 23  2018 12.monkeys.s04e06.720p.web.x264-tbs.mkv
-rwxrwxr-x 1 x x        47 Jul 25  2018 12.monkeys.s04e06.720p.web.x264-tbs.nfo
-rwxrwxr-x 1 x x       900 Jul 25  2018 12.monkeys.s04e06.720p.web.x264-tbs.sfv
```

### How to Reproduce

Not sure.
I hope the information provided here and in the original issue is of use.

### Behaviors

st_mode 100600 should result in appropriate file permissions.

### Environment

OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17763 N/A Build 17763
WinFsp version:         1.4.19016

**Comment by hasse69** [comment] 2019-08-17 10:05
Just to clarify, the dump of the stat structure above is done immediately after filling in the data and returning from the FUSE `getattr` callback. I went through the code in `cygfuse` but could not see anything obvious that could result in this anomaly. The problem might very well lurk in some other layer. The problem with reproducing this is annoying since I myself do not see this and permissions are reported as expected and according to what is sent from the user-space file system.

**Comment by billziss-gh** [comment] 2019-08-19 14:49
I just went through the thread in the original bug reports at hasse69/rar2fs#111. I believe a number of things have been tried already, but I want to make sure that I understand.

Would a console session like this be accurate:

```
$ ls -l 12.monkeys.s04e06.720p.web.x264-tbs.mkv
---------- 1 x x 864775589 Jun 23  2018 12.monkeys.s04e06.720p.web.x264-tbs.mkv

$ stat 12.monkeys.s04e06.720p.web.x264-tbs.mkv
  File: 12.monkeys.s04e06.720p.web.x264-tbs.mkv
  Size: 864775589       Blocks: 844508     IO Block: 65536  regular file
Device: bfb1559ch/3216070044d   Inode: 7743262778922486871  Links: 1
Access: (0000/----------)  Uid: (197609/   x)   Gid: (197609/   x)
Access: 2018-06-23 11:49:38.000000000 +0200
Modify: 2018-06-23 11:49:38.000000000 +0200
Change: 2018-06-23 11:49:38.000000000 +0200
 Birth: -
```

All this while rar2fs reporting in its debug logs for this particular session and file that:

```
struct stat {
    st_dev = 0
   st_mode = 100644 (octal)
  st_nlink = 1
    st_ino = 0
    st_uid = 197609
    st_gid = 197609
   st_rdev = 0
   st_size = 864775589
 st_blocks = 1689016
st_blksize = 0
}
```

Also: is it possible to try the command `cacls 12.monkeys.s04e06.720p.web.x264-tbs.mkv /S` from the same cygwin prompt? (CACLS is a Windows utility; for this reson try to change into the directory that contains the relevant file to avoid issues with Cygwin/CACLS command line translations of slash and backslash).

**Comment by hasse69** [comment] 2019-08-19 15:02
@billziss-gh 
Actually, the funny thing here is that if rar2fs reports `100644` in `getattr` callback the status from `ls -l` in a cygwin window gives `-r--r--r--` on this particular system, which is also wrong of course.

**Comment by billziss-gh** [comment] 2019-08-19 15:15
@hasse69 this definitely suggests some mangling of permission bits. I am hoping that the output of `cacls` might shed a bit of light.

**Comment by Marabon** [comment] 2019-08-21 00:23
struct stat:
```
struct stat {
    st_dev = 0
   st_mode = 100600 (octal)
  st_nlink = 1
    st_ino = 0
    st_uid = 197609
    st_gid = 197609
   st_rdev = 0
   st_size = 864775589
 st_blocks = 1689016
st_blksize = 0
}
```
LS
```
$ ls -l 12.monkeys.s04e06.720p.web.x264-tbs.mkv
---------- 1 x x 864775589 Jun 23  2018 12.monkeys.s04e06.720p.web.x264-tbs.mkv

$ stat 12.monkeys.s04e06.720p.web.x264-tbs.mkv
  File: 12.monkeys.s04e06.720p.web.x264-tbs.mkv
  Size: 864775589       Blocks: 844508     IO Block: 65536  regular file
Device: bfb1559ch/3216070044d   Inode: 7743262778922486871  Links: 1
Access: (0000/----------)  Uid: (197609/   x)   Gid: (197609/   x)
Access: 2018-06-23 11:49:38.000000000 +0200
Modify: 2018-06-23 11:49:38.000000000 +0200
Change: 2018-06-23 11:49:38.000000000 +0200
 Birth: -

$ cacls 12.monkeys.s04e06.720p.web.x264-tbs.mkv /S
O:\12.monkeys.s04e06.720p.web.x264-tbs.mkv "D:P(A;;0x1f0198;;;S-1-5-21-1328609849-3804899598-2777500429-1001)(A;;0x120088;;;S-1-5-21-1328609849-3804899598-2777500429-1001)(A;;0x120088;;;WD)"
```

**Comment by billziss-gh** [comment] 2019-08-21 00:38
@Marabon thanks.

The `cacls` output suggests that there is indeed a problem with the permissions getting mangled/lost somehow. Notice that in the `D:P(A;;0x1f0198;...` part, the number `0x1f0198` describes the following permissions:

```
#define SYNCHRONIZE                      (0x00100000L)

#define DELETE                           (0x00010000L)
#define READ_CONTROL                     (0x00020000L)
#define WRITE_DAC                        (0x00040000L)
#define WRITE_OWNER                      (0x00080000L)

#define FILE_WRITE_ATTRIBUTES     ( 0x0100 )

#define FILE_WRITE_EA             ( 0x0010 )
#define FILE_READ_ATTRIBUTES      ( 0x0080 )

#define FILE_READ_EA              ( 0x0008 )
```

What we are missing is:

```
#define FILE_READ_DATA            ( 0x0001 )
```

Which would allow us to read the file data (according to the `0600` file mode).

This suggests a problem in how the FUSE layer translates permissions. So I now need to repro this somehow.

**Comment by Marabon** [comment] 2019-08-21 00:40
Let me know if there's anything you need from me, just be warned I might be techy, but I'm no where close to you guys' level, so you might have to provide instructions for advanced stuff.

**Comment by hasse69** [comment] 2019-08-21 05:51
@billziss-gh 
Just an observation/question. You say we are missing the `FILE_READ_DATA` bit, but I see a lot of write permission bits being set, but still what is presented from Cygwn is neither write nor read? Should we not at least see write access in the `ls -l` then? Or is there something like `FILE_WRITE_DATA` missing too?

**Comment by billziss-gh** [comment] 2019-08-21 10:25
@Marabon 
I believe I know the reason for the problem. Despite the annoying behavior this is not a bug and the system works as designed.

The problem is that your uid and gid are the same: `197609`. On UNIX the `uid` and `gid` are in a different namespace: even if the numeric `uid==gid` are the same the corresponding user and group can never be the same and UNIX considers the  permissions of the two separately. On Windows user and group "SID's" (Security Identifiers: the long `S-1-5-21-XXX-YYY-ZZZ` strings) are in the same namespace and it is possible to have a `SID` on Windows that acts as both user and group. Unfortunately in this case WinFsp considers the most restrictive permissions to be authoritative.

In more detail: your user and group SID are both `S-1-5-21-1328609849-3804899598-2777500429-1001`, which is translated to a `uid==gid` of `197609`. (The FUSE layer figures out your `uid` and `gid` automatically when you pass the `-o uid=-1,gid=-1` parameter).

Now because `uid==gid` and because `uid` and `gid` are drawn from the same namespace on Windows, [this rule](https://github.com/billziss-gh/winfsp/blob/v1.4/src/dll/posix.c#L471-L478) kicks in:

```C
    /* [PERMS]
     * What about the case where both owner and group are the same SID and
     * a chmod(1) request is made where the owner and the group permission
     * bits are different?. In this case, the most restrictive permissions
     * are chosen and assigned to both ACEs.
     */
    if (EqualSid(OwnerSid, GroupSid))
        OwnerPerm = GroupPerm = OwnerPerm & GroupPerm;
```

The result is that the `0600` permission becomes `0000`.

This is surprising and unfortunate, but I was not completely mad when I was putting in that logic. Rather I based this on the specification from SFU (Services For UNIX), which defined this behavior. Cygwin is compatible with SFU as far as I know.

So the solution for you is to only use `-o uid=-1` (without the `,gid=-1` part) or to use a group such as "Authenticated Users": `-o uid=-1,gid=11`.

**NOTE**: I am not sure under which circumstances a Windows account ends up with the same SID for its owner and primary group. I would have thought that should not happen under normal circumstances, but the Windows security model is way too complicated.

@hasse69 
Yes, there is a `FILE_WRITE_DATA` that is missing as well. Below are the full Windows file access rights from the relevant header file:

```
#define FILE_READ_DATA            ( 0x0001 )    // file & pipe
#define FILE_LIST_DIRECTORY       ( 0x0001 )    // directory

#define FILE_WRITE_DATA           ( 0x0002 )    // file & pipe
#define FILE_ADD_FILE             ( 0x0002 )    // directory

#define FILE_APPEND_DATA          ( 0x0004 )    // file
#define FILE_ADD_SUBDIRECTORY     ( 0x0004 )    // directory
#define FILE_CREATE_PIPE_INSTANCE ( 0x0004 )    // named pipe


#define FILE_READ_EA              ( 0x0008 )    // file & directory

#define FILE_WRITE_EA             ( 0x0010 )    // file & directory

#define FILE_EXECUTE              ( 0x0020 )    // file
#define FILE_TRAVERSE             ( 0x0020 )    // directory

#define FILE_DELETE_CHILD         ( 0x0040 )    // directory

#define FILE_READ_ATTRIBUTES      ( 0x0080 )    // all

#define FILE_WRITE_ATTRIBUTES     ( 0x0100 )    // all

#define FILE_ALL_ACCESS (STANDARD_RIGHTS_REQUIRED | SYNCHRONIZE | 0x1FF)

#define FILE_GENERIC_READ         (STANDARD_RIGHTS_READ     |\
                                   FILE_READ_DATA           |\
                                   FILE_READ_ATTRIBUTES     |\
                                   FILE_READ_EA             |\
                                   SYNCHRONIZE)


#define FILE_GENERIC_WRITE        (STANDARD_RIGHTS_WRITE    |\
                                   FILE_WRITE_DATA          |\
                                   FILE_WRITE_ATTRIBUTES    |\
                                   FILE_WRITE_EA            |\
                                   FILE_APPEND_DATA         |\
                                   SYNCHRONIZE)


#define FILE_GENERIC_EXECUTE      (STANDARD_RIGHTS_EXECUTE  |\
                                   FILE_READ_ATTRIBUTES     |\
                                   FILE_EXECUTE             |\
                                   SYNCHRONIZE)
```

**Comment by billziss-gh** [comment] 2019-08-21 10:26
BTW, I should really add this to the FAQ. It often trips people, including me.

**Comment by hasse69** [comment] 2019-08-21 18:56
@billziss-gh 
Well analyzed. We learn something new every day, but then we also tend to forget something as often :) Unless @Marabon has something to add I guess it is case closed.

**Comment by Marabon** [comment] 2019-08-21 23:27
Yeah I just started it without the uid and gid so I guess it defaulted to fetching my Windows IDs.
I suppose changing the behavior of that feature would defeat the purpose of that feature. :)

Anyways I'm happy we figured it out. :)

**Comment by billziss-gh** [comment] 2019-08-22 09:29
@Marabon I am glad this was explained. Closing.

**Closed by billziss-gh** 2019-08-22 09:29 UTC
