### ISSUE TITLE
PT sample with Windows Defender - file never gets a Close event.

### ISSUE THREAD

**Issue by alfaunits** [billziss-gh/winfsp#206] opened 2018-12-05 10:15 UTC
OS: W10 x64, 1703, latest WinFSP as of today.

Run PassThrough sample, mount any folder on any drive. Suppose we create a file, write any data to it and close (specifically I did a test with a C++ app that does fopen/fwrite/fclose). This does not occur with simply doing "echo test >test.dat".

Windows Defender reads the file, and the file never gets a Close. I suspected a caching issue, but the close does not arrive for an hour at least ;)

passthough -p C:\PassthroughPoint -m E:

C++ sample:
```
                    io_err = _wfopen_s(&pFile, "E:\\Test.dat", L"w+b");
                    if (io_err)
                    {
                        std::wcout << L"\nError " << io_err << L" occurred during fopen call on the file " << std::endl;
                    }
                    else
                        if (fwrite(buffer, 1024 * 128, 1, pFile) != 1)
                        {
                            std::wcout << L"\nError " << errno << L" occurred during write for the file " << std::endl;
                        }
                    if (!io_err) fclose(pFile);
```

**Comment by billziss-gh** [comment] 2018-12-05 19:53
The Windows OS will delay closing files indefinitely.

When an application calls `CloseHandle`, the file system is sent a CLEANUP message. But the file is not closed until it receives a CLOSE message, which is sent when the last reference to the file goes away. The Windows OS may delay this message for many reasons; one of the most common ones is caching.

Consider, as a simplified example, the common scenario where an application opens, reads and closes a file multiple times. If the file was truly closed and all its caches purged, the file would have to be re-read from disk every time. By delaying the close, the OS can keep the file's cache around and service all but the first READ from cache.

To convince yourself that there is no problem you can download a utility named [RAMMap](https://docs.microsoft.com/en-us/sysinternals/downloads/rammap). Try sending an "Empty Standby List" command and you will see all the missing CLOSE messages.

Finally and because some file systems cannot handle having CLOSE delayed indefinitely I have added the flag `FlushAndPurgeOnCleanup` in `FSP_FSCTL_VOLUME_PARAMS`. This will instruct the FSD to ask the OS to send those CLOSE calls in a more timely manner. Unfortunately this flag did not make it into passthrough, because it was added after the passthrough file system was created.

**Comment by alfaunits** [comment] 2018-12-05 20:02
I am aware of this. However, a close delayed for so long is a symptom
of a bug, not a feature.

You will not see this exhibited on NTFS, or with Windows Defender
disables (I reckon most other AVs would cause the problem).

I wrote a transpoarent encryption filter, 16 years now (the product is
still active). I remember a delayed close always being a cause for
alarm (as in "My driver has bug").

Often it is an interaction issue, especially with those pesky AVs :)

-- 


Kind regards, Dejan.

**Comment by alfaunits** [comment] 2018-12-05 20:09
Uhm... I forgot to mention. We set the FileInfoTimeout to 1000, so
that should mean no data cache? Hence, nothing to keep a reference.

I am puzzled though, I did not have the time to figure, but no file
data caching at all would mean Notepad cannot function, due to it
using memory mapping, which relies on the cache, yet it does.

**Comment by billziss-gh** [comment] 2018-12-06 00:45
@alfaunits please try RAMMap and "empty standby list" if you want to convince yourself that there is no bug.

Also use the `FlushAndPurgeOnCleanup` flag to see that the behavior will change. The FSD will actively ask Windows to release references:

- https://github.com/billziss-gh/winfsp/blob/v1.3/src/sys/file.c#L816
- https://github.com/billziss-gh/winfsp/blob/v1.3/src/sys/file.c#L950

There are many components in Windows that will keep references to files, even when the last handle is gone. The caching scenario was just a simplified example.

> I am puzzled though, I did not have the time to figure, but no file
data caching at all would mean Notepad cannot function, due to it
using memory mapping, which relies on the cache, yet it does.

Good catch. When memory mapped files are involved you get a form of "caching" regardless of what you set `FileInfoTimeout` as.

**Comment by alfaunits** [comment] 2018-12-06 10:23
Huh, that does force closes to happen (or happen much, much sooner).

We'll keep it in mind, at this time the slowdown is incredible with the flag on (in our code, based on PTFS, this is not likely to matter to PTFS)

**Comment by billziss-gh** [comment] 2018-12-06 22:17
> We'll keep it in mind, at this time the slowdown is incredible with the flag on 

Yes. The problem is that during CLEANUP, the FSD now asks Windows to `CcFlushCache` the file, which (potentially) results in WRITE's being sent to your file system. Next `CcUnitializeCacheMap` is also passed a `TruncateSize` of 0, which purges the (now flushed) cache. This has the desired effect of the Cc releasing its references to the file and therefore you get the CLOSE. But it also has negative effects: (1) you circumvent the lazy writing machinery and (2) your cache has to be reprimed on the next I/O.

(Of course this will not work if the file is memory-mapped. That is another can of worms.)

I hope you now see why I chose to **not** do this in the general case.

> I was just able to reproduce a case (vanilla PTFS executable, with no changes) where the file close does not arrive for over an hour, and no I/O occurs either.

Was this with the `FlushAndPurgeOnCleanup` on? Was the offending file memory-mapped?

**Comment by alfaunits** [comment] 2018-12-06 22:23
Was the file not supposed to not be cached, with FileInfoTimeout being 1000? Write is not the problem, the test is writing to a cached NTFS folder, it us exposing as a passthrough.

The test is using vanilla Ptfs, without the Flush flag.

**Comment by billziss-gh** [comment] 2018-12-06 22:39
> Was the file not supposed to not be cached, with FileInfoTimeout being 1000?

Yes. The file is not supposed to be cached.

> The test is using vanilla Ptfs, without the Flush flag. I cant tell if there is a memory mapping. Not from.amy app or us, perhaps from Windows Defender, I doubt it.

Actually Windows Defender may be using memory mapped files.

Here is interesting article that appears related to this discussion. The article mentions Microsoft Security Essentials and I am not certain of its relationship with Windows Defender, but it does point to memory mapped files being the culprit:
http://fsfilters.blogspot.com/2012/04/standby-list-and-storage.html

**Comment by alfaunits** [comment] 2018-12-07 10:42
Interesting, so it is the culprit of all those missing CLOSEes :(
We will reconsider Purging on close, and reimplement our code differently to mitigate the slowdown. The slowdown has nothing to do with the caching itself, it is just a byproduct of closes ariving often (just saying, this is not related to WinFSP, or the file systems, only our current implementation and needs)

**Comment by billziss-gh** [comment] 2018-12-07 21:40
@alfaunits understood.

I am wondering if WinFsp should include any functionality to evict those unused memory-mapped files after some time (e.g. by using `MmForceSectionClosed`):

- This would mean that WinFsp now imposes a policy that goes against what the Windows OS designers think, although Windows OS designers likely do not take the needs of user mode file systems into account.
- Even if we implemented such functionality into WinFsp it should be controllable by the file system, because WinFsp should not be in the business of implementing policy on its own.

In any case would it be fair to say that we should close this issue?

**Comment by alfaunits** [comment] 2018-12-08 08:31
A default policy would probably not be received well, but an availability of it prolly would.

Any clues why NTFS closes the file right away then? I am thinking it is an incorrect code or data returned somewhere.
When I return STATUS_FILE_LOCK_CONFLICT to Windows Defender, the file gets closed fast.

**Comment by billziss-gh** [comment] 2018-12-08 17:37
Interesting. Where do you return  `STATUS_FILE_LOCK_CONFLICT` from?

**Comment by billziss-gh** [comment] 2018-12-08 19:49
Hmmm... I just do not see how knowledge of this (`Read` returning `STATUS_FILE_LOCK_CONFLICT` affecting Windows Defender behavior) could be used in a general fashion.

BTW, how do you observe that memory-mapped files are closed early on NTFS? FileSpy?

On my system RAMMap shows many files open on the C: drive even after they are presumably gone.

**Comment by alfaunits** [comment] 2018-12-09 00:50
I observe it via Process Monitor.

**Comment by billziss-gh** [comment] 2018-12-09 06:59
I have found that Process Monitor is not reliable in reporting IRP's that actually make it to the FSD (or I do not know how to properly configure it to do so reliably). I strongly recommend the use of [FileSpy](http://www.zezula.net/en/fstools/filespy.html), which is a far superior tool for this purpose.

**Comment by alfaunits** [comment] 2018-12-09 09:39
I had no issue seeing correct IRPs to the WinFSP FSD. Albeit, the GUID based volume names are funny and hard to sift through n larger data sets, but for a test as minor as this one, it is easy. FileSpy would not see it differently I think, only the old FileMon (would display a drive letter, as it attaches to letters) but it won't run on W10 :)

The Close does come to the FSD, I did a printf() of the Close. So to summarize, in a PTFS sample, only changed to include Close() printf:
- With Windows Defender, a Close does not arrive for over an hour. We have a FS stress sample that can write over 2GB of data, no closes arrive.
- Without Windows Defender (real-time protection disabled), a Close arrives right away
- On NTFS, with WD RTP On, Close arrives right away. Right away = less than 2 seconds, in both cases.
- If I return STATUS_FILE_LOCK_CONFLICT from PTFS's Read() callback, the close comes right away. This is a modified PTFS sample test, where ALL Reads return SFLC (our stress test app only writes data, file is opened for write access only then, nothing else accesses files, so we can just return SFLC from Read() and be sure it is for WD only)
- Setting the purge on close flag for PTFS causes the closes to arrive right away in all cases.

I think for our purpose, we can rewrite the code to use the flag, and have 0 performance penalty.

I am more interested in the general question of "why is the Close not coming the same way it is coming for NTFS"?

**Comment by billziss-gh** [comment] 2018-12-10 20:54
> I am more interested in the general question of "why is the Close not coming the same way it is coming for NTFS"?

Unfortunately the NTFS source code is not available. In FastFat, where source code is available, `CcFlushCache` is called in a number of places during CLEANUP:

https://github.com/Microsoft/Windows-driver-samples/blob/master/filesys/fastfat/cleanup.c

> Setting the purge on close flag for PTFS causes the closes to arrive right away in all cases.

In this case I believe we can close this issue. Please reopen if you find otherwise.

**Closed by billziss-gh** 2018-12-10 20:54 UTC
