### ISSUE TITLE
Build s3fs with WinFSP layer?

### ISSUE THREAD

**Issue by chrilith** [billziss-gh/winfsp#143] opened 2018-02-05 13:02 UTC
Hi,

I [forked](https://github.com/chrilith/s3fs-fuse) `s3fs-fuse` and created a [pull-request](https://github.com/s3fs-fuse/s3fs-fuse/pull/712) to make s3fs compile under Cygwin.

My problem now is that it doesn't work. :) Using WinFSP 2017.2 on Microsoft Windows 10 Pro 10.0.14393.

First I had a "mount point in use" error. So, reading details from #75 I found that `stat()` calls may be modified. For testing purpose, I removed the whole check in `my_fuse_opt_proc()` (s3fs.cpp). After that, and changing `check_passwd_file_perms()` too to prevent "credentials file %s should not have others permissions.". The drive is now created with:
```
$  s3fs myBucket k: -o passwd_file=~/passwd.s3fs
```

But still, with "access denied" problem. So, I tried to append `-ouid=65792,gid=65792,umask=0`.

With a new error: "K: is unreachable. Invalid path name"
(this is translated, don't know the correct english version of this error).

Any clue?
Thanks!

----

Before submitting this issue please review this checklist. Ideally all checkmarks should be checked upon submitting. (Use an x inside square brackets like so: [x])

- [x] **Issue type**: Please consider posting only bug reports or enhancement requests. Questions are better in the [WinFsp Google Group](https://groups.google.com/forum/#!forum/winfsp). Please also consult the [WinFsp Frequently Asked Questions](https://github.com/billziss-gh/winfsp/wiki/Frequently-Asked-Questions).
- [x] **No Duplicate**: Ensure that your issue has not been filed before. (Check open and closed issues.)
- [x] **Description**: Provide a descriptive title and a detailed explanation of the problem you are experiencing (for a bug report) or you are trying to solve (for an enhancement request).
- [x] **Reproduce**: For bug reports provide detailed information on how to reproduce the problem. For enhancement requests you do not need to provide this information, unless you find it relevant.
- [x] **Behaviors**: Provide information on the expected and actual behaviors.
- [x] **Environment**: For bug reports provide information about your OS version and build (e.g. 10.0.14393) and WinFsp version and build (e.g. 2017.2 or 1.2.17341). For enhancement requests you do not need to provide this information, unless you find it relevant.

**Comment by billziss-gh** [comment] 2018-02-06 16:58
Apologies, I closed this by accident.

I have been traveling, but now I am back and will look into this more closely. Will try to build your s3fs fork and see what happens.

**Comment by billziss-gh** [comment] 2018-02-06 18:17
I am able to build s3fs using the steps you outlined [here](https://groups.google.com/forum/#!topic/winfsp/xXe6M_MoW8w) and some of my own changes:

- Patch the file `/usr/include/fuse/winfsp_fuse.h` to add the missing `(char *)` cast. (This is a CYGFUSE issue, which I will fix.)

- Build using the following:
    ```sh
    $ ./autogen.sh
    $ ./configure
    $ make
    ```

- Patch around the mount point checks (mount points do not exist on Windows/WinFsp prior to starting the file system):
    ```diff
    diff --git a/src/s3fs.cpp b/src/s3fs.cpp
    index aae4e89..e21c333 100644
    --- a/src/s3fs.cpp
    +++ b/src/s3fs.cpp
    @@ -4278,6 +4278,7 @@ static int my_fuse_opt_proc(void* data, const char* arg, int key, struct fuse_ar
        if(0 == mountpoint.size() && 0 == utility_mode){
          // save the mountpoint and do some basic error checking
          mountpoint = arg;
    +#if !defined(__CYGWIN__)
          struct stat stbuf;
    
          if(stat(arg, &stbuf) == -1){
    @@ -4309,6 +4310,7 @@ static int my_fuse_opt_proc(void* data, const char* arg, int key, struct fuse_ar
            }
            closedir(dp);
          }
    +#endif
          return 1;
        }
    ```

- I can see the file system returns `STATUS_ACCESS_DENIED` when passing the a double `-d` switch. Investigating.

**Comment by chrilith** [comment] 2018-02-06 18:45
Hi @billziss-gh,

Thank you for taking time to look at this.
Will try to help as much as I can, unfortunately the code is very big with all the curl/thread stuff. Not so easy to step into everything :).

Hopefully it is just a small communication issue between s3fs and WinFSP and not something related to more libs.

Anyway thank you again!

**Comment by billziss-gh** [comment] 2018-02-06 19:34
I think I have found the (first) problem.

The issue was that `s3fs_getattr` was returning a mode of `000` for the root directory, which means **regular file** with no permissions. Even with `-o umask=000` the returned mode was `0777`, which means regular file with full RWX permissions. WinFsp was failing because it expects that the root directory is a **directory** :)

The hackpatch below circumvents the issue, by faking the mount point uid, gid, mode (recall that in Windows/WinFsp the mountpoint does not exist).

```diff
diff --git a/src/s3fs.cpp b/src/s3fs.cpp
index aae4e89..747f314 100644
--- a/src/s3fs.cpp
+++ b/src/s3fs.cpp
@@ -4202,6 +4202,7 @@ static int set_mountpoint_attribute(struct stat& mpst)
   mp_gid  = getegid();
   mp_mode = S_IFDIR | (allow_other ? (is_mp_umask ? (~mp_umask & (S_IRWXU | S_IRWXG | S_IRWXO)) : (S_IRWXU | S_IRWXG | S_IRWXO)) : S_IRWXU);
 
+#if !defined(__CYGWIN__)
   S3FS_PRN_INFO2("PROC(uid=%u, gid=%u) - MountPoint(uid=%u, gid=%u, mode=%04o)",
          (unsigned int)mp_uid, (unsigned int)mp_gid, (unsigned int)(mpst.st_uid), (unsigned int)(mpst.st_gid), mpst.st_mode);
 
@@ -4220,6 +4221,9 @@ static int set_mountpoint_attribute(struct stat& mpst)
     return true;
   }
   return false;
+#else
+  return true;
+#endif
 }
 
 //
@@ -4280,6 +4284,7 @@ static int my_fuse_opt_proc(void* data, const char* arg, int key, struct fuse_ar
       mountpoint = arg;
       struct stat stbuf;
 
+#if !defined(__CYGWIN__)
       if(stat(arg, &stbuf) == -1){
         S3FS_PRN_EXIT("unable to access MOUNTPOINT %s: %s", mountpoint.c_str(), strerror(errno));
         return -1;
@@ -4309,6 +4314,10 @@ static int my_fuse_opt_proc(void* data, const char* arg, int key, struct fuse_ar
         }
         closedir(dp);
       }
+#else
+      memset(&stbuf, 0, sizeof stbuf);
+      set_mountpoint_attribute(stbuf);
+#endif
       return 1;
     }
 ```

Onto the next issue.

**Comment by billziss-gh** [comment] 2018-02-06 19:41
BTW, with this patch I am able to `cd` into the directory using Cygwin, but the file system segfaults when I issue `ls -l`. I do not have time to investigate this right now, but hopefully will have time for another look in a couple of hours.

**Comment by billziss-gh** [comment] 2018-02-06 22:18
I took some time to run s3fs under gdb. The program dies either with a segfault or silently whenever I try to list the root directory:

- Run s3fs with the following arguments: `-f -d billziss-rclone2 X: -o passwd_file=/cygdrive/c/Users/billziss/Desktop/PersonalAWS.cred -o umask=000`

- S3fs segfaults or dies silently. The problem is likely with the `list_bucket` function.

- The problem does not appear to be related to WinFsp. In one case the segfault appeared to be deep within the guts of Curl+OpenSSL. (Unfortunately I lost the backtrace.)

**Comment by gaul** [comment] 2018-02-06 22:48
You can try unencrypted HTTP to see if it works around the crypto issues via:  `s3fs -o url=http://s3.amazonaws.com`

**Comment by billziss-gh** [comment] 2018-02-06 23:11
@gaul Unfortunately this did not resolve the issue.

The program appears to be dying because of `SIGABRT`. The suspect backtrace when running with `-o url=http://s3.amazonaws.com` is:

```
Thread 11 (Thread 3680.0x8b0):
#0  0x00007ffe67156154 in ntdll!ZwWaitForSingleObject () from /cygdrive/c/WINDOWS/SYSTEM32/ntdll.dll
#1  0x00007ffe63d33acf in WaitForSingleObjectEx () from /cygdrive/c/WINDOWS/System32/KERNELBASE.dll
#2  0x0000000180121288 in sig_send(_pinfo*, siginfo_t&, _cygtls*) () from /usr/bin/cygwin1.dll
#3  0x000000018011db0e in _pinfo::kill(siginfo_t&) () from /usr/bin/cygwin1.dll
#4  0x000000018011dfc2 in kill0(int, siginfo_t&) () from /usr/bin/cygwin1.dll
#5  0x000000018011e20a in raise () from /usr/bin/cygwin1.dll
#6  0x000000018011e4cf in abort () from /usr/bin/cygwin1.dll
#7  0x0000000180156db5 in dlmalloc () from /usr/bin/cygwin1.dll
#8  0x0000000180158946 in dlrealloc () from /usr/bin/cygwin1.dll
---Type <return> to continue, or q <return> to quit---
#9  0x00000001800ba79f in realloc () from /usr/bin/cygwin1.dll
#10 0x000000018011973b in _sigfe () from /usr/bin/cygwin1.dll
#11 0x00000003f6dc2745 in cygcurl-4!Curl_saferealloc () from /usr/bin/cygcurl-4.dll
#12 0x00000003f6d98152 in cygcurl-4!Curl_add_buffer () from /usr/bin/cygcurl-4.dll
#13 0x00000003f6d98253 in cygcurl-4!Curl_add_bufferf () from /usr/bin/cygcurl-4.dll
#14 0x00000003f6d9904d in cygcurl-4!Curl_http () from /usr/bin/cygcurl-4.dll
#15 0x00000003f6dbcee6 in cygcurl-4!curl_multi_remove_handle () from /usr/bin/cygcurl-4.dll
#16 0x00000003f6dbda9d in cygcurl-4!curl_multi_perform () from /usr/bin/cygcurl-4.dll
#17 0x00000003f6db3d7d in cygcurl-4!curl_easy_perform () from /usr/bin/cygcurl-4.dll
#18 0x0000000100424f1a in S3fsCurl::RequestPerform (this=this@entry=0x325c070) at curl.cpp:2040
#19 0x0000000100433d4d in S3fsCurl::HeadRequest (this=this@entry=0x325c070,
    tpath=0x600228ae8 "/.git", meta=...) at curl.cpp:2711
#20 0x00000001004085c2 in get_object_attribute (path=<optimized out>, path@entry=0x819370 "/.git",
    pstbuf=pstbuf@entry=0x325c410, pmeta=pmeta@entry=0x0, overcheck=overcheck@entry=true,
    pisforce=0x325bf86, pisforce@entry=0x0, add_no_truncate_cache=<optimized out>,
    add_no_truncate_cache@entry=false) at s3fs.cpp:479
#21 0x000000010040922d in check_object_access (path=path@entry=0x819370 "/.git", mask=mask@entry=0,
    pstbuf=pstbuf@entry=0x325c410) at s3fs.cpp:597
#22 0x0000000100409e5d in s3fs_getattr (path=0x819370 "/.git", stbuf=0x325c410) at s3fs.cpp:847
#23 0x00007ffe54e6ff07 in ?? ()
   from /cygdrive/c/Users/billziss/Projects/ext/s3fs-fuse/src/winfsp-x64.dll
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

As before the issue appears to have something to do with memory management inside Curl (notice that `realloc` calls `abort` if this backtrace is to be trusted).

BTW, the `.git` accesses are from my git prompt which Cygwin bash tries to run. This suggests that the issue is not tied to listing directories, but probably a symptom of a memory management problem, such as accessing memory after `free`, etc.

**Comment by gaul** [comment] 2020-02-03 08:23
Any updates on this?  It would be great to get s3fs support on Windows.  Please let me know if we can help from the s3fs side.

**Comment by billziss-gh** [comment] 2020-02-03 18:31
@gaul unfortunately I only have time to maintain WinFsp and do not have time to troubleshoot problems with s3fs, a code base that I am not familiar with.

I am happy to support anyone that wants to port s3fs to Windows however.

**Comment by chrilith** [comment] 2020-02-03 20:05
@gaul as for myself, I'm not using AWS anymore and as stated in a previous message the codebase is too dense for me to get into.

Thank you to all of you for your help anyway!

**Closed** 2021-11-18 16:36 UTC
