### ISSUE TITLE
How to implement STATUS_PENDING

### ISSUE THREAD

**Issue by JohnOberschelp** [billziss-gh/winfsp#108] opened 2017-09-29 02:08 UTC
I am porting my file system to run under **WinFsp**, and it uses `STATUS_PENDING` for IO. I am struggling to figure out how to send my `FspFileSystemSendResponse( FileSystem, Response);`s for `Read`, `Write`, and `ReadDirectory`.
In particular, the struct `FSP_FSCTL_TRANSACT_RSP` seems to be a tricky beast.

Your **MemFS** is a terrific sample file system, as it is a simple, small, almost-complete file system that doesn’t rely on **NTFS** for anything. So, though I would be happy with just some direction, ideally I would ask how to add `DEBUGTEST()`-style `STATUS_PENDING` to **MemFS** `Read`, `Write`, and `ReadDirectory`, as I think this would be a great addition to your test coverage.

**Comment by billziss-gh** [comment] 2017-09-29 04:22
> I am struggling to figure out how to send my FspFileSystemSendResponse( FileSystem, Response);s for Read, Write, and ReadDirectory.

I think you have identified an area where tests are lacking.

In theory here is what you would have to do, e.g. for a Write (untested):

```C
FSP_FSCTL_TRANSACT_RSP ResponseBuf;

memset(&ResponseBuf, 0, sizeof ResponseBuf);
ResponseBuf.Size = sizeof ResponseBuf;
ResponseBuf.Kind = FspFsctlTransactWriteKind;
ResponseBuf.Hint = Request.Hint;                        // IRP that is being completed
ResponseBuf.IoStatus.Status = STATUS_SUCCESS;
ResponseBuf.IoStatus.Information = BytesTransferred;    // bytes written
ResponseBuf.Rsp.Write.FileInfo = FileInfo;              // FileInfo of file after Write

FspFileSystemSendResponse(FileSystem, &ResponseBuf);
```

> So, though I would be happy with just some direction, ideally I would ask how to add DEBUGTEST()-style STATUS_PENDING to MemFS Read, Write, and ReadDirectory, as I think this would be a great addition to your test coverage.

This is a great idea!

- [`DEBUGTEST`](https://github.com/billziss-gh/winfsp/blob/v1.1/src/sys/driver.h#L124-L133) is currently an FSD (kernel-only) macro. It relies on the FSD function [`DebugRandom`](https://github.com/billziss-gh/winfsp/blob/v1.1/src/sys/debug.c#L293-L309). It should be easy to port to user mode (or we can just use C's `random()` with a lock around it).

- Presumably `Read`, `Write`, and `ReadDirectory` should be written in such a way so that some times (based on a `DEBUGTEST` percentage) they return `STATUS_PENDING` rather than `STATUS_SUCCESS`. When that happens a new thread or thread pool work item should be scheduled just for the purpose of delivering the I/O response using `FspFileSystemSendResponse`.

- As this is for testing during debug builds only, we should keep it as simple as possible and not worry about performance. One gotcha is that if any threads/work items are scheduled we should wait for them to finish before the `FileSystem` object gets deleted. This management might actually make things a bit complicated.

So if you are willing to try it, I will be happy to help.

**Comment by JohnOberschelp** [comment] 2017-10-02 00:42
I'm giving it a go, but I am already stumped. How do I access `Request` needed to fill in the `Request.Hint`? Is `Request` in your code above a `FSP_FSCTL_TRANSACT_REQ`?

**Comment by billziss-gh** [comment] 2017-10-02 03:23
You should be able to get the `Request` using the following code:

```C
FSP_FSCTL_TRANSACT_REQ *Request = FspFileSystemGetOperationContext()->Request;
```

More information:

https://github.com/billziss-gh/winfsp/blob/v1.1/inc/winfsp/winfsp.h#L953-L963

**Comment by JohnOberschelp** [comment] 2017-10-09 22:24
I put in a pull request with the code to support 3 new parameters to control slowdown and STATUS_PENDING testing. I apologize in advance for my `ioThreadsRunning` code which is at best barbaric, possibly cleaning up in the wrong place, and possibly flat out wrong. But it does seem to work with my favorite test case, FirefoxPortable installs. #110

**Comment by billziss-gh** [comment] 2017-10-09 22:34
Thanks for the PR! I will have a look at it some time tomorrow, as it is unlikely that I will find time today.

**Comment by billziss-gh** [comment] 2017-10-25 03:06
@JohnOberschelp I am wondering if you had the chance to see my comments on your PR.

**Comment by JohnOberschelp** [comment] 2017-10-26 01:17
Oops! I was waiting for your comments here. N00b mistake. Just wrote to #110

**Comment by billziss-gh** [comment] 2017-10-26 15:50
No problem. I also do not fully understand when GitHub alerts someone about a conversation. I will try to comment on both this issue and the PR in the future.

**Comment by billziss-gh** [comment] 2017-11-02 05:10
Reposting here from #110 in case you do not get notifications again:

I have merged your changes into the [pvt-slowio](https://github.com/billziss-gh/winfsp/tree/pvt-slowio) branch. I will test them locally and with AppVeyor and then merge into [master](https://github.com/billziss-gh/winfsp/tree/master).

Unfortunately AppVeyor builds have been fragile in the last few days and I am not sure why. As mentioned there was a major change in how "Query Directory" is handled, however I got a few green builds after that change was introduced and before builds started going red. This may mean that it may be related to a change in the AppVeyor environment, etc.

[AppVeyor builds execute hundreds of test cases and tens of thousands of individual tests; if just one of these individual tests fails, the whole build fails.]

I need to figure out what the problem is and resolve it. I am also away next week, so probably it will be a couple of weeks before I manage to merge this into [master](https://github.com/billziss-gh/winfsp/tree/master).

**Comment by billziss-gh** [comment] 2017-11-03 16:08
@JohnOberschelp I have been able to test your `STATUS_PENDING` changes with `winfsp-tests` and `fsx` and I am fairly confident that things work as should. I have merged your changes into the master branch. Thank you again for the great work!

**Closed by billziss-gh** 2017-11-03 16:08 UTC
