### ISSUE TITLE
Drive silently fails to mount when running as administrator

### ISSUE THREAD

**Issue by TomKuhn** [billziss-gh/winfsp#194] opened 2018-10-10 23:10 UTC
## Bug Report

When running memfs example and setting the mount point to a drive, e.g Z: then it fails to mount the drive when running as administrator. When running as non-administrator, the drive shows up in explorer just fine

### How to Reproduce

Run the memfs example as administrator on Windows 10 Version 1803

### Behaviors

Expected drive letter to show up in explorer. Call to "Mount" on the FileSystemHost succeeds.
Interestingly setting the mount point to a folder on an existing drive works, e.g D:\MemFS

### Environment

Windows 10 build 1803
winfsp-x64.dll, winftp-msil.dll version 1.3.18160.0

**Comment by billziss-gh** [comment] 2018-10-11 01:11
This is by design on Windows and not a true failure. The drive is mounted, but you cannot see it from a non-elevated Explorer.

When you create a drive as an Administrator (elevated) it is created in a drive namespace that is different from the one you see when you are not acting as Administrator (non-elevated). The usual scenario where this happens is starting a file system from an Administrator command-prompt and trying to access it from the Windows Explorer (which runs non-elevated).

For the full details read the remarks in the [`DefineDosDevice`](https://docs.microsoft.com/en-us/windows/desktop/api/fileapi/nf-fileapi-definedosdevicew) documentation.

> Starting with Windows XP, this function creates a device name for a caller that is not running in the "LocalSystem" context in its own Local MS-DOS device namespace. If the caller is running in the "LocalSystem" context, the function creates the device name in the Global MS-DOS device namespace. For more information, see Defining an MS DOS Device Name and File Names, Paths, and Namespaces.

If you want to create drives that are globally visible you must create them from the SYSTEM account (i.e. run your file system as a service). The easiest way to do this is to use the [WinFsp Launcher](https://github.com/billziss-gh/winfsp/wiki/WinFsp-Service-Architecture).

**Comment by billziss-gh** [comment] 2018-10-11 01:13
This link (accessible from `DefineDosDevice`) has the full details:

https://docs.microsoft.com/en-us/windows/desktop/FileIO/defining-an-ms-dos-device-name

**Comment by billziss-gh** [comment] 2018-10-16 19:31
@TomKuhn I am closing this. Please reopen if you find that my comments above did not address your issue.

**Closed by billziss-gh** 2018-10-16 19:31 UTC
