### ISSUE TITLE
Winfsp should be installable on Windows 10 with system restore disabled

### ISSUE THREAD

**Issue by Sharky444** [billziss-gh/winfsp#295] opened 2020-04-01 20:18 UTC
Currently it's not possible to install Winfsp on Windows 10 with system restore disabled on that system. The installation will stop with a device cannot be accessed message, which is very confusing for the vast majority of users.

I've created a verbose log of the installer and saw that it tries to create a system restore access point, but fails since it doesn't check if system restore is enabled on that system.

Preferably a warning should be displayed that the access point could not be created, with the option for the user to proceed anyway..

If think you have to force the user to install WinFSP only when system restore is enabled, then please give a clear error message informing the user he has to turn it on again. 

I don't use System Restore, because it's very unreliable. I'm using automatic system backups twice a day instead.

**Comment by Rootax** [comment] 2020-05-02 11:59
I've system restore disabled, and I installed WinFSP just fine...

**Comment by billziss-gh** [comment] 2020-05-04 21:56
@Sharky444 I cannot reproduce this problem locally.

Can you please post the log of the installer to see what the problem might be? Thanks.

**Comment by billziss-gh** [comment] 2020-05-05 21:58
Closing this. Please reopen if you find that the problem persists.

**Closed by billziss-gh** 2020-05-05 21:58 UTC
