### ISSUE TITLE
WinFSP Performances

### ISSUE THREAD

**Issue by efeat** [billziss-gh/winfsp#50] opened 2017-02-09 19:01 UTC
Dear @billziss-gh,

WinFsp has goob performances, according to your article https://github.com/billziss-gh/winfsp/wiki/WinFsp-Performance-Testing.

I've made few tests on memfs and passthrough file systems and my conclusions are nearly yours.

I've also made standard actions tests (not only benchmark ones) such as running a program, compiling source codes, unzip archives, fetch/pull data into the file system... They are commons actions that many programs do.

I've also made something similar on Fuse (installed on Debian Jessie).
Here are my conclusions about "commons" actions:

- memfs using Fuse has no impact 
- passthrough using Fuse has no impact 
- memfs using WinFsp has no impact 
- passthrough using WinFsp is twice slower than ntfs

When I say "no impact", it means that these actions run in the same delay on a Fuse or WinFsp FS than on a standard FS (ext4 or ntfs)

First of all, have you ever made such tests and if so, do you confirm my **brief** conclusion.

Secondly, even if this is a good performance for a user mode FS, do you think that the FastIO support could increase the passthrough performance with WinFsp ? Could it becomes as fast as ntfs ?

Best Regards

**Comment by billziss-gh** [comment] 2017-02-09 20:32
Hey, @efeat.

> I've also made standard actions tests (not only benchmark ones) such as running a program, compiling source codes, unzip archives, fetch/pull data into the file system... They are commons actions that many programs do.

If you ever package these tests in a way that they can be used by other file systems, I would love to see them and perhaps incorporate them into my own test suites.

> - memfs using Fuse has no impact
> - passthrough using Fuse has no impact

Here I am assuming that you mean your own "memfs" running on FUSE. Do you also mean your own "passthrough" running on FUSE?

> - memfs using WinFsp has no impact
> - passthrough using WinFsp is twice slower than ntfs

Here I am assuming that you mean the "memfs" and "passthrough" file systems that ship with WinFsp (RC2).

I suspect that the primary reason that you see this performance difference is that the MEMFS file system enables the NTOS cache manager, whereas the passthrough file system does not. [File data on a passthrough file system are **not** cached, only metadata are.]

Caching in WinFsp is controlled through the `FileInfoTimeout` value in `FSP_FSCTL_VOLUME_PARAMS`. A value of `0` means no caching. A value of `1000` means to cache file metadata (**not** data) for 1000ms (milliseconds). A value of `-1` means "infinite" caching of file metadata and also enables full caching of data.

Passthrough could be modified to enable full caching by changing the value of `FileInfoTimeout` to `-1`. If this is done files in the underlying file system (NTFS) should probably be opened using `FILE_FLAG_NO_BUFFERING` and written in increments of the NTFS allocation unit (usually 4096 on modern systems) to avoid double buffering of files within the NTOS cache manager.

For testing purposes you can probably just set the passthrough `FileInfoTimeout` to `-1` and rerun your benchmarks. Keep in mind that because files are now double-cached memory pressure will increase and caching will not work as well. But this may not matter if you run this test on a box with lots of memory. [Disclaimer: I have not tested passthrough with a `FileInfoTimeout` of `-1`.]

A final note: when running those tests make sure the driver verifier is off. The driver verifier kills WinFsp performance.

**Comment by efeat** [comment] 2017-02-13 10:55
Hi @billziss-gh,

> If you ever package these tests in a way that they can be used by other file systems, I would love to see them and perhaps incorporate them into my own test suites.

My tests are not packaged but of course I will keep that in mind and share them.

> Here I am assuming that you mean your own "memfs" running on FUSE. Do you also mean your own "passthrough" running on FUSE?

Yes.

> Here I am assuming that you mean the "memfs" and "passthrough" file systems that ship with WinFsp (RC2)

Yes. I've also test the memfs packaged with RC1 and a passthrough I've found in one of your Github repositories before you've moved it into RC2.
Results are the same for RC1 & RC2.

> A final note: when running those tests make sure the driver verifier is off. The driver verifier kills WinFsp performance.

Verifier was off.

> Passthrough could be modified to enable full caching by changing the value of FileInfoTimeout to -1 ...

I've tryed it, but unfortunatly I may have done an incorrect modification.
I've modified passthough.c @Line 684:

> VolumeParams.FileInfoTimeout = -1;//1000;

But then the filesystem was not working so fine.
One of my test uses "subversion" (because the svn client uses a sqlite database).
Here is the result of a checkout:

`time svn co https://xxxxxx
svn: E200030: sqlite[S10]: disk I/O error
svn: E200030: Additional errors:
svn: E200030: sqlite[S10]: disk I/O error`

An other test uses maven to compile a simple java project.
The maven build failed with an "access denied" error.

After that I've changed all CreateFileW calls on the underlying file system to add the FILE_FLAG_NO_BUFFERING (4 calls changed, I did not change the CreateFileW call for the log file).
It was then worst: I was unable to create any directory on the file system.

![mkdir-error](https://cloud.githubusercontent.com/assets/25483919/22880172/7c9a88c2-f1e1-11e6-8841-9a0eb9e8fc92.png)
The error message is:
`Unable to create directory "foobar": Invalid Argument`

As it's said here https://support.microsoft.com/en-us/help/99794/info-file-flag-write-through-and-file-flag-no-buffering 

> buffer addresses must be aligned on disk sector boundaries in memory

We may need to do something a bit more complicated ?
Did I've done something wrong ?


Best Regards

**Comment by billziss-gh** [comment] 2017-02-13 17:58
Hi, @efeat.

>> Passthrough could be modified to enable full caching by changing the value of FileInfoTimeout to -1 ...
> I've tryed it, but unfortunatly I may have done an incorrect modification.
> I've modified passthough.c @Line 684:
> 
> VolumeParams.FileInfoTimeout = -1;//1000;
> But then the filesystem was not working so fine.

I think your modification is fine. It is just that passthrough has not been tested with a `FileInfoTimeout` of -1. I will look into modifying it to add this enhancement, because it would let us get good benchmarks of a file system running on top of NTFS.

**Comment by efeat** [comment] 2017-02-14 08:36
Hi @billziss-gh ,

Good news :)

Thanks

**Comment by billziss-gh** [comment] 2017-02-14 17:59
Hey, @efeat.

I looked into modifying passthrough to use `FileInfoTimeout==-1` and `FILE_FLAG_NO_BUFFERING` yesterday. Unfortunately I have hit a serious problem, which I document here:

http://www.osronline.com/showthread.cfm?link=282037

The problem is that Windows crashes inside the **NTFS** driver while executing `ReadFile` from the passthrough file system. [This does not always happen, but it does happen under specific circumstances.] While it is not WinFsp that directly causes this problem, the combination of WinFsp and NTFS can cause it.

There is an easy workaround for the problem as described in the above mentioned link: implement the passthrough `Read` operation by reading into a separate buffer and then copy that buffer into the buffer supplied by `Read` (i.e. double buffering). I am not happy with this solution, but it may be the best one available. I may even implement a special flag in WinFsp's `FSP_FSCTL_VOLUME_PARAMS` to have the WinFsp DLL do it automatically for file systems that need it.

Let me re-iterate that this problem does not happen with passthrough as it ships today, but it can be triggered if passthrough is modified to use `FileInfoTimeout==-1` and `FILE_FLAG_NO_BUFFERING`.

**Comment by efeat** [comment] 2017-02-20 10:04
Hi @billziss-gh ,

Thank you for that work.
Double buffering may not be a good solution.

As you told in that thread (https://groups.google.com/forum/#!topic/dokan/BoLxl5p_fQQ) the WinFsp architecture must be the first priority, before the performance.

Take your time, I'am not in hurry :)

**Comment by billziss-gh** [comment] 2017-02-25 02:17
Hi @efeat,

I have modified WinFsp to fix the issue discovered by modifying the passthrough file system to open files with `FILE_FLAG_NO_BUFFERING`. See issue #55.

With this fix in place I modified passthrough to use `FileInfoTimeout==-1` and `FILE_FLAG_NO_BUFFERING`. The modified passthrough file system passes the tests described in the [WinFsp tutorial](https://github.com/billziss-gh/winfsp/wiki/WinFsp-Tutorial#testing-the-file-system).

I also run the `fsbench` `rdwr_cc_{read,write}_page_test` tests against NTFS and the modified passthrough file system:

<img width="601" alt="screen shot 2017-02-24 at 5 41 16 pm" src="https://cloud.githubusercontent.com/assets/15330948/23326918/b18cc9ac-fab8-11e6-814c-3a1d70cf8290.png">

From this you can see that NTFS (drive C:) is faster than the modified passthrough (drive Z:), but within the same order of magnitude (NTFS: 23% read faster, 30% write faster). As explained in the [WinFsp Performance Testing](https://github.com/billziss-gh/winfsp/wiki/WinFsp-Performance-Testing) document, the difference is likely due to *FastIo*, which WinFsp does not currently implement.

For comparison I also run the same tests on the unmodified passthrough file system:

<img width="599" alt="screen shot 2017-02-24 at 5 46 01 pm" src="https://cloud.githubusercontent.com/assets/15330948/23326975/8848cbda-fab9-11e6-9dc4-47d599193014.png">

From this you can see that NTFS (drive C:) is considerably faster than the unmodified passthrough (drive Z:) (NTFS: 81% read faster, 81% write faster). This is explained because the unmodified passthrough file system does not use the cache manager (directly).

So the takeaway here is: always enable the cache manager (by using `FileInfoTimeout==-1`) if you can. The usual reason not to use the cache manager is if you have coherency issues in your file system.

Despite these results I will not be releasing the modified version of the passthrough file system. The reason is that the passthrough file system (as it currently stands) is actually not a good candidate for use with the cache manager, because the cache manager keeps files open for long periods thus impending concurrent deletes and renames.

[Note to self: perhaps there are ways to work around this issue by using `CreateFileMappingW` to keep a file mapping open, but with all file handles closed. All I/O should be done through the file mapping rather than `ReadFile` / `WriteFile` in this case. Gotchas: how to handle file size changes and how to handle files with zero size? ].

In case you are interested here is the patch I used over the existing passthrough file system:

    diff --git a/tst/passthrough/passthrough.c b/tst/passthrough/passthrough.c
    index 2eef2a4..bc78e6a 100644
    --- a/tst/passthrough/passthrough.c
    +++ b/tst/passthrough/passthrough.c
    @@ -188,7 +188,17 @@ static NTSTATUS Create(FSP_FILE_SYSTEM *FileSystem,
             FileAttributes |= FILE_ATTRIBUTE_DIRECTORY;
         }
         else
    +    {
    +        if (GrantedAccess & FILE_APPEND_DATA)
    +        {
    +            GrantedAccess &= ~FILE_APPEND_DATA;
    +            GrantedAccess |= FILE_WRITE_DATA;
    +        }
    +        if (GrantedAccess & FILE_WRITE_DATA)
    +            GrantedAccess |= FILE_READ_DATA;
    +        CreateFlags |= FILE_FLAG_NO_BUFFERING;
             FileAttributes &= ~FILE_ATTRIBUTE_DIRECTORY;
    +    }
 
         if (0 == FileAttributes)
             FileAttributes = FILE_ATTRIBUTE_NORMAL;
    @@ -228,6 +238,21 @@ static NTSTATUS Open(FSP_FILE_SYSTEM *FileSystem,
         if (CreateOptions & FILE_DELETE_ON_CLOSE)
             CreateFlags |= FILE_FLAG_DELETE_ON_CLOSE;
 
    +    if (CreateOptions & FILE_DIRECTORY_FILE)
    +    {
    +    }
    +    else
    +    {
    +        if (GrantedAccess & FILE_APPEND_DATA)
    +        {
    +            GrantedAccess &= ~FILE_APPEND_DATA;
    +            GrantedAccess |= FILE_WRITE_DATA;
    +        }
    +        if (GrantedAccess & FILE_WRITE_DATA)
    +            GrantedAccess |= FILE_READ_DATA;
    +        CreateFlags |= FILE_FLAG_NO_BUFFERING;
    +    }
    +
         FileContext->Handle = CreateFileW(FullPath,
             GrantedAccess, FILE_SHARE_READ | FILE_SHARE_WRITE | FILE_SHARE_DELETE, 0,
             OPEN_EXISTING, CreateFlags, 0);
    @@ -681,13 +706,14 @@ static NTSTATUS PtfsCreate(PWSTR Path, PWSTR VolumePrefix, PWSTR MountPoint, UIN
         VolumeParams.SectorsPerAllocationUnit = 1;
         VolumeParams.VolumeCreationTime = ((PLARGE_INTEGER)&CreationTime)->QuadPart;
         VolumeParams.VolumeSerialNumber = 0;
    -    VolumeParams.FileInfoTimeout = 1000;
    +    VolumeParams.FileInfoTimeout = -1;
         VolumeParams.CaseSensitiveSearch = 0;
         VolumeParams.CasePreservedNames = 1;
         VolumeParams.UnicodeOnDisk = 1;
         VolumeParams.PersistentAcls = 1;
         VolumeParams.PostCleanupWhenModifiedOnly = 1;
         VolumeParams.PassQueryDirectoryPattern = 1;
    +    VolumeParams.AlwaysUseDoubleBuffering = 1;
         VolumeParams.UmFileContextIsUserContext2 = 1;
         if (0 != VolumePrefix)
             wcscpy_s(VolumeParams.Prefix, sizeof VolumeParams.Prefix / sizeof(WCHAR), VolumePrefix);

**Comment by efeat** [comment] 2017-02-27 13:25
Hi @billziss-gh,

Thanks for these investigations and that patch.
I've tested it on RC4 & Windows 7 Pro and had few problems (same issues than my patch).

For example:

`time svn co https://xxxxxx svn: E200030: sqlite[S10]: disk I/O error svn: E200030: Additional errors: svn: E200030: sqlite[S10]: disk I/O error`

I don't think we would need some more investigations about that.
The goal of these tests was to get an idea about WinFsp global performances which are pretty good.

I'am actually working on a mixed solution between memfs and passthrough (FileNode tree will stay into memory, but content file data is flushed to the disk) as a personal getting started of WinFsp.

Unfortunatly it's still not stable, but tests such as compile, exec, unzip ... seems to be really good, better than passthrough (maybe that's why it's unstable too :)).

**Comment by billziss-gh** [comment] 2017-03-10 23:17
Hi @efeat and apologies for my very late response.

> I'am actually working on a mixed solution between memfs and passthrough (FileNode tree will stay into memory, but content file data is flushed to the disk) as a personal getting started of WinFsp.
>
> Unfortunatly it's still not stable, but tests such as compile, exec, unzip ... seems to be really good, better than passthrough (maybe that's why it's unstable too :)).

This is a pretty good idea and I am happy to help you troubleshoot if you want to share some more information about any issues you are experiencing.

In any case, if you think that your questions/concerns have been addressed, I will go ahead and close this issue.

**Closed** 2017-03-15 16:44 UTC

**Comment by efeat** [comment] 2017-03-17 16:16
Hi @billziss-gh,

Of course, this issue can be closed.

Best Regards

**Comment by billziss-gh** [comment] 2017-03-17 16:31
Thank you!

**Comment by timofonic** [comment] 2018-02-02 06:31
@billziss-gh Anyway...

What's current performance comparison these days?

**Comment by billziss-gh** [comment] 2018-02-02 07:23
@timofonic I believe WinFsp performance to be generally good, especially when using the NTOS Cache Manager. Are you experiencing otherwise?

**Comment by billziss-gh** [comment] 2018-02-02 07:38
I should add that the information in the [Performance](https://github.com/billziss-gh/winfsp/wiki/WinFsp-Performance-Testing) document is still valid.

That document is about MEMFS, which is the reference file system for WinFsp. This particular issue is about the passthrough file system, which is an example file system written for a tutorial and was never optimized.
