### ISSUE TITLE
Beginners need a simple tutorial

### ISSUE THREAD

**Issue by gmxyb** [billziss-gh/winfsp#33] opened 2017-01-19 12:40 UTC
Thanks!

**Comment by billziss-gh** [comment] 2017-01-19 19:52
Thanks for the good suggestion.

Originally MEMFS was meant to be the "sample", but I recognize that it has grown complicated as it is now used for testing all WinFsp features (including many which some user mode file systems do not need).

**Comment by billziss-gh** [comment] 2017-01-20 21:41
Ok, here is a simple "passthrough" file system in less than 1000 lines of code:

https://github.com/billziss-gh/winfsp/blob/53a4bdc47818c80b9052336ec85ef537d54e380c/tst/passthrough/passthrough.c

The file system implements basic Windows file system functionality:

- Query volume information.
- Open, create, close, delete files and directories.
- Query and set file and directory information.
- Query and set security information (ACL's).
- Read and write files.
- Memory mapped I/O.
- Directory change notifications.
- Lock and unlock files.
- Opportunistic locks.

It does not implement the following functionality (which WinFsp supports):

- Open, create, close, delete, query named streams.
- Reparse points with special support for symbolic links.

The file system has received some minimal testing. I intend to test it more fully using the WinFsp test suites in the coming days. I am also writing at the same time a tutorial based on this file system, which should hopefully help beginners with WinFsp.

NOTE: This file system is currently in the pvt-passthru branch, but my current intent is to merge with the release/1.0 branch.

**Comment by gmxyb** [comment] 2017-01-21 01:00
Thanks a lot!

**Comment by billziss-gh** [comment] 2017-01-21 01:50
You are welcome.

BTW, once I am done testing it, I will change the license of the passthrough file system to BSD or other liberal license so that others can use it as a basis without restrictions.

**Comment by gmxyb** [comment] 2017-01-22 05:14
I compiled the passthrough in VS2015, but it not work.
-------------
passthrough-x86.exe -d -1 -D - -p D:\MyDir -m Z:
passthrough -p D:\!MyDownLoads -m Z:
The service passthrough has been started.
-------------
Then I open explorer, passthrough-x86.exe failure and exit.
-------------
Windows EventLog:

C:\Windows\syswow64\USER32.dll
Error Code: 0xc0000005
Error Offset: 0x0005103c

**Comment by gmxyb** [comment] 2017-01-22 05:18
I run passthrough-x86.exe again, the driver "Z:" can not mount and display.

**Comment by billziss-gh** [comment] 2017-01-22 06:19
I am assuming that you have the WinFsp 2017 RC1 installed.

Can you run it through the Visual Studio debugger and see where it fails?

BTW, I have only tested the x64 version of it so far (and only minimal testing as I just wrote this file system).

**Comment by billziss-gh** [comment] 2017-01-22 06:52
Also which OS are you running this on? I have only tested on Win10 so far. I am wondering whether loading the DLL fails on other OS'es because of the the `RRF_SUBKEY_WOW6432KEY` flag in `WinFspLoad`.

**Comment by billziss-gh** [comment] 2017-01-23 19:00
I have written a tutorial on creating a new file system: [WinFsp Tutorial](https://github.com/billziss-gh/winfsp/wiki/WinFsp-Tutorial).

**Comment by billziss-gh** [comment] 2017-01-31 20:31
> I compiled the passthrough in VS2015, but it not work.
>
>     passthrough-x86.exe -d -1 -D - -p D:\MyDir -m Z:
>     passthrough -p D:\MyDir -m Z:
>     The service passthrough has been started.
>
> Then I open explorer, passthrough-x86.exe failure and exit.

I can confirm that there was a problem in the x86 version that has been fixed. The fix should be included in WinFsp RC2 (coming soon), which will include the passthrough file system as a sample.

BTW, there is now also a passthrough-fuse file system that will also be included as a sample in RC2.

**Comment by billziss-gh** [comment] 2017-02-05 00:04
Closing this as the tutorial and file system are now complete. The passthrough file system will be included in the RC2 installer, due soon.

**Closed by billziss-gh** 2017-02-05 00:04 UTC
Labels: in progress, task
