### ISSUE TITLE
Cygfuse fs: not possible to mount a network share as source folder using the registry

### ISSUE THREAD

**Issue by hasse69** [billziss-gh/winfsp#89] opened 2017-05-25 12:52 UTC
While testing the `cygfuse` port of `rar2fs` I stumbled into a small problem. A rather feasible use case would be to have a network share exporting a lot of files and then use `rar2fs` to mount that onto a local drive.
But I cannot get that to work through the Windows registry entry and using the explorer or `launchctl`.
The below error is what I receive, which is the same as if I had provided a source folder that does not exists. 

![image](https://cloud.githubusercontent.com/assets/1021198/26451063/aff2da6c-415a-11e7-83df-ba85b10439ee.png)

It however works fine to specify a source folder like that by doing a manual mount as
```
>c:\cygwin\home\user\rar2fs.exe \\nas\share i: --VolumePrefix=\rar2fs\share
rar2fs: PID 3172: mounted i:
The service rar2fs has been started.
```
I have tried several different syntax variants in the `CommandLine` registry entry, all failing miserably.
Any ideas what might be going wrong here? Is there something that is actually not supported or limited in the WinFSP network layer/helper? What I can do is to log to file what actual source path `rar2fs` gets, but maybe the cause of this is already known?

**Comment by billziss-gh** [comment] 2017-05-25 17:47
I am not aware of any such issue. My only guess is that the path that rar2fs gets to open is somehow mangled.

I also note that rar2fs is a Cygwin program so backslash handling in `\\nas\share` may be an issue as well.

**Comment by hasse69** [comment] 2017-05-25 18:06
> I also note that rar2fs is a Cygwin program so backslash handling in \\nas\share may be an issue as well.

Since it works using the manual method that is very unlikely to be the problem?

**Comment by hasse69** [comment] 2017-05-25 18:43
There is no difference in what `rar2fs` gets in the two cases?
The working "manual" case starting `rar2fs` in the foreground:
```
argv[0] = >>/home/user/rar2fs<<<
argv[1] = >>-f<<<
argv[2] = >>\\nas\share<<<
argv[3] = >>j:<<<
argv[4] = >>--VolumePrefix=\rar2fs\share<<<
argv[5] = >>-o<<<
argv[6] = >>umask=000<<<
```
The non-working case from the explorer
```
argv[0] = >>/home/user/rar2fs<<<
argv[1] = >>\\nas\share<<<
argv[2] = >>J:<<<
argv[3] = >>--VolumePrefix=\rar2fs\share<<<
argv[4] = >>-o<<<
argv[5] = >>umask=000<<<
```
There must be a difference in what context rar2fs is invoked in these two cases which "hides" `\\nas\share`?

**Comment by billziss-gh** [comment] 2017-05-25 18:49
> There must be a difference in what context rar2fs is invoked in these two cases which "hides" \\nas\share?

YES! In this case rar2fs runs under the SYSTEM account rather than your local account. I do not know the implications of this for accessing your `\\nas\share` storage.

One way to debug this is to start rar2fs yourself under SYSTEM using the psexec utiilty:

https://technet.microsoft.com/en-us/sysinternals/bb897553.aspx

Something like this should start you a command prompt running under SYSTEM:

```
> psexec -i -d -s cmd.exe
```

**Comment by billziss-gh** [comment] 2017-05-25 18:55
Actually I think the problem is that you start the file system without the `-f` switch when starting from Explorer:

>```
>argv[0] = >>/home/user/rar2fs<<<
>argv[1] = >>\\nas\share<<<
>argv[2] = >>J:<<<
>argv[3] = >>--VolumePrefix=\rar2fs\share<<<
>argv[4] = >>-o<<<
>argv[5] = >>umask=000<<<
>```

There is no `-f` switch here. You cannot daemonize a process and expect it to be controlled by the launcher.

**Comment by billziss-gh** [comment] 2017-05-25 18:57
This may even explain #90.

**Comment by hasse69** [comment] 2017-05-25 19:20
Actually it explains #90 but it has nothing to do with this issue. It works manually also without the -f switch. This has something to do with visibility and access. Even if we can prove that the SYSTEM account does not see my shares, how can we ever make it possible to mount a share like this. It does not help trying to `subst` or assign it to a drive letter. If the share cannot be "discovered" it does not really make any difference how it is accessed.

**Comment by hasse69** [comment] 2017-05-25 19:29
Yepp, `SYSTEM` has limited access to my shares
From a `cmd.exe` spawned using `psexec`
```
C:\WINDOWS\system32>dir \\nas01\share
ls: cannot open directory '\\nas\share': Permission denied

C:\WINDOWS\system32>
```
From a standard `cmd.exe`
```
C:\Users\Hasse>dir \\nas\share
 Volume in drive \\nas\share is share
 Volume Serial Number is 03F0-05A3

 Directory of \\nas\share

2016-09-04  15:51    <DIR>          .
2016-06-29  00:08    <DIR>          ..
2010-10-18  22:01    <DIR>          misc
2011-02-25  22:42    <DIR>          incoming
2016-09-04  15:51    <DIR>          tmp
2016-03-04  21:07    <DIR>          export
               0 File(s)              0 bytes
               6 Dir(s)  1 283 909 505 024 bytes free
```

**Comment by billziss-gh** [comment] 2017-05-25 19:45
I believe this is beyond the scope of a WinFsp issue. However I am happy to help if I can.

The most likely reason that the share is not accessible is because you have connected to it using your local account credentials. The SYSTEM account has different credentials and therefore cannot see it.

Does `net use n: \\nas\share` help at all?

**Comment by hasse69** [comment] 2017-05-25 19:56
> I believe this is beyond the scope of a WinFsp issue. However I am happy to help if I can.

Agreed. But if you can help in any way I would really appreciate it :)

> Does net use n: \\nas\share help at all?

That was the first thing I tried actually. But assigning the share to a drive makes no difference. Actually the drive cannot even be seen from any other account than the one that created it.
So question  is then, how can I either mount a share by-passing the `SYSTEM` user or make the `SYSTEM` user the owner of the share?

**Comment by billziss-gh** [comment] 2017-05-25 20:06
A couple of suggestions:

- The SYSTEM account is one of the most powerful accounts in a Windows system. It is also part of the Administrators group. https://msdn.microsoft.com/en-us/library/windows/desktop/ms684190(v=vs.85).aspx

- See this stackoverflow article: https://serverfault.com/questions/135867/how-to-grant-network-access-to-localsystem-account#135874

- For some time, I have been thinking about enhancing the launcher infrastructure to also pass the username of the account that maps the network drive. This would allow a file system running under the SYSTEM account to impersonate a local account which has various benefits including accessing the same resources like the local account. Perhaps we should open such an issue and make it higher priority.

**Comment by hasse69** [comment] 2017-05-25 20:30
> See this stackoverflow article: https://serverfault.com/questions/135867/how-to-grant-network-access-to-localsystem-account#135874

Right. And the following caught my attention...

>You don't. If you need a service to connect to remote files or other network services, then you want to have the service run as a named account, and on the remote machine, assign rights to that named account.

Is this not exactly what you enhancements are all about? In that case I would really like this being put a bit higher on the priority list. Since file systems like `rar2fs` typically would want to mount shares from external resources it would be great if this could enable such usage.

**Comment by billziss-gh** [comment] 2017-05-25 20:57
> Is this not exactly what you enhancements are all about? In that case I would really like this being put a bit higher on the priority list. Since file systems like rar2fs typically would want to mount shares from external resources it would be great if this could enable such usage.

Fair enough. I will add an enhancement issue, but cannot promise a quick delivery at this time.

Or maybe (just maybe :) you would consider adding this as an enhancement yourself? I would provide full support of course. Here is what the idea is:

- The network provider component of the WinFsp DLL receives a user name at [`NPAddConnection`](https://github.com/billziss-gh/winfsp/blob/v1.0/src/dll/np.c#L483). If this is not adequate we may be able to get it by doing [`GetUserName`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724432(v=vs.85).aspx) or [`GetUserNameEx`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724435(v=vs.85).aspx).

- It passes this to the launcher as a third argument (`%3`) [here](https://github.com/billziss-gh/winfsp/blob/v1.0/src/dll/np.c#L573). I notice that there is already some support for sending additional arguments to the launcher for file systems that need password access (e.g. sshfs), so we may be able to just retrofit this.

**Comment by hasse69** [comment] 2017-05-25 21:09
>Fair enough. I will add an enhancement issue, but cannot promise a quick delivery at this time.

That is ok. I just found a hairy workaround that actually works but is far from "clean".
By going into the network settings for the exported share and changing security setting for it and setting `SYSTEM` as effective permission user I could access the share using `net use` (from a `cmd.exe` spawned by `psexec`) and assign it to a drive letter. That drive is marked with a red cross for my normal user in the explorer but it could be used as source drive for the mount in the registry entry for `rar2fs`.  Voila!

> Or maybe (just maybe :) you would consider adding this as an enhancement yourself? I would provide full support of course. Here is what the idea is:

I do not think I am qualified for such a great task :)

**Comment by billziss-gh** [comment] 2017-05-25 21:14
> That is ok. I just found a hairy workaround that actually works but is far from "clean".

Good work.

> I do not think I am qualified for such a great task :)

No problem. I will look at it myself at some point in the future. It may be a while though.

----

Should we close this now that you have a workaround and we also have a solid action item for the future?

**Comment by hasse69** [comment] 2017-05-25 21:33
The key here is that when using `net use` to map the drive you will be asked for credentials in the form of a user and password. While the drive is mapped you can access it from the `SYSTEM` account as either the drive letter or the UNC. If you disconnect the drive credentials will be lost.

Agree. You can close this issue and refer to a future real solution.

**Comment by hasse69** [comment] 2017-05-25 22:59
Actually if you use the `/SAVECRED` option to `net use` when providing the user/password any mounts made by WinFSP afterwards will stay even after reboot together with the network drive (if that was selected).

**Comment by billziss-gh** [comment] 2017-05-25 23:14
> Agree. You can close this issue and refer to a future real solution.

Ok, closing this.

> Actually if you use the /SAVECRED option to net use when providing the user/password any mounts made by WinFSP afterwards will stay even after reboot together with its network drive (if desired). 

Yes. Another way is to select the "Reconnect at sign-in" option in Windows Explorer during "Map Network Drive".

**Closed by billziss-gh** 2017-05-25 23:14 UTC

**Comment by hasse69** [comment] 2017-05-26 07:28
> Yes. Another way is to select the "Reconnect at sign-in" option in Windows Explorer during "Map Network Drive".

Well, that was the "if desired" part I mentioned. The `/SAVECRED' has nothing to do with a mount surviving a system reboot or not. It is for the `SYSTEM` user to remember credentials given for the network share so you do not need to repeat entering user/password after boot. Effectively meaning that even if you chose to release the mount after reboot you can mount it again without the need for the `psexec` etc.
